// Code generated by MockGen. DO NOT EDIT.
// Source: ./producer.go
//
// Generated by this command:
//
//	mockgen -source=./producer.go -package=evtmocks -destination=./mocks/producer.mock.go -typed NewFieldSecureAttrChangeEventProducer
//

// Package evtmocks is a generated GoMock package.
package evtmocks

import (
	context "context"
	reflect "reflect"

	event "github.com/Duke1616/ecmdb/internal/attribute/internal/event"
	gomock "go.uber.org/mock/gomock"
)

// MockFieldSecureAttrChangeEventProducer is a mock of FieldSecureAttrChangeEventProducer interface.
type MockFieldSecureAttrChangeEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockFieldSecureAttrChangeEventProducerMockRecorder
	isgomock struct{}
}

// MockFieldSecureAttrChangeEventProducerMockRecorder is the mock recorder for MockFieldSecureAttrChangeEventProducer.
type MockFieldSecureAttrChangeEventProducerMockRecorder struct {
	mock *MockFieldSecureAttrChangeEventProducer
}

// NewMockFieldSecureAttrChangeEventProducer creates a new mock instance.
func NewMockFieldSecureAttrChangeEventProducer(ctrl *gomock.Controller) *MockFieldSecureAttrChangeEventProducer {
	mock := &MockFieldSecureAttrChangeEventProducer{ctrl: ctrl}
	mock.recorder = &MockFieldSecureAttrChangeEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFieldSecureAttrChangeEventProducer) EXPECT() *MockFieldSecureAttrChangeEventProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockFieldSecureAttrChangeEventProducer) Produce(ctx context.Context, evt event.FieldSecureAttrChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockFieldSecureAttrChangeEventProducerMockRecorder) Produce(ctx, evt any) *MockFieldSecureAttrChangeEventProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockFieldSecureAttrChangeEventProducer)(nil).Produce), ctx, evt)
	return &MockFieldSecureAttrChangeEventProducerProduceCall{Call: call}
}

// MockFieldSecureAttrChangeEventProducerProduceCall wrap *gomock.Call
type MockFieldSecureAttrChangeEventProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFieldSecureAttrChangeEventProducerProduceCall) Return(arg0 error) *MockFieldSecureAttrChangeEventProducerProduceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFieldSecureAttrChangeEventProducerProduceCall) Do(f func(context.Context, event.FieldSecureAttrChange) error) *MockFieldSecureAttrChangeEventProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFieldSecureAttrChangeEventProducerProduceCall) DoAndReturn(f func(context.Context, event.FieldSecureAttrChange) error) *MockFieldSecureAttrChangeEventProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
