// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=workflowmocks -destination=../../mocks/workflow.mock.go -typed Service
//

// Package workflowmocks is a generated GoMock package.
package workflowmocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Bunny3th/easy-workflow/workflow/model"
	domain "github.com/Duke1616/ecmdb/internal/workflow/internal/domain"
	service "github.com/Duke1616/ecmdb/internal/workflow/internal/service"
	easyflow "github.com/Duke1616/ecmdb/internal/workflow/pkg/easyflow"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AdminNotifyBinding mocks base method.
func (m *MockService) AdminNotifyBinding() service.AdminNotifyBindingService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminNotifyBinding")
	ret0, _ := ret[0].(service.AdminNotifyBindingService)
	return ret0
}

// AdminNotifyBinding indicates an expected call of AdminNotifyBinding.
func (mr *MockServiceMockRecorder) AdminNotifyBinding() *MockServiceAdminNotifyBindingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminNotifyBinding", reflect.TypeOf((*MockService)(nil).AdminNotifyBinding))
	return &MockServiceAdminNotifyBindingCall{Call: call}
}

// MockServiceAdminNotifyBindingCall wrap *gomock.Call
type MockServiceAdminNotifyBindingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAdminNotifyBindingCall) Return(arg0 service.AdminNotifyBindingService) *MockServiceAdminNotifyBindingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAdminNotifyBindingCall) Do(f func() service.AdminNotifyBindingService) *MockServiceAdminNotifyBindingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAdminNotifyBindingCall) DoAndReturn(f func() service.AdminNotifyBindingService) *MockServiceAdminNotifyBindingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *MockServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
	return &MockServiceCreateCall{Call: call}
}

// MockServiceCreateCall wrap *gomock.Call
type MockServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateCall) Return(arg0 int64, arg1 error) *MockServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateCall) Do(f func(context.Context, domain.Workflow) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateCall) DoAndReturn(f func(context.Context, domain.Workflow) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *MockServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
	return &MockServiceDeleteCall{Call: call}
}

// MockServiceDeleteCall wrap *gomock.Call
type MockServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteCall) Return(arg0 int64, arg1 error) *MockServiceDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Deploy mocks base method.
func (m *MockService) Deploy(ctx context.Context, flow domain.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, flow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockServiceMockRecorder) Deploy(ctx, flow any) *MockServiceDeployCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockService)(nil).Deploy), ctx, flow)
	return &MockServiceDeployCall{Call: call}
}

// MockServiceDeployCall wrap *gomock.Call
type MockServiceDeployCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeployCall) Return(arg0 error) *MockServiceDeployCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeployCall) Do(f func(context.Context, domain.Workflow) error) *MockServiceDeployCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeployCall) DoAndReturn(f func(context.Context, domain.Workflow) error) *MockServiceDeployCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockService) Find(ctx context.Context, id int64) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockServiceMockRecorder) Find(ctx, id any) *MockServiceFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockService)(nil).Find), ctx, id)
	return &MockServiceFindCall{Call: call}
}

// MockServiceFindCall wrap *gomock.Call
type MockServiceFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindCall) Return(arg0 domain.Workflow, arg1 error) *MockServiceFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindCall) Do(f func(context.Context, int64) (domain.Workflow, error)) *MockServiceFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindCall) DoAndReturn(f func(context.Context, int64) (domain.Workflow, error)) *MockServiceFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByKeyword mocks base method.
func (m *MockService) FindByKeyword(ctx context.Context, keyword string, offset, limit int64) ([]domain.Workflow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeyword", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByKeyword indicates an expected call of FindByKeyword.
func (mr *MockServiceMockRecorder) FindByKeyword(ctx, keyword, offset, limit any) *MockServiceFindByKeywordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyword", reflect.TypeOf((*MockService)(nil).FindByKeyword), ctx, keyword, offset, limit)
	return &MockServiceFindByKeywordCall{Call: call}
}

// MockServiceFindByKeywordCall wrap *gomock.Call
type MockServiceFindByKeywordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindByKeywordCall) Return(arg0 []domain.Workflow, arg1 int64, arg2 error) *MockServiceFindByKeywordCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindByKeywordCall) Do(f func(context.Context, string, int64, int64) ([]domain.Workflow, int64, error)) *MockServiceFindByKeywordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindByKeywordCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.Workflow, int64, error)) *MockServiceFindByKeywordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindInstanceFlow mocks base method.
func (m *MockService) FindInstanceFlow(ctx context.Context, workflowID int64, processID, version int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInstanceFlow", ctx, workflowID, processID, version)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInstanceFlow indicates an expected call of FindInstanceFlow.
func (mr *MockServiceMockRecorder) FindInstanceFlow(ctx, workflowID, processID, version any) *MockServiceFindInstanceFlowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInstanceFlow", reflect.TypeOf((*MockService)(nil).FindInstanceFlow), ctx, workflowID, processID, version)
	return &MockServiceFindInstanceFlowCall{Call: call}
}

// MockServiceFindInstanceFlowCall wrap *gomock.Call
type MockServiceFindInstanceFlowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindInstanceFlowCall) Return(arg0 domain.Workflow, arg1 error) *MockServiceFindInstanceFlowCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindInstanceFlowCall) Do(f func(context.Context, int64, int, int) (domain.Workflow, error)) *MockServiceFindInstanceFlowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindInstanceFlowCall) DoAndReturn(f func(context.Context, int64, int, int) (domain.Workflow, error)) *MockServiceFindInstanceFlowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindPassEdgeIds mocks base method.
func (m *MockService) FindPassEdgeIds(ctx context.Context, wf domain.Workflow, tasks []model.Task) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPassEdgeIds", ctx, wf, tasks)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPassEdgeIds indicates an expected call of FindPassEdgeIds.
func (mr *MockServiceMockRecorder) FindPassEdgeIds(ctx, wf, tasks any) *MockServiceFindPassEdgeIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPassEdgeIds", reflect.TypeOf((*MockService)(nil).FindPassEdgeIds), ctx, wf, tasks)
	return &MockServiceFindPassEdgeIdsCall{Call: call}
}

// MockServiceFindPassEdgeIdsCall wrap *gomock.Call
type MockServiceFindPassEdgeIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindPassEdgeIdsCall) Return(arg0 []string, arg1 error) *MockServiceFindPassEdgeIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindPassEdgeIdsCall) Do(f func(context.Context, domain.Workflow, []model.Task) ([]string, error)) *MockServiceFindPassEdgeIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindPassEdgeIdsCall) DoAndReturn(f func(context.Context, domain.Workflow, []model.Task) ([]string, error)) *MockServiceFindPassEdgeIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAutomationProperty mocks base method.
func (m *MockService) GetAutomationProperty(workflow easyflow.Workflow, nodeId string) (easyflow.AutomationProperty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationProperty", workflow, nodeId)
	ret0, _ := ret[0].(easyflow.AutomationProperty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationProperty indicates an expected call of GetAutomationProperty.
func (mr *MockServiceMockRecorder) GetAutomationProperty(workflow, nodeId any) *MockServiceGetAutomationPropertyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationProperty", reflect.TypeOf((*MockService)(nil).GetAutomationProperty), workflow, nodeId)
	return &MockServiceGetAutomationPropertyCall{Call: call}
}

// MockServiceGetAutomationPropertyCall wrap *gomock.Call
type MockServiceGetAutomationPropertyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetAutomationPropertyCall) Return(arg0 easyflow.AutomationProperty, arg1 error) *MockServiceGetAutomationPropertyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetAutomationPropertyCall) Do(f func(easyflow.Workflow, string) (easyflow.AutomationProperty, error)) *MockServiceGetAutomationPropertyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetAutomationPropertyCall) DoAndReturn(f func(easyflow.Workflow, string) (easyflow.AutomationProperty, error)) *MockServiceGetAutomationPropertyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWorkflowSnapshot mocks base method.
func (m *MockService) GetWorkflowSnapshot(ctx context.Context, processID, version int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowSnapshot", ctx, processID, version)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowSnapshot indicates an expected call of GetWorkflowSnapshot.
func (mr *MockServiceMockRecorder) GetWorkflowSnapshot(ctx, processID, version any) *MockServiceGetWorkflowSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowSnapshot", reflect.TypeOf((*MockService)(nil).GetWorkflowSnapshot), ctx, processID, version)
	return &MockServiceGetWorkflowSnapshotCall{Call: call}
}

// MockServiceGetWorkflowSnapshotCall wrap *gomock.Call
type MockServiceGetWorkflowSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetWorkflowSnapshotCall) Return(arg0 domain.Workflow, arg1 error) *MockServiceGetWorkflowSnapshotCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetWorkflowSnapshotCall) Do(f func(context.Context, int, int) (domain.Workflow, error)) *MockServiceGetWorkflowSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetWorkflowSnapshotCall) DoAndReturn(f func(context.Context, int, int) (domain.Workflow, error)) *MockServiceGetWorkflowSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, offset, limit int64) ([]domain.Workflow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, offset, limit any) *MockServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, offset, limit)
	return &MockServiceListCall{Call: call}
}

// MockServiceListCall wrap *gomock.Call
type MockServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListCall) Return(arg0 []domain.Workflow, arg1 int64, arg2 error) *MockServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListCall) Do(f func(context.Context, int64, int64) ([]domain.Workflow, int64, error)) *MockServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Workflow, int64, error)) *MockServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *MockServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
	return &MockServiceUpdateCall{Call: call}
}

// MockServiceUpdateCall wrap *gomock.Call
type MockServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateCall) Return(arg0 int64, arg1 error) *MockServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateCall) Do(f func(context.Context, domain.Workflow) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Workflow) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAdminNotifyBindingService is a mock of AdminNotifyBindingService interface.
type MockAdminNotifyBindingService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminNotifyBindingServiceMockRecorder
	isgomock struct{}
}

// MockAdminNotifyBindingServiceMockRecorder is the mock recorder for MockAdminNotifyBindingService.
type MockAdminNotifyBindingServiceMockRecorder struct {
	mock *MockAdminNotifyBindingService
}

// NewMockAdminNotifyBindingService creates a new mock instance.
func NewMockAdminNotifyBindingService(ctrl *gomock.Controller) *MockAdminNotifyBindingService {
	mock := &MockAdminNotifyBindingService{ctrl: ctrl}
	mock.recorder = &MockAdminNotifyBindingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminNotifyBindingService) EXPECT() *MockAdminNotifyBindingServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminNotifyBindingService) Create(ctx context.Context, n domain.NotifyBinding) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdminNotifyBindingServiceMockRecorder) Create(ctx, n any) *MockAdminNotifyBindingServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminNotifyBindingService)(nil).Create), ctx, n)
	return &MockAdminNotifyBindingServiceCreateCall{Call: call}
}

// MockAdminNotifyBindingServiceCreateCall wrap *gomock.Call
type MockAdminNotifyBindingServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminNotifyBindingServiceCreateCall) Return(arg0 int64, arg1 error) *MockAdminNotifyBindingServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminNotifyBindingServiceCreateCall) Do(f func(context.Context, domain.NotifyBinding) (int64, error)) *MockAdminNotifyBindingServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminNotifyBindingServiceCreateCall) DoAndReturn(f func(context.Context, domain.NotifyBinding) (int64, error)) *MockAdminNotifyBindingServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockAdminNotifyBindingService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminNotifyBindingServiceMockRecorder) Delete(ctx, id any) *MockAdminNotifyBindingServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminNotifyBindingService)(nil).Delete), ctx, id)
	return &MockAdminNotifyBindingServiceDeleteCall{Call: call}
}

// MockAdminNotifyBindingServiceDeleteCall wrap *gomock.Call
type MockAdminNotifyBindingServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminNotifyBindingServiceDeleteCall) Return(arg0 int64, arg1 error) *MockAdminNotifyBindingServiceDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminNotifyBindingServiceDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockAdminNotifyBindingServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminNotifyBindingServiceDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockAdminNotifyBindingServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEffective mocks base method.
func (m *MockAdminNotifyBindingService) GetEffective(ctx context.Context, workflowId int64, notifyType domain.NotifyType, channel string) (domain.NotifyBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEffective", ctx, workflowId, notifyType, channel)
	ret0, _ := ret[0].(domain.NotifyBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEffective indicates an expected call of GetEffective.
func (mr *MockAdminNotifyBindingServiceMockRecorder) GetEffective(ctx, workflowId, notifyType, channel any) *MockAdminNotifyBindingServiceGetEffectiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEffective", reflect.TypeOf((*MockAdminNotifyBindingService)(nil).GetEffective), ctx, workflowId, notifyType, channel)
	return &MockAdminNotifyBindingServiceGetEffectiveCall{Call: call}
}

// MockAdminNotifyBindingServiceGetEffectiveCall wrap *gomock.Call
type MockAdminNotifyBindingServiceGetEffectiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminNotifyBindingServiceGetEffectiveCall) Return(arg0 domain.NotifyBinding, arg1 error) *MockAdminNotifyBindingServiceGetEffectiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminNotifyBindingServiceGetEffectiveCall) Do(f func(context.Context, int64, domain.NotifyType, string) (domain.NotifyBinding, error)) *MockAdminNotifyBindingServiceGetEffectiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminNotifyBindingServiceGetEffectiveCall) DoAndReturn(f func(context.Context, int64, domain.NotifyType, string) (domain.NotifyBinding, error)) *MockAdminNotifyBindingServiceGetEffectiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockAdminNotifyBindingService) List(ctx context.Context, workflowId int64) ([]domain.NotifyBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workflowId)
	ret0, _ := ret[0].([]domain.NotifyBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdminNotifyBindingServiceMockRecorder) List(ctx, workflowId any) *MockAdminNotifyBindingServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminNotifyBindingService)(nil).List), ctx, workflowId)
	return &MockAdminNotifyBindingServiceListCall{Call: call}
}

// MockAdminNotifyBindingServiceListCall wrap *gomock.Call
type MockAdminNotifyBindingServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminNotifyBindingServiceListCall) Return(arg0 []domain.NotifyBinding, arg1 error) *MockAdminNotifyBindingServiceListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminNotifyBindingServiceListCall) Do(f func(context.Context, int64) ([]domain.NotifyBinding, error)) *MockAdminNotifyBindingServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminNotifyBindingServiceListCall) DoAndReturn(f func(context.Context, int64) ([]domain.NotifyBinding, error)) *MockAdminNotifyBindingServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockAdminNotifyBindingService) Update(ctx context.Context, n domain.NotifyBinding) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, n)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAdminNotifyBindingServiceMockRecorder) Update(ctx, n any) *MockAdminNotifyBindingServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdminNotifyBindingService)(nil).Update), ctx, n)
	return &MockAdminNotifyBindingServiceUpdateCall{Call: call}
}

// MockAdminNotifyBindingServiceUpdateCall wrap *gomock.Call
type MockAdminNotifyBindingServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdminNotifyBindingServiceUpdateCall) Return(arg0 int64, arg1 error) *MockAdminNotifyBindingServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdminNotifyBindingServiceUpdateCall) Do(f func(context.Context, domain.NotifyBinding) (int64, error)) *MockAdminNotifyBindingServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdminNotifyBindingServiceUpdateCall) DoAndReturn(f func(context.Context, domain.NotifyBinding) (int64, error)) *MockAdminNotifyBindingServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
