// Code generated by MockGen. DO NOT EDIT.
// Source: ./resolve.go
//
// Generated by this command:
//
//	mockgen -source=./resolve.go -package=resolveblocks -destination=./mocks/resolve.mock.go -typed Engine
//

// Package resolveblocks is a generated GoMock package.
package resolveblocks

import (
	context "context"
	reflect "reflect"

	user "github.com/Duke1616/ecmdb/internal/user"
	resolve "github.com/Duke1616/ecmdb/pkg/resolve"
	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockResolver) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockResolverMockRecorder) Name() *MockResolverNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockResolver)(nil).Name))
	return &MockResolverNameCall{Call: call}
}

// MockResolverNameCall wrap *gomock.Call
type MockResolverNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResolverNameCall) Return(arg0 string) *MockResolverNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResolverNameCall) Do(f func() string) *MockResolverNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResolverNameCall) DoAndReturn(f func() string) *MockResolverNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Resolve mocks base method.
func (m *MockResolver) Resolve(ctx context.Context, target resolve.Target) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, target)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder) Resolve(ctx, target any) *MockResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver)(nil).Resolve), ctx, target)
	return &MockResolverResolveCall{Call: call}
}

// MockResolverResolveCall wrap *gomock.Call
type MockResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResolverResolveCall) Return(arg0 []user.User, arg1 error) *MockResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResolverResolveCall) Do(f func(context.Context, resolve.Target) ([]user.User, error)) *MockResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResolverResolveCall) DoAndReturn(f func(context.Context, resolve.Target) ([]user.User, error)) *MockResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
	isgomock struct{}
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockEngine) Register(resolvers ...resolve.Resolver) resolve.Engine {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range resolvers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(resolve.Engine)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockEngineMockRecorder) Register(resolvers ...any) *MockEngineRegisterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockEngine)(nil).Register), resolvers...)
	return &MockEngineRegisterCall{Call: call}
}

// MockEngineRegisterCall wrap *gomock.Call
type MockEngineRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineRegisterCall) Return(arg0 resolve.Engine) *MockEngineRegisterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineRegisterCall) Do(f func(...resolve.Resolver) resolve.Engine) *MockEngineRegisterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineRegisterCall) DoAndReturn(f func(...resolve.Resolver) resolve.Engine) *MockEngineRegisterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Resolve mocks base method.
func (m *MockEngine) Resolve(ctx context.Context, targets []resolve.Target) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, targets)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockEngineMockRecorder) Resolve(ctx, targets any) *MockEngineResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockEngine)(nil).Resolve), ctx, targets)
	return &MockEngineResolveCall{Call: call}
}

// MockEngineResolveCall wrap *gomock.Call
type MockEngineResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineResolveCall) Return(arg0 []user.User, arg1 error) *MockEngineResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineResolveCall) Do(f func(context.Context, []resolve.Target) ([]user.User, error)) *MockEngineResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineResolveCall) DoAndReturn(f func(context.Context, []resolve.Target) ([]user.User, error)) *MockEngineResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveWithErrorHandling mocks base method.
func (m *MockEngine) ResolveWithErrorHandling(ctx context.Context, targets []resolve.Target, failFast bool) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveWithErrorHandling", ctx, targets, failFast)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveWithErrorHandling indicates an expected call of ResolveWithErrorHandling.
func (mr *MockEngineMockRecorder) ResolveWithErrorHandling(ctx, targets, failFast any) *MockEngineResolveWithErrorHandlingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveWithErrorHandling", reflect.TypeOf((*MockEngine)(nil).ResolveWithErrorHandling), ctx, targets, failFast)
	return &MockEngineResolveWithErrorHandlingCall{Call: call}
}

// MockEngineResolveWithErrorHandlingCall wrap *gomock.Call
type MockEngineResolveWithErrorHandlingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineResolveWithErrorHandlingCall) Return(arg0 []user.User, arg1 error) *MockEngineResolveWithErrorHandlingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineResolveWithErrorHandlingCall) Do(f func(context.Context, []resolve.Target, bool) ([]user.User, error)) *MockEngineResolveWithErrorHandlingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineResolveWithErrorHandlingCall) DoAndReturn(f func(context.Context, []resolve.Target, bool) ([]user.User, error)) *MockEngineResolveWithErrorHandlingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
