// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package policy

import (
	"github.com/Duke1616/ecmdb/internal/policy/internal/grpc"
	"github.com/Duke1616/ecmdb/internal/policy/internal/service"
	"github.com/Duke1616/ecmdb/internal/policy/internal/web"
	"github.com/casbin/casbin/v2"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(enforcer *casbin.SyncedEnforcer) (*Module, error) {
	serviceService := service.NewService(enforcer)
	handler := web.NewHandler(serviceService)
	policyServer := grpc.NewPolicyServer(serviceService)
	module := &Module{
		Hdl:       handler,
		Svc:       serviceService,
		RpcServer: policyServer,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, grpc.NewPolicyServer)
