// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dataio

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/dataio/internal/service"
	"github.com/Duke1616/ecmdb/internal/dataio/internal/web"
	"github.com/Duke1616/ecmdb/internal/model"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/Duke1616/ecmdb/pkg/storage"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(attributeModule *attribute.Module, resourceModule *resource.Module, storage2 *storage.S3Storage, modelModule *model.Module) (*Module, error) {
	serviceService := attributeModule.Svc
	encryptedSvc := resourceModule.EncryptedSvc
	service2 := modelModule.Svc
	iDataIOService := service.NewDataIOService(serviceService, encryptedSvc, service2)
	handler := web.NewHandler(iDataIOService, storage2)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

// ProviderSet 数据交换模块依赖集合
var ProviderSet = wire.NewSet(web.NewHandler, service.NewDataIOService)
