// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/attribute/internal/web"
)

// Injectors from wire.go:

func InitHandler() (*web.Handler, error) {
	mongo := InitMongoDB()
	mq := InitMQ()
	module, err := attribute.InitModule(mongo, mq)
	if err != nil {
		return nil, err
	}
	handler := module.Hdl
	return handler, nil
}
