// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package workflow

import (
	"github.com/Duke1616/ecmdb/internal/engine"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/repository"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/service"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/web"
	"github.com/Duke1616/ecmdb/internal/workflow/pkg/easyflow"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, engineModule *engine.Module) (*Module, error) {
	workflowDAO := dao.NewWorkflowDAO(db)
	snapshotDAO := dao.NewSnapshotDAO(db)
	workflowRepository := repository.NewWorkflowRepository(workflowDAO, snapshotDAO)
	notifyBindingDAO := dao.NewNotifyBindingDAO(db)
	notifyBindingRepository := repository.NewNotifyBindingRepository(notifyBindingDAO)
	serviceService := engineModule.Svc
	processEngineConvert := easyflow.NewLogicFlowToEngineConvert()
	service2 := service.NewService(workflowRepository, notifyBindingRepository, serviceService, processEngineConvert)
	handler := web.NewHandler(service2, serviceService)
	module := &Module{
		Hdl: handler,
		Svc: service2,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewWorkflowRepository, repository.NewNotifyBindingRepository, dao.NewWorkflowDAO, dao.NewSnapshotDAO, dao.NewNotifyBindingDAO, easyflow.NewLogicFlowToEngineConvert)
