// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package workflow

import (
	"github.com/Duke1616/ecmdb/internal/workflow/internal/repository"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/service"
	"github.com/Duke1616/ecmdb/internal/workflow/internal/web"
	"github.com/Duke1616/ecmdb/internal/workflow/pkg/easyflow"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	workflowDAO := dao.NewWorkflowDAO(db)
	workflowRepository := repository.NewWorkflowRepository(workflowDAO)
	processEngineConvert := easyflow.NewLogicFlowToEngineConvert()
	serviceService := service.NewService(workflowRepository, processEngineConvert)
	handler := web.NewHandler(serviceService)
	module := &Module{
		Hdl: handler,
		Svc: serviceService,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewWorkflowRepository, dao.NewWorkflowDAO, easyflow.NewLogicFlowToEngineConvert)
