// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package relation

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/relation/internal/repository"
	"github.com/Duke1616/ecmdb/internal/relation/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/relation/internal/service"
	"github.com/Duke1616/ecmdb/internal/relation/internal/web"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitModule(db *mongo.Client, attributeModel *attribute.Module, resourceModel *resource.Module) (*Module, error) {
	relationResourceDAO := dao.NewRelationResourceDAO(db)
	relationResourceRepository := repository.NewRelationResourceRepository(relationResourceDAO)
	relationResourceService := service.NewRelationResourceService(relationResourceRepository)
	relationModelDAO := dao.NewRelationModelDAO(db)
	relationModelRepository := repository.NewRelationModelRepository(relationModelDAO)
	relationModelService := service.NewRelationModelService(relationModelRepository)
	serviceService := attributeModel.Svc
	service2 := resourceModel.Svc
	relationResourceHandler := web.NewRelationResourceHandler(relationResourceService, serviceService, service2)
	relationModelHandler := web.NewRelationModelHandler(relationModelService)
	module := &Module{
		RRSvc: relationResourceService,
		RMSvc: relationModelService,
		RRHdl: relationResourceHandler,
		RMHdl: relationModelHandler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewRelationResourceHandler, web.NewRelationModelHandler, service.NewRelationResourceService, service.NewRelationModelService, repository.NewRelationModelRepository, repository.NewRelationResourceRepository, dao.NewRelationModelDAO, dao.NewRelationResourceDAO)
