// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package relation

import (
	"github.com/Duke1616/ecmdb/internal/relation/internal/repository"
	"github.com/Duke1616/ecmdb/internal/relation/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/relation/internal/service"
	"github.com/Duke1616/ecmdb/internal/relation/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitHandler(db *mongo.Client) *web.Handler {
	relationDAO := dao.NewRelationDAO(db)
	relationRepository := repository.NewRelationRepository(relationDAO)
	serviceService := service.NewService(relationRepository)
	handler := web.NewHandler(serviceService)
	return handler
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewRelationRepository, dao.NewRelationDAO)

type Handler = web.Handler
