// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=departmentmocks -destination=../../mocks/department.mock.go -typed Service
//

// Package departmentmocks is a generated GoMock package.
package departmentmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/department/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockService) CreateDepartment(ctx context.Context, req domain.Department) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockServiceMockRecorder) CreateDepartment(ctx, req any) *MockServiceCreateDepartmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockService)(nil).CreateDepartment), ctx, req)
	return &MockServiceCreateDepartmentCall{Call: call}
}

// MockServiceCreateDepartmentCall wrap *gomock.Call
type MockServiceCreateDepartmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateDepartmentCall) Return(arg0 int64, arg1 error) *MockServiceCreateDepartmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateDepartmentCall) Do(f func(context.Context, domain.Department) (int64, error)) *MockServiceCreateDepartmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateDepartmentCall) DoAndReturn(f func(context.Context, domain.Department) (int64, error)) *MockServiceCreateDepartmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteDepartment mocks base method.
func (m *MockService) DeleteDepartment(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockServiceMockRecorder) DeleteDepartment(ctx, id any) *MockServiceDeleteDepartmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockService)(nil).DeleteDepartment), ctx, id)
	return &MockServiceDeleteDepartmentCall{Call: call}
}

// MockServiceDeleteDepartmentCall wrap *gomock.Call
type MockServiceDeleteDepartmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteDepartmentCall) Return(arg0 int64, arg1 error) *MockServiceDeleteDepartmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteDepartmentCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceDeleteDepartmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteDepartmentCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceDeleteDepartmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindById mocks base method.
func (m *MockService) FindById(ctx context.Context, id int64) (domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", ctx, id)
	ret0, _ := ret[0].(domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockServiceMockRecorder) FindById(ctx, id any) *MockServiceFindByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockService)(nil).FindById), ctx, id)
	return &MockServiceFindByIdCall{Call: call}
}

// MockServiceFindByIdCall wrap *gomock.Call
type MockServiceFindByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindByIdCall) Return(arg0 domain.Department, arg1 error) *MockServiceFindByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindByIdCall) Do(f func(context.Context, int64) (domain.Department, error)) *MockServiceFindByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindByIdCall) DoAndReturn(f func(context.Context, int64) (domain.Department, error)) *MockServiceFindByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDepartment mocks base method.
func (m *MockService) ListDepartment(ctx context.Context) ([]domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepartment", ctx)
	ret0, _ := ret[0].([]domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDepartment indicates an expected call of ListDepartment.
func (mr *MockServiceMockRecorder) ListDepartment(ctx any) *MockServiceListDepartmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepartment", reflect.TypeOf((*MockService)(nil).ListDepartment), ctx)
	return &MockServiceListDepartmentCall{Call: call}
}

// MockServiceListDepartmentCall wrap *gomock.Call
type MockServiceListDepartmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListDepartmentCall) Return(arg0 []domain.Department, arg1 error) *MockServiceListDepartmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListDepartmentCall) Do(f func(context.Context) ([]domain.Department, error)) *MockServiceListDepartmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListDepartmentCall) DoAndReturn(f func(context.Context) ([]domain.Department, error)) *MockServiceListDepartmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDepartmentByIds mocks base method.
func (m *MockService) ListDepartmentByIds(ctx context.Context, ids []int64) ([]domain.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDepartmentByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDepartmentByIds indicates an expected call of ListDepartmentByIds.
func (mr *MockServiceMockRecorder) ListDepartmentByIds(ctx, ids any) *MockServiceListDepartmentByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDepartmentByIds", reflect.TypeOf((*MockService)(nil).ListDepartmentByIds), ctx, ids)
	return &MockServiceListDepartmentByIdsCall{Call: call}
}

// MockServiceListDepartmentByIdsCall wrap *gomock.Call
type MockServiceListDepartmentByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListDepartmentByIdsCall) Return(arg0 []domain.Department, arg1 error) *MockServiceListDepartmentByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListDepartmentByIdsCall) Do(f func(context.Context, []int64) ([]domain.Department, error)) *MockServiceListDepartmentByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListDepartmentByIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Department, error)) *MockServiceListDepartmentByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDepartment mocks base method.
func (m *MockService) UpdateDepartment(ctx context.Context, req domain.Department) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockServiceMockRecorder) UpdateDepartment(ctx, req any) *MockServiceUpdateDepartmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockService)(nil).UpdateDepartment), ctx, req)
	return &MockServiceUpdateDepartmentCall{Call: call}
}

// MockServiceUpdateDepartmentCall wrap *gomock.Call
type MockServiceUpdateDepartmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateDepartmentCall) Return(arg0 int64, arg1 error) *MockServiceUpdateDepartmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateDepartmentCall) Do(f func(context.Context, domain.Department) (int64, error)) *MockServiceUpdateDepartmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateDepartmentCall) DoAndReturn(f func(context.Context, domain.Department) (int64, error)) *MockServiceUpdateDepartmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
