// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package codebook

import (
	"github.com/Duke1616/ecmdb/internal/codebook/internal/repostory"
	"github.com/Duke1616/ecmdb/internal/codebook/internal/repostory/dao"
	"github.com/Duke1616/ecmdb/internal/codebook/internal/service"
	"github.com/Duke1616/ecmdb/internal/codebook/internal/web"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/xen0n/go-workwx"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, db *mongox.Mongo, workAPP *workwx.WorkwxApp) (*Module, error) {
	codebookDAO := dao.NewCodebookDAO(db)
	codebookRepository := repository.NewCodebookRepository(codebookDAO)
	serviceService := service.NewService(codebookRepository)
	handler := web.NewHandler(serviceService)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewCodebookRepository, dao.NewCodebookDAO)
