// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package exchange

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/exchange/internal/service"
	"github.com/Duke1616/ecmdb/internal/exchange/internal/web"
	"github.com/Duke1616/ecmdb/internal/model"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/Duke1616/ecmdb/pkg/storage"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(attributeModule *attribute.Module, resourceModule *resource.Module, storage2 *storage.S3Storage, modelModule *model.Module) (*Module, error) {
	serviceService := attributeModule.Svc
	service2 := resourceModule.Svc
	service3 := modelModule.Svc
	iExchangeService := service.NewExchangeService(serviceService, service2, service3)
	handler := web.NewHandler(iExchangeService, storage2)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

// ProviderSet 数据交换模块依赖集合
var ProviderSet = wire.NewSet(web.NewHandler, service.NewExchangeService)
