// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/bootstrap/internal/service"
	"github.com/Duke1616/ecmdb/internal/model"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(modelModule *model.Module, attributeModule *attribute.Module, relationModule *relation.Module) (*Module, error) {
	v := modelModule.Svc
	v2 := modelModule.MGSvc
	v3 := attributeModule.Svc
	v4 := relationModule.RTSvc
	v5 := relationModule.RMSvc
	v6 := service.NewLoader(v, v2, v3, v4, v5)
	module := &Module{
		Svc: v6,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewLoader)
