// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/bootstrap/internal/service"
	"github.com/Duke1616/ecmdb/internal/model"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(modelModule *model.Module, attributeModule *attribute.Module, relationModule *relation.Module) (*Module, error) {
	serviceService := modelModule.Svc
	mgService := modelModule.MGSvc
	service2 := attributeModule.Svc
	relationTypeService := relationModule.RTSvc
	relationModelService := relationModule.RMSvc
	loader := service.NewLoader(serviceService, mgService, service2, relationTypeService, relationModelService)
	module := &Module{
		Svc: loader,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewLoader)
