// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

import (
	"github.com/Duke1616/ecmdb/internal/model/internal/repository"
	"github.com/Duke1616/ecmdb/internal/model/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/model/internal/service"
	"github.com/Duke1616/ecmdb/internal/model/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitHandler(db *mongo.Client) *web.Handler {
	modelDAO := dao.NewModelDAO(db)
	modelRepository := repository.NewModelRepository(modelDAO)
	serviceService := service.NewService(modelRepository)
	handler := web.NewHandler(serviceService)
	return handler
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewModelRepository, dao.NewModelDAO)

type Handler = web.Handler
