// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/model/internal/repository"
	"github.com/Duke1616/ecmdb/internal/model/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/model/internal/service"
	"github.com/Duke1616/ecmdb/internal/model/internal/web"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, rmModule *relation.Module, attrModule *attribute.Module, resourceSvc *resource.Module) (*Module, error) {
	modelDAO := dao.NewModelDAO(db)
	modelRepository := repository.NewModelRepository(modelDAO)
	serviceService := service.NewModelService(modelRepository)
	modelGroupDAO := dao.NewModelGroupDAO(db)
	mgRepository := repository.NewMGRepository(modelGroupDAO)
	mgService := service.NewMGService(mgRepository)
	relationModelService := rmModule.RMSvc
	service2 := attrModule.Svc
	encryptedSvc := resourceSvc.EncryptedSvc
	handler := web.NewHandler(serviceService, mgService, relationModelService, service2, encryptedSvc)
	module := &Module{
		Svc: serviceService,
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, initMGProvider,
	initModelProvider)

var initMGProvider = wire.NewSet(service.NewMGService, repository.NewMGRepository, dao.NewModelGroupDAO)

var initModelProvider = wire.NewSet(service.NewModelService, repository.NewModelRepository, dao.NewModelDAO)
