// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role

import (
	"github.com/Duke1616/ecmdb/internal/menu"
	"github.com/Duke1616/ecmdb/internal/policy"
	"github.com/Duke1616/ecmdb/internal/role/internal/repository"
	"github.com/Duke1616/ecmdb/internal/role/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/role/internal/service"
	"github.com/Duke1616/ecmdb/internal/role/internal/web"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, menuModule *menu.Module, policyModule *policy.Module) (*Module, error) {
	roleDAO := dao.NewRoleDAO(db)
	roleRepository := repository.NewRoleRepository(roleDAO)
	serviceService := service.NewService(roleRepository)
	service2 := menuModule.Svc
	service3 := policyModule.Svc
	handler := web.NewHandler(serviceService, service2, service3)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewRoleRepository, dao.NewRoleDAO)
