log:
  debug: true

web:
  host: "0.0.0.0"
  port: 9000

grpc:
  server:
    eiam:
      name: "eiam"
      listen_addr: "0.0.0.0:8077"
      auth_token: "1234567890"

mysql:
  dsn: "eiam:123456@tcp(ecmdb-mysql:3306)/eiam?charset=utf8mb4&parseTime=True&loc=Local"

# 会话与 Cookie 配置
session:
  session_encrypted_key: "1234567890Key"
  cookie:
    domain: ".example.com"
    name: "ecmdb-token-key"

# 缓存配置 (Redis)
redis:
  addr: "ecmdb-redis:6379"
  password: "1234567890"
  db: 1

# 消息队列配置 (Kafka)
kafka:
  network: tcp
  addresses:
    - ecmdb-kafka:9092

# 注册中心配置 (Etcd)
etcd:
  endpoints:
    - ecmdb-etcd:2379

# 密码加密
identity:
  encryption_key: 1234567890

casbin:
  redis:
    addr: "ecmdb-redis:6379"
    password: "1234567890"
    db: 2

migration:
  source:
    mongo:
      dsn: "mongodb://ecmdb:123456@ecmdb-mongo:27017/ecmdb"
      database: "ecmdb"
    mysql:
      dsn: "eiam:123456@tcp(ecmdb-mysql:3306)/eiam?charset=utf8mb4&parseTime=True&loc=Local"
  identity:
    version: "V1"
    key: "1234567890"
  batch_size: 100
  timeout: "10m"
  auto_migrate: true
  reset_auto_increment: true
  truncate: false
  dry_run: false
