# ecmdb 全量配置文件

# 日志配置
log:
  debug: true # 是否开启调试模式，开启后会打印更多详细日志

# web 配置: 对外暴露 http 接口
web:
  host: "0.0.0.0"
  port: 8000

# 数据加密配置：针对敏感字段进行 AES 加密存储
encryption:
  version: "V1" # 加密算法版本
  key: "1234567890"

# 策略鉴权：IAM服务地址，用于登录验证与权限鉴权
policy:
  auth_url: http://eiam:8000
  discovery_url: http://eiam:8000

# Redis 缓存配置
redis:
  addr: "redis:6379"
  password: "1234567890"
  db: 0

# MongoDB：持久化存储配置
mongodb:
  dsn: "mongodb://mongo:27017/ecmdb?authSource=admin"
  db: "ecmdb"
  username: "ecmdb"
  password: "123456"

# Kafka：用于自动化任务与异步事件通知的消息总线
kafka:
  network: "tcp"
  addresses:
    - "kafka:9092"

# Etcd：服务注册中心与配置分发
etcd:
  endpoints:
    - "etcd:2379"

# Minio：对象存储，用于附件、导出文件等非结构化数据
minio:
  endpoint: "minio:9000"
  access_key_id: "minio"
  secret_access_key: "minio123"
  use_ssl: false
