set -e
mysql -uroot -p$MYSQL_ROOT_PASSWORD <<EOF
create database $MYSQL_EALERT_DATABASE;
CREATE USER "$MYSQL_EALERT_USERNAME"@'%' IDENTIFIED BY "$MYSQL_EALERT_PASSWORD";
GRANT ALL PRIVILEGES ON $MYSQL_EALERT_DATABASE.* TO "$MYSQL_EALERT_USERNAME"@'%';
flush privileges;
EOF