# 数据加密，根据模块划分
encryption:
  user:
    version: "V1"
    key: "1234567890"
  resource:
    version: "V1"
    key: "1234567890"
  runner:
    version: "V1"
    key: "1234567890"

ldap:
  url: "ldap://127.0.0.1:389"
  base_dn: "DC=example,DC=com"
  bind_dn: "CN=cn,OU=ou,DC=example,DC=com"
  bind_password: "1234567890"
  username_attribute: "sAMAccountName"
  mail_attribute: "mail"
  display_name_attribute: "displayName"
  title_attribute: "title"
  group_name_attribute: "cn"
  user_filter: "(&(sAMAccountName={input})(!(UserAccountControl=514)))"
  group_filter: "(|(member={dn}))"

session:
  session_encrypted_key: "1234567890Key"
  cookie:
    domain: ".example.com"
    name: "ecmdb-token-key"

redis:
  addr: "ecmdb-redis:6379"
  password: "1234567890"
  db: 0

casbin:
  redis:
    addr: "ecmdb-redis:6379"
    db: 1
    password: "1234567890"

mongodb:
  dsn: mongodb://mongo:27017/ecmdb?authSource=admin
  db: ecmdb
  username: ecmdb
  password: 123456

mysql:
  dsn: ecmdb:123456@tcp(ecmdb-mysql:3306)/ecmdb?charset=utf8mb4&parseTime=True&loc=Local&timeout=5s

kafka:
  network: tcp
  addresses:
    - ecmdb-kafka:9092

etcd:
  endpoints:
    - ecmdb-etcd:2379

minio:
  endpoint: minio:9000
  accessKeyID: minio
  secretAccessKey: minio123
  useSSL: false

# 用于查询企业微信API
wechat:
  corpId: ""
  corpSecret: ""
  agentId: 1000002

# 用于飞书发送消息通知
feishu:
  appId: ""
  appSecret: ""

frontend:
  logicflow_url: http://localhost:3333/logicflow-preview

cronjob:
  enabled: false

grpc:
  server:
    name: "ecmdb"
    port: 8097
    etcd_ttl: 60
    key: "1234567890"