crypto_aes_key: "1234567890"

ldap:
  url: "ldap://127.0.0.1:389"
  base_dn: "DC=example,DC=com"
  bind_dn: "CN=cn,OU=ou,DC=example,DC=com"
  bind_password: "1234567890"
  username_attribute: "sAMAccountName"
  mail_attribute: "mail"
  display_name_attribute: "displayName"
  title_attribute: "title"
  group_name_attribute: "cn"
  user_filter: "(&(sAMAccountName={input})(!(UserAccountControl=514)))"
  group_filter: "(|(member={dn}))"

session:
  session_encrypted_key: "1234567890"

redis:
  addr: "ecmdb-redis:6379"
  password: "1234567890"
  db: 0

casbin:
  redis:
    addr: "ecmdb-redis:6379"
    db: 1
    password: "1234567890"

mongodb:
  dsn: mongodb://ecmdb-mongo:27017/cmdb
  db: cmdb
  username: cmdb
  password: 123456

mysql:
  dsn: cmdb:123456@tcp(ecmdb-mysql:3306)/cmdb?charset=utf8mb4&parseTime=True&loc=Local&timeout=5s

kafka:
  network: tcp
  addresses:
    - ecmdb-kafka:9092

etcd:
  endpoints:
    - ecmdb-etcd:2379

minio:
  endpoint: minio:9000
  accessKeyID: minio
  secretAccessKey: minio123
  useSSL: false

wechat:
  corpId: ""
  corpSecret: ""
  agentId: 1000002

cronjob:
  enabled: true
