set -e
mysql -h"${MYSQL_HOST:-localhost}" -uroot -p$MYSQL_ROOT_PASSWORD <<EOF
CREATE DATABASE IF NOT EXISTS $MYSQL_EALERT_DATABASE;
CREATE USER IF NOT EXISTS "$MYSQL_EALERT_USERNAME"@'%' IDENTIFIED BY "$MYSQL_EALERT_PASSWORD";
GRANT ALL PRIVILEGES ON $MYSQL_EALERT_DATABASE.* TO "$MYSQL_EALERT_USERNAME"@'%';

CREATE DATABASE IF NOT EXISTS $MYSQL_ETASK_DATABASE;
CREATE USER IF NOT EXISTS "$MYSQL_ETASK_USERNAME"@'%' IDENTIFIED BY "$MYSQL_ETASK_PASSWORD";
GRANT ALL PRIVILEGES ON $MYSQL_ETASK_DATABASE.* TO "$MYSQL_ETASK_USERNAME"@'%';

CREATE DATABASE IF NOT EXISTS $MYSQL_EIAM_DATABASE;
CREATE USER IF NOT EXISTS "$MYSQL_EIAM_USERNAME"@'%' IDENTIFIED BY "$MYSQL_EIAM_PASSWORD";
GRANT ALL PRIVILEGES ON $MYSQL_EIAM_DATABASE.* TO "$MYSQL_EIAM_USERNAME"@'%';

CREATE DATABASE IF NOT EXISTS $MYSQL_EFLOW_DATABASE;
CREATE USER IF NOT EXISTS "$MYSQL_EFLOW_USERNAME"@'%' IDENTIFIED BY "$MYSQL_EFLOW_PASSWORD";
GRANT ALL PRIVILEGES ON $MYSQL_EFLOW_DATABASE.* TO "$MYSQL_EFLOW_USERNAME"@'%';
FLUSH PRIVILEGES;
EOF