// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package engine

import (
	engine2 "github.com/Bunny3th/easy-workflow/workflow/engine"
	"github.com/Duke1616/ecmdb/internal/engine/internal/event/engine"
	"github.com/Duke1616/ecmdb/internal/engine/internal/event/producer"
	"github.com/Duke1616/ecmdb/internal/engine/internal/repository"
	"github.com/Duke1616/ecmdb/internal/engine/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/engine/internal/service"
	"github.com/Duke1616/ecmdb/internal/engine/internal/web"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"gorm.io/gorm"
	"log"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, q mq.MQ) (*Module, error) {
	processEngineDAO := dao.NewProcessEngineDAO(db)
	processEngineRepository := repository.NewProcessEngineRepository(processEngineDAO)
	serviceService := service.NewService(processEngineRepository)
	handler := web.NewHandler(serviceService)
	orderStatusModifyEventProducer, err := producer.NewOrderStatusModifyEventProducer(q)
	if err != nil {
		return nil, err
	}
	processEvent := InitWorkflowEngineOnce(db, orderStatusModifyEventProducer, serviceService)
	module := &Module{
		Svc:   serviceService,
		Hdl:   handler,
		event: processEvent,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewProcessEngineRepository, dao.NewProcessEngineDAO)

var engineOnce = sync.Once{}

func InitWorkflowEngineOnce(db *gorm.DB, producer2 producer.OrderStatusModifyEventProducer, svc service.Service) *engine.ProcessEvent {
	event := engine.NewProcessEvent(producer2, svc)

	engineOnce.Do(func() {
		engine2.DB = db
		if err := engine2.DatabaseInitialize(); err != nil {
			log.Fatalln("easy workflow 初始化数据表失败，错误:", err)
		}
		engine2.IgnoreEventError = false
		engine2.RegisterEvents(event)
	})

	return event
}
