// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/ecmdb/cmd/initial/version"
	"github.com/Duke1616/ecmdb/internal/repository"
	"github.com/Duke1616/ecmdb/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/service/attribute"
	service5 "github.com/Duke1616/ecmdb/internal/service/bootstrap"
	service4 "github.com/Duke1616/ecmdb/internal/service/model"
	service3 "github.com/Duke1616/ecmdb/internal/service/relation"
	service2 "github.com/Duke1616/ecmdb/internal/service/resource"
	"github.com/Duke1616/ecmdb/ioc"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	mongo := ioc.InitMongoDB()
	versionDao := version.NewDao(mongo)
	versionService := version.NewService(versionDao)
	db := ioc.InitMongoDBV2(mongo)
	modelDAO := dao.NewModelDAO(db)
	modelRepository := repository.NewModelRepository(modelDAO)
	resourceDAO := dao.NewResourceDAO(db)
	resourceRepository := repository.NewResourceRepository(resourceDAO)
	attributeDAO := dao.NewAttributeDAO(db)
	attributeRepository := repository.NewAttributeRepository(attributeDAO)
	attributeGroupDAO := dao.NewAttributeGroupDAO(db)
	attributeGroupRepository := repository.NewAttributeGroupRepository(attributeGroupDAO)
	mq := ioc.InitMQ()
	fieldSecureAttrChangeEventProducer, err := ioc.InitFieldSecureAttrChangeEventProducer(mq)
	if err != nil {
		return nil, err
	}
	iFieldDeleteEventProducer, err := ioc.InitFieldDeleteEventProducer(mq)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(attributeRepository, attributeGroupRepository, fieldSecureAttrChangeEventProducer, iFieldDeleteEventProducer)
	crypto := ioc.InitCrypto()
	service6 := service2.NewService(resourceRepository, serviceService, crypto)
	relationModelDAO := dao.NewRelationModelDAO(db)
	relationModelRepository := repository.NewRelationModelRepository(relationModelDAO)
	relationResourceDAO := dao.NewRelationResourceDAO(db)
	relationResourceRepository := repository.NewRelationResourceRepository(relationResourceDAO)
	relationModelService := service3.NewRelationModelService(relationModelRepository, relationResourceRepository)
	v := ioc.InitDeleteModelDependencyCheckers(service6, relationModelService)
	service7 := service4.NewModelService(modelRepository, v, serviceService)
	modelGroupDAO := dao.NewModelGroupDAO(db)
	mgRepository := repository.NewModelGroupRepository(modelGroupDAO)
	mgService := service4.NewMGService(mgRepository, modelRepository)
	relationTypeDAO := dao.NewRelationTypeDAO(db)
	relationTypeRepository := repository.NewRelationTypeRepository(relationTypeDAO)
	relationTypeService := service3.NewRelationTypeService(relationTypeRepository, relationModelRepository, relationResourceRepository)
	loader := service5.NewLoader(service7, mgService, serviceService, relationTypeService, relationModelService)
	app := &App{
		VerSvc:       versionService,
		BootstrapSvc: loader,
		DB:           mongo,
	}
	return app, nil
}

// wire.go:

var BaseSet = wire.NewSet(ioc.InitMongoDB, ioc.InitMongoDBV2, ioc.InitRedis, ioc.InitMQ, ioc.InitEtcdClient, ioc.InitCrypto)
