log:
  debug: true

web:
  host: "0.0.0.0"
  port: 8000

policy:
  auth_url: http://127.0.0.1:9000
  discovery_url: http://127.0.0.1:9000

encryption:
  version: "V1"
  key: "1234567890"

redis:
  addr: "127.0.0.1:6379"
  password: "1234567890"
  db: 0

mongodb:
  dsn: mongodb://127.0.0.1:27017/ecmdb
  db: ecmdb
  username: ecmdb
  password: "123456"

kafka:
  network: tcp
  addresses:
    - 127.0.0.1:9092

etcd:
  endpoints:
    - 127.0.0.1:2379

minio:
  endpoint: 127.0.0.1:9000
  access_key_id: minio
  secret_access_key: minio123
  use_ssl: false
