// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package order

import (
	"context"
	"github.com/Duke1616/ecmdb/internal/engine"
	"github.com/Duke1616/ecmdb/internal/order/internal/event"
	"github.com/Duke1616/ecmdb/internal/order/internal/event/consumer"
	"github.com/Duke1616/ecmdb/internal/order/internal/grpc"
	"github.com/Duke1616/ecmdb/internal/order/internal/repository"
	"github.com/Duke1616/ecmdb/internal/order/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/order/internal/service"
	"github.com/Duke1616/ecmdb/internal/order/internal/web"
	"github.com/Duke1616/ecmdb/internal/pkg/notification/sender"
	"github.com/Duke1616/ecmdb/internal/template"
	"github.com/Duke1616/ecmdb/internal/user"
	"github.com/Duke1616/ecmdb/internal/workflow"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/larksuite/oapi-sdk-go/v3"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, db *mongox.Mongo, workflowModule *workflow.Module, engineModule *engine.Module, templateModule *template.Module, userModule *user.Module, lark2 *lark.Client, sender2 sender.NotificationSender) (*Module, error) {
	orderDAO := dao.NewOrderDAO(db)
	taskFormDAO := dao.NewTaskFormDAO(db)
	orderRepository := repository.NewOrderRepository(orderDAO, taskFormDAO)
	serviceService := templateModule.Svc
	createProcessEventProducer, err := event.NewCreateProcessEventProducer(q)
	if err != nil {
		return nil, err
	}
	service2 := service.NewService(orderRepository, serviceService, createProcessEventProducer)
	service3 := engineModule.Svc
	service4 := workflowModule.Svc
	processEngine := service.NewProcessEngine(service2, service3, service4)
	service5 := userModule.Svc
	handler := web.NewHandler(service2, service3, processEngine, service5, service4)
	workOrderServer := grpc.NewWorkOrderServer(service2, serviceService)
	wechatOrderConsumer := initWechatConsumer(service2, serviceService, service5, q)
	processEventConsumer := InitProcessConsumer(q, service4, service2)
	orderStatusModifyEventConsumer := InitModifyStatusConsumer(q, service2)
	larkCallbackEventConsumer := InitLardCallbackConsumer(q, service3, lark2, service5, serviceService, service2, processEngine, service4, sender2)
	module := &Module{
		Hdl:       handler,
		RpcServer: workOrderServer,
		Svc:       service2,
		EngineSvc: processEngine,
		cw:        wechatOrderConsumer,
		cs:        processEventConsumer,
		cms:       orderStatusModifyEventConsumer,
		cf:        larkCallbackEventConsumer,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, service.NewProcessEngine, repository.NewOrderRepository, dao.NewTaskFormDAO, dao.NewOrderDAO, grpc.NewWorkOrderServer)

func initWechatConsumer(svc service.Service, templateSvc template.Service, userSvc user.Service, q mq.MQ) *consumer.WechatOrderConsumer {
	c, err := consumer.NewWechatOrderConsumer(svc, templateSvc, userSvc, q)
	if err != nil {
		panic(err)
	}

	c.Start(context.Background())
	return c
}

func InitProcessConsumer(q mq.MQ, workflowSvc workflow.Service, svc service.Service) *consumer.ProcessEventConsumer {
	c, err := consumer.NewProcessEventConsumer(q, workflowSvc, svc)
	if err != nil {
		return nil
	}

	c.Start(context.Background())
	return c
}

func InitModifyStatusConsumer(q mq.MQ, svc service.Service) *consumer.OrderStatusModifyEventConsumer {
	c, err := consumer.NewOrderStatusModifyEventConsumer(q, svc)
	if err != nil {
		return nil
	}

	c.Start(context.Background())
	return c
}

func InitLardCallbackConsumer(q mq.MQ, engineSvc engine.Service, lark2 *lark.Client, userSvc user.Service,
	templateSvc template.Service, svc service.Service, engineProcessSvc service.ProcessEngine,
	workflowSvc workflow.Service, sender2 sender.NotificationSender) *consumer.LarkCallbackEventConsumer {
	c, err := consumer.NewLarkCallbackEventConsumer(q, engineSvc, engineProcessSvc, svc, templateSvc, sender2, userSvc, workflowSvc, lark2)
	if err != nil {
		return nil
	}

	c.Start(context.Background())
	return c
}
