// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/api/proto/gen/ealert/notification/v1"
	"github.com/Duke1616/ecmdb/api/proto/gen/ealert/team"
	"github.com/Duke1616/ecmdb/internal/department"
	"github.com/Duke1616/ecmdb/internal/engine"
	"github.com/Duke1616/ecmdb/internal/event"
	"github.com/Duke1616/ecmdb/internal/event/producer"
	"github.com/Duke1616/ecmdb/internal/event/service/assignees"
	"github.com/Duke1616/ecmdb/internal/event/service/easyflow"
	"github.com/Duke1616/ecmdb/internal/event/service/strategy"
	"github.com/Duke1616/ecmdb/internal/event/service/strategy/automation"
	"github.com/Duke1616/ecmdb/internal/event/service/strategy/carbon_copy"
	"github.com/Duke1616/ecmdb/internal/event/service/strategy/chat"
	"github.com/Duke1616/ecmdb/internal/event/service/strategy/start"
	user2 "github.com/Duke1616/ecmdb/internal/event/service/strategy/user"
	"github.com/Duke1616/ecmdb/internal/order"
	"github.com/Duke1616/ecmdb/internal/pkg/notification/sender"
	"github.com/Duke1616/ecmdb/internal/rota"
	"github.com/Duke1616/ecmdb/internal/task"
	"github.com/Duke1616/ecmdb/internal/template"
	"github.com/Duke1616/ecmdb/internal/test/ioc"
	"github.com/Duke1616/ecmdb/internal/user"
	"github.com/Duke1616/ecmdb/internal/workflow"
	"github.com/larksuite/oapi-sdk-go/v3"
)

// Injectors from wire.go:

func InitApp(sender2 sender.NotificationSender, teamSvc teamv1.TeamServiceClient, notificationSvc notificationv1.NotificationServiceClient, userModule *user.Module, orderModule *order.Module, taskModule *task.Module, templateModule *template.Module, engineModule *engine.Module, workflowModule *workflow.Module, departmentModule *department.Module, rotaModule *rota.Module) (*TestApp, error) {
	db := ioc.InitMySQLDB()
	service := engineModule.Svc
	mq := ioc.InitMQ()
	orderStatusModifyEventProducer, err := producer.NewOrderStatusModifyEventProducer(mq)
	if err != nil {
		return nil, err
	}
	serviceService := taskModule.Svc
	service2 := orderModule.Svc
	service3 := workflowModule.Svc
	service4 := userModule.Svc
	service5 := templateModule.Svc
	appointResolver := assignees.NewAppointResolver(service4)
	founderResolver := assignees.NewFounderResolver(service4)
	service6 := departmentModule.Svc
	leaderResolver := assignees.NewLeaderResolver(service4, service6)
	mainLeaderResolver := assignees.NewMainLeaderResolver(service4, service6)
	service7 := rotaModule.Svc
	onCallResolver := assignees.NewOnCallResolver(service7, service4)
	templateResolver := assignees.NewTemplateResolver(service4)
	teamResolver := assignees.NewTeamResolver(teamSvc, service4)
	resolveEngine := event.InitResolveEngine(appointResolver, founderResolver, leaderResolver, mainLeaderResolver, onCallResolver, templateResolver, teamResolver)
	strategyService := strategy.NewService(service4, service5, serviceService, service2, service, resolveEngine)
	notification := user2.NewNotification(strategyService, service6, sender2, notificationSvc)
	automationNotification := automation.NewNotification(strategyService, sender2)
	startNotification := start.NewNotification(strategyService, sender2)
	client := _wireClientValue
	chatNotification := chat.NewNotification(strategyService, sender2, client, teamSvc)
	carbon_copyNotification := carbon_copy.NewNotification(strategyService, sender2)
	dispatcher := event.ProviderNewDispatcher(notification, automationNotification, startNotification, chatNotification, carbon_copyNotification, strategyService)
	processEvent := event.InitWorkflowEngineOnce(db, service, orderStatusModifyEventProducer, serviceService, service2, service3, dispatcher)
	testApp := &TestApp{
		EventHandler:     processEvent,
		UserModule:       userModule,
		OrderModule:      orderModule,
		TaskModule:       taskModule,
		TemplateModule:   templateModule,
		EngineModule:     engineModule,
		WorkflowModule:   workflowModule,
		DepartmentModule: departmentModule,
		RotaModule:       rotaModule,
	}
	return testApp, nil
}

var (
	_wireClientValue = (*lark.Client)(nil)
)

// wire.go:

type TestApp struct {
	EventHandler     *easyflow.ProcessEvent
	UserModule       *user.Module
	OrderModule      *order.Module
	TaskModule       *task.Module
	TemplateModule   *template.Module
	EngineModule     *engine.Module
	WorkflowModule   *workflow.Module
	DepartmentModule *department.Module
	RotaModule       *rota.Module
}
