// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/internal/relation"
)

// Injectors from wire.go:

func InitRMHandler() (*relation.RMHandler, error) {
	db := InitMongoDB()
	module, err := relation.InitModule(db)
	if err != nil {
		return nil, err
	}
	v := module.RMHdl
	return v, nil
}

func InitRRHandler() (*relation.RRHandler, error) {
	db := InitMongoDB()
	module, err := relation.InitModule(db)
	if err != nil {
		return nil, err
	}
	v := module.RRHdl
	return v, nil
}

func InitRRSvc() relation.RRSvc {
	db := InitMongoDB()
	v := relation.InitRRService(db)
	return v
}

func InitRMSvc() relation.RMSvc {
	db := InitMongoDB()
	v := relation.InitRMService(db)
	return v
}
