// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/Duke1616/ecmdb/internal/relation/internal/service"
	"github.com/Duke1616/ecmdb/internal/relation/internal/web"
)

// Injectors from wire.go:

func InitRMHandler() (*web.RelationModelHandler, error) {
	db := InitMongoDB()
	module, err := relation.InitModule(db)
	if err != nil {
		return nil, err
	}
	relationModelHandler := module.RMHdl
	return relationModelHandler, nil
}

func InitRRHandler() (*web.RelationResourceHandler, error) {
	db := InitMongoDB()
	module, err := relation.InitModule(db)
	if err != nil {
		return nil, err
	}
	relationResourceHandler := module.RRHdl
	return relationResourceHandler, nil
}

func InitRRSvc() service.RelationResourceService {
	db := InitMongoDB()
	relationResourceService := relation.InitRRService(db)
	return relationResourceService
}

func InitRMSvc() service.RelationModelService {
	db := InitMongoDB()
	relationModelService := relation.InitRMService(db)
	return relationModelService
}
