// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=taskmocks -destination=../../mocks/task.mock.go -typed Service
//

// Package taskmocks is a generated GoMock package.
package taskmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/task/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AutoRetryTask mocks base method.
func (m *MockService) AutoRetryTask(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoRetryTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AutoRetryTask indicates an expected call of AutoRetryTask.
func (mr *MockServiceMockRecorder) AutoRetryTask(ctx, id any) *MockServiceAutoRetryTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoRetryTask", reflect.TypeOf((*MockService)(nil).AutoRetryTask), ctx, id)
	return &MockServiceAutoRetryTaskCall{Call: call}
}

// MockServiceAutoRetryTaskCall wrap *gomock.Call
type MockServiceAutoRetryTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAutoRetryTaskCall) Return(arg0 error) *MockServiceAutoRetryTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAutoRetryTaskCall) Do(f func(context.Context, int64) error) *MockServiceAutoRetryTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAutoRetryTaskCall) DoAndReturn(f func(context.Context, int64) error) *MockServiceAutoRetryTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTask mocks base method.
func (m *MockService) CreateTask(ctx context.Context, orderId int64, processInstId int, nodeId string) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, orderId, processInstId, nodeId)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockServiceMockRecorder) CreateTask(ctx, orderId, processInstId, nodeId any) *MockServiceCreateTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockService)(nil).CreateTask), ctx, orderId, processInstId, nodeId)
	return &MockServiceCreateTaskCall{Call: call}
}

// MockServiceCreateTaskCall wrap *gomock.Call
type MockServiceCreateTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateTaskCall) Return(arg0 domain.Task, arg1 error) *MockServiceCreateTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateTaskCall) Do(f func(context.Context, int64, int, string) (domain.Task, error)) *MockServiceCreateTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateTaskCall) DoAndReturn(f func(context.Context, int64, int, string) (domain.Task, error)) *MockServiceCreateTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Detail mocks base method.
func (m *MockService) Detail(ctx context.Context, id int64) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockServiceMockRecorder) Detail(ctx, id any) *MockServiceDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockService)(nil).Detail), ctx, id)
	return &MockServiceDetailCall{Call: call}
}

// MockServiceDetailCall wrap *gomock.Call
type MockServiceDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDetailCall) Return(arg0 domain.Task, arg1 error) *MockServiceDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDetailCall) Do(f func(context.Context, int64) (domain.Task, error)) *MockServiceDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDetailCall) DoAndReturn(f func(context.Context, int64) (domain.Task, error)) *MockServiceDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTaskResult mocks base method.
func (m *MockService) FindTaskResult(ctx context.Context, instanceId int, nodeId string) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskResult", ctx, instanceId, nodeId)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskResult indicates an expected call of FindTaskResult.
func (mr *MockServiceMockRecorder) FindTaskResult(ctx, instanceId, nodeId any) *MockServiceFindTaskResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskResult", reflect.TypeOf((*MockService)(nil).FindTaskResult), ctx, instanceId, nodeId)
	return &MockServiceFindTaskResultCall{Call: call}
}

// MockServiceFindTaskResultCall wrap *gomock.Call
type MockServiceFindTaskResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindTaskResultCall) Return(arg0 domain.Task, arg1 error) *MockServiceFindTaskResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindTaskResultCall) Do(f func(context.Context, int, string) (domain.Task, error)) *MockServiceFindTaskResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindTaskResultCall) DoAndReturn(f func(context.Context, int, string) (domain.Task, error)) *MockServiceFindTaskResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListReadyTasks mocks base method.
func (m *MockService) ListReadyTasks(ctx context.Context, limit int64) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadyTasks", ctx, limit)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReadyTasks indicates an expected call of ListReadyTasks.
func (mr *MockServiceMockRecorder) ListReadyTasks(ctx, limit any) *MockServiceListReadyTasksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadyTasks", reflect.TypeOf((*MockService)(nil).ListReadyTasks), ctx, limit)
	return &MockServiceListReadyTasksCall{Call: call}
}

// MockServiceListReadyTasksCall wrap *gomock.Call
type MockServiceListReadyTasksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListReadyTasksCall) Return(arg0 []domain.Task, arg1 error) *MockServiceListReadyTasksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListReadyTasksCall) Do(f func(context.Context, int64) ([]domain.Task, error)) *MockServiceListReadyTasksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListReadyTasksCall) DoAndReturn(f func(context.Context, int64) ([]domain.Task, error)) *MockServiceListReadyTasksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSuccessTasksByUtime mocks base method.
func (m *MockService) ListSuccessTasksByUtime(ctx context.Context, offset, limit, utime int64) ([]domain.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSuccessTasksByUtime", ctx, offset, limit, utime)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSuccessTasksByUtime indicates an expected call of ListSuccessTasksByUtime.
func (mr *MockServiceMockRecorder) ListSuccessTasksByUtime(ctx, offset, limit, utime any) *MockServiceListSuccessTasksByUtimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSuccessTasksByUtime", reflect.TypeOf((*MockService)(nil).ListSuccessTasksByUtime), ctx, offset, limit, utime)
	return &MockServiceListSuccessTasksByUtimeCall{Call: call}
}

// MockServiceListSuccessTasksByUtimeCall wrap *gomock.Call
type MockServiceListSuccessTasksByUtimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListSuccessTasksByUtimeCall) Return(arg0 []domain.Task, arg1 int64, arg2 error) *MockServiceListSuccessTasksByUtimeCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListSuccessTasksByUtimeCall) Do(f func(context.Context, int64, int64, int64) ([]domain.Task, int64, error)) *MockServiceListSuccessTasksByUtimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListSuccessTasksByUtimeCall) DoAndReturn(f func(context.Context, int64, int64, int64) ([]domain.Task, int64, error)) *MockServiceListSuccessTasksByUtimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTask mocks base method.
func (m *MockService) ListTask(ctx context.Context, offset, limit int64) ([]domain.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTask", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTask indicates an expected call of ListTask.
func (mr *MockServiceMockRecorder) ListTask(ctx, offset, limit any) *MockServiceListTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTask", reflect.TypeOf((*MockService)(nil).ListTask), ctx, offset, limit)
	return &MockServiceListTaskCall{Call: call}
}

// MockServiceListTaskCall wrap *gomock.Call
type MockServiceListTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListTaskCall) Return(arg0 []domain.Task, arg1 int64, arg2 error) *MockServiceListTaskCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListTaskCall) Do(f func(context.Context, int64, int64) ([]domain.Task, int64, error)) *MockServiceListTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListTaskCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Task, int64, error)) *MockServiceListTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTaskByInstanceId mocks base method.
func (m *MockService) ListTaskByInstanceId(ctx context.Context, offset, limit int64, instanceId int) ([]domain.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskByInstanceId", ctx, offset, limit, instanceId)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTaskByInstanceId indicates an expected call of ListTaskByInstanceId.
func (mr *MockServiceMockRecorder) ListTaskByInstanceId(ctx, offset, limit, instanceId any) *MockServiceListTaskByInstanceIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskByInstanceId", reflect.TypeOf((*MockService)(nil).ListTaskByInstanceId), ctx, offset, limit, instanceId)
	return &MockServiceListTaskByInstanceIdCall{Call: call}
}

// MockServiceListTaskByInstanceIdCall wrap *gomock.Call
type MockServiceListTaskByInstanceIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListTaskByInstanceIdCall) Return(arg0 []domain.Task, arg1 int64, arg2 error) *MockServiceListTaskByInstanceIdCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListTaskByInstanceIdCall) Do(f func(context.Context, int64, int64, int) ([]domain.Task, int64, error)) *MockServiceListTaskByInstanceIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListTaskByInstanceIdCall) DoAndReturn(f func(context.Context, int64, int64, int) ([]domain.Task, int64, error)) *MockServiceListTaskByInstanceIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTaskByStatus mocks base method.
func (m *MockService) ListTaskByStatus(ctx context.Context, offset, limit int64, status uint8) ([]domain.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskByStatus", ctx, offset, limit, status)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTaskByStatus indicates an expected call of ListTaskByStatus.
func (mr *MockServiceMockRecorder) ListTaskByStatus(ctx, offset, limit, status any) *MockServiceListTaskByStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskByStatus", reflect.TypeOf((*MockService)(nil).ListTaskByStatus), ctx, offset, limit, status)
	return &MockServiceListTaskByStatusCall{Call: call}
}

// MockServiceListTaskByStatusCall wrap *gomock.Call
type MockServiceListTaskByStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListTaskByStatusCall) Return(arg0 []domain.Task, arg1 int64, arg2 error) *MockServiceListTaskByStatusCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListTaskByStatusCall) Do(f func(context.Context, int64, int64, uint8) ([]domain.Task, int64, error)) *MockServiceListTaskByStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListTaskByStatusCall) DoAndReturn(f func(context.Context, int64, int64, uint8) ([]domain.Task, int64, error)) *MockServiceListTaskByStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTaskByStatusAndKind mocks base method.
func (m *MockService) ListTaskByStatusAndKind(ctx context.Context, offset, limit int64, status uint8, kind string) ([]domain.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskByStatusAndKind", ctx, offset, limit, status, kind)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTaskByStatusAndKind indicates an expected call of ListTaskByStatusAndKind.
func (mr *MockServiceMockRecorder) ListTaskByStatusAndKind(ctx, offset, limit, status, kind any) *MockServiceListTaskByStatusAndKindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskByStatusAndKind", reflect.TypeOf((*MockService)(nil).ListTaskByStatusAndKind), ctx, offset, limit, status, kind)
	return &MockServiceListTaskByStatusAndKindCall{Call: call}
}

// MockServiceListTaskByStatusAndKindCall wrap *gomock.Call
type MockServiceListTaskByStatusAndKindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListTaskByStatusAndKindCall) Return(arg0 []domain.Task, arg1 int64, arg2 error) *MockServiceListTaskByStatusAndKindCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListTaskByStatusAndKindCall) Do(f func(context.Context, int64, int64, uint8, string) ([]domain.Task, int64, error)) *MockServiceListTaskByStatusAndKindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListTaskByStatusAndKindCall) DoAndReturn(f func(context.Context, int64, int64, uint8, string) ([]domain.Task, int64, error)) *MockServiceListTaskByStatusAndKindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MarkTaskAsAutoPassed mocks base method.
func (m *MockService) MarkTaskAsAutoPassed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTaskAsAutoPassed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTaskAsAutoPassed indicates an expected call of MarkTaskAsAutoPassed.
func (mr *MockServiceMockRecorder) MarkTaskAsAutoPassed(ctx, id any) *MockServiceMarkTaskAsAutoPassedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTaskAsAutoPassed", reflect.TypeOf((*MockService)(nil).MarkTaskAsAutoPassed), ctx, id)
	return &MockServiceMarkTaskAsAutoPassedCall{Call: call}
}

// MockServiceMarkTaskAsAutoPassedCall wrap *gomock.Call
type MockServiceMarkTaskAsAutoPassedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceMarkTaskAsAutoPassedCall) Return(arg0 error) *MockServiceMarkTaskAsAutoPassedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceMarkTaskAsAutoPassedCall) Do(f func(context.Context, int64) error) *MockServiceMarkTaskAsAutoPassedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceMarkTaskAsAutoPassedCall) DoAndReturn(f func(context.Context, int64) error) *MockServiceMarkTaskAsAutoPassedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RetryTask mocks base method.
func (m *MockService) RetryTask(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryTask indicates an expected call of RetryTask.
func (mr *MockServiceMockRecorder) RetryTask(ctx, id any) *MockServiceRetryTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryTask", reflect.TypeOf((*MockService)(nil).RetryTask), ctx, id)
	return &MockServiceRetryTaskCall{Call: call}
}

// MockServiceRetryTaskCall wrap *gomock.Call
type MockServiceRetryTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceRetryTaskCall) Return(arg0 error) *MockServiceRetryTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceRetryTaskCall) Do(f func(context.Context, int64) error) *MockServiceRetryTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceRetryTaskCall) DoAndReturn(f func(context.Context, int64) error) *MockServiceRetryTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartTask mocks base method.
func (m *MockService) StartTask(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartTask indicates an expected call of StartTask.
func (mr *MockServiceMockRecorder) StartTask(ctx, id any) *MockServiceStartTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTask", reflect.TypeOf((*MockService)(nil).StartTask), ctx, id)
	return &MockServiceStartTaskCall{Call: call}
}

// MockServiceStartTaskCall wrap *gomock.Call
type MockServiceStartTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceStartTaskCall) Return(arg0 error) *MockServiceStartTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceStartTaskCall) Do(f func(context.Context, int64) error) *MockServiceStartTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceStartTaskCall) DoAndReturn(f func(context.Context, int64) error) *MockServiceStartTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateArgs mocks base method.
func (m *MockService) UpdateArgs(ctx context.Context, id int64, args map[string]any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArgs", ctx, id, args)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArgs indicates an expected call of UpdateArgs.
func (mr *MockServiceMockRecorder) UpdateArgs(ctx, id, args any) *MockServiceUpdateArgsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArgs", reflect.TypeOf((*MockService)(nil).UpdateArgs), ctx, id, args)
	return &MockServiceUpdateArgsCall{Call: call}
}

// MockServiceUpdateArgsCall wrap *gomock.Call
type MockServiceUpdateArgsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateArgsCall) Return(arg0 int64, arg1 error) *MockServiceUpdateArgsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateArgsCall) Do(f func(context.Context, int64, map[string]any) (int64, error)) *MockServiceUpdateArgsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateArgsCall) DoAndReturn(f func(context.Context, int64, map[string]any) (int64, error)) *MockServiceUpdateArgsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateExternalId mocks base method.
func (m *MockService) UpdateExternalId(ctx context.Context, id int64, externalId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExternalId", ctx, id, externalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExternalId indicates an expected call of UpdateExternalId.
func (mr *MockServiceMockRecorder) UpdateExternalId(ctx, id, externalId any) *MockServiceUpdateExternalIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExternalId", reflect.TypeOf((*MockService)(nil).UpdateExternalId), ctx, id, externalId)
	return &MockServiceUpdateExternalIdCall{Call: call}
}

// MockServiceUpdateExternalIdCall wrap *gomock.Call
type MockServiceUpdateExternalIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateExternalIdCall) Return(arg0 error) *MockServiceUpdateExternalIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateExternalIdCall) Do(f func(context.Context, int64, string) error) *MockServiceUpdateExternalIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateExternalIdCall) DoAndReturn(f func(context.Context, int64, string) error) *MockServiceUpdateExternalIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTaskResult mocks base method.
func (m *MockService) UpdateTaskResult(ctx context.Context, req domain.TaskResult) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskResult", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskResult indicates an expected call of UpdateTaskResult.
func (mr *MockServiceMockRecorder) UpdateTaskResult(ctx, req any) *MockServiceUpdateTaskResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskResult", reflect.TypeOf((*MockService)(nil).UpdateTaskResult), ctx, req)
	return &MockServiceUpdateTaskResultCall{Call: call}
}

// MockServiceUpdateTaskResultCall wrap *gomock.Call
type MockServiceUpdateTaskResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateTaskResultCall) Return(arg0 int64, arg1 error) *MockServiceUpdateTaskResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateTaskResultCall) Do(f func(context.Context, domain.TaskResult) (int64, error)) *MockServiceUpdateTaskResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateTaskResultCall) DoAndReturn(f func(context.Context, domain.TaskResult) (int64, error)) *MockServiceUpdateTaskResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTaskStatus mocks base method.
func (m *MockService) UpdateTaskStatus(ctx context.Context, req domain.TaskResult) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockServiceMockRecorder) UpdateTaskStatus(ctx, req any) *MockServiceUpdateTaskStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockService)(nil).UpdateTaskStatus), ctx, req)
	return &MockServiceUpdateTaskStatusCall{Call: call}
}

// MockServiceUpdateTaskStatusCall wrap *gomock.Call
type MockServiceUpdateTaskStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateTaskStatusCall) Return(arg0 int64, arg1 error) *MockServiceUpdateTaskStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateTaskStatusCall) Do(f func(context.Context, domain.TaskResult) (int64, error)) *MockServiceUpdateTaskStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateTaskStatusCall) DoAndReturn(f func(context.Context, domain.TaskResult) (int64, error)) *MockServiceUpdateTaskStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateVariables mocks base method.
func (m *MockService) UpdateVariables(ctx context.Context, id int64, variables []domain.Variables) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariables", ctx, id, variables)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVariables indicates an expected call of UpdateVariables.
func (mr *MockServiceMockRecorder) UpdateVariables(ctx, id, variables any) *MockServiceUpdateVariablesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariables", reflect.TypeOf((*MockService)(nil).UpdateVariables), ctx, id, variables)
	return &MockServiceUpdateVariablesCall{Call: call}
}

// MockServiceUpdateVariablesCall wrap *gomock.Call
type MockServiceUpdateVariablesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateVariablesCall) Return(arg0 int64, arg1 error) *MockServiceUpdateVariablesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateVariablesCall) Do(f func(context.Context, int64, []domain.Variables) (int64, error)) *MockServiceUpdateVariablesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateVariablesCall) DoAndReturn(f func(context.Context, int64, []domain.Variables) (int64, error)) *MockServiceUpdateVariablesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
