// Code generated by MockGen. DO NOT EDIT.
// Source: ./relation_model.go
//
// Generated by this command:
//
//	mockgen -source=./relation_model.go -destination=../../mocks/relation_model.mock.go -package=relationmocks -typed RelationModelService
//

// Package relationmocks is a generated GoMock package.
package relationmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/relation/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRelationModelService is a mock of RelationModelService interface.
type MockRelationModelService struct {
	ctrl     *gomock.Controller
	recorder *MockRelationModelServiceMockRecorder
	isgomock struct{}
}

// MockRelationModelServiceMockRecorder is the mock recorder for MockRelationModelService.
type MockRelationModelServiceMockRecorder struct {
	mock *MockRelationModelService
}

// NewMockRelationModelService creates a new mock instance.
func NewMockRelationModelService(ctrl *gomock.Controller) *MockRelationModelService {
	mock := &MockRelationModelService{ctrl: ctrl}
	mock.recorder = &MockRelationModelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationModelService) EXPECT() *MockRelationModelServiceMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockRelationModelService) BatchCreate(ctx context.Context, relations []domain.ModelRelation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, relations)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockRelationModelServiceMockRecorder) BatchCreate(ctx, relations any) *MockRelationModelServiceBatchCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockRelationModelService)(nil).BatchCreate), ctx, relations)
	return &MockRelationModelServiceBatchCreateCall{Call: call}
}

// MockRelationModelServiceBatchCreateCall wrap *gomock.Call
type MockRelationModelServiceBatchCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceBatchCreateCall) Return(arg0 error) *MockRelationModelServiceBatchCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceBatchCreateCall) Do(f func(context.Context, []domain.ModelRelation) error) *MockRelationModelServiceBatchCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceBatchCreateCall) DoAndReturn(f func(context.Context, []domain.ModelRelation) error) *MockRelationModelServiceBatchCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountByModelUid mocks base method.
func (m *MockRelationModelService) CountByModelUid(ctx context.Context, modelUid string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByModelUid", ctx, modelUid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByModelUid indicates an expected call of CountByModelUid.
func (mr *MockRelationModelServiceMockRecorder) CountByModelUid(ctx, modelUid any) *MockRelationModelServiceCountByModelUidCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByModelUid", reflect.TypeOf((*MockRelationModelService)(nil).CountByModelUid), ctx, modelUid)
	return &MockRelationModelServiceCountByModelUidCall{Call: call}
}

// MockRelationModelServiceCountByModelUidCall wrap *gomock.Call
type MockRelationModelServiceCountByModelUidCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceCountByModelUidCall) Return(arg0 int64, arg1 error) *MockRelationModelServiceCountByModelUidCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceCountByModelUidCall) Do(f func(context.Context, string) (int64, error)) *MockRelationModelServiceCountByModelUidCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceCountByModelUidCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockRelationModelServiceCountByModelUidCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountByRelationTypeUID mocks base method.
func (m *MockRelationModelService) CountByRelationTypeUID(ctx context.Context, uid string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByRelationTypeUID", ctx, uid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByRelationTypeUID indicates an expected call of CountByRelationTypeUID.
func (mr *MockRelationModelServiceMockRecorder) CountByRelationTypeUID(ctx, uid any) *MockRelationModelServiceCountByRelationTypeUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByRelationTypeUID", reflect.TypeOf((*MockRelationModelService)(nil).CountByRelationTypeUID), ctx, uid)
	return &MockRelationModelServiceCountByRelationTypeUIDCall{Call: call}
}

// MockRelationModelServiceCountByRelationTypeUIDCall wrap *gomock.Call
type MockRelationModelServiceCountByRelationTypeUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceCountByRelationTypeUIDCall) Return(arg0 int64, arg1 error) *MockRelationModelServiceCountByRelationTypeUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceCountByRelationTypeUIDCall) Do(f func(context.Context, string) (int64, error)) *MockRelationModelServiceCountByRelationTypeUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceCountByRelationTypeUIDCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockRelationModelServiceCountByRelationTypeUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateModelRelation mocks base method.
func (m *MockRelationModelService) CreateModelRelation(ctx context.Context, req domain.ModelRelation) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModelRelation", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModelRelation indicates an expected call of CreateModelRelation.
func (mr *MockRelationModelServiceMockRecorder) CreateModelRelation(ctx, req any) *MockRelationModelServiceCreateModelRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModelRelation", reflect.TypeOf((*MockRelationModelService)(nil).CreateModelRelation), ctx, req)
	return &MockRelationModelServiceCreateModelRelationCall{Call: call}
}

// MockRelationModelServiceCreateModelRelationCall wrap *gomock.Call
type MockRelationModelServiceCreateModelRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceCreateModelRelationCall) Return(arg0 int64, arg1 error) *MockRelationModelServiceCreateModelRelationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceCreateModelRelationCall) Do(f func(context.Context, domain.ModelRelation) (int64, error)) *MockRelationModelServiceCreateModelRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceCreateModelRelationCall) DoAndReturn(f func(context.Context, domain.ModelRelation) (int64, error)) *MockRelationModelServiceCreateModelRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteModelRelation mocks base method.
func (m *MockRelationModelService) DeleteModelRelation(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModelRelation", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteModelRelation indicates an expected call of DeleteModelRelation.
func (mr *MockRelationModelServiceMockRecorder) DeleteModelRelation(ctx, id any) *MockRelationModelServiceDeleteModelRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModelRelation", reflect.TypeOf((*MockRelationModelService)(nil).DeleteModelRelation), ctx, id)
	return &MockRelationModelServiceDeleteModelRelationCall{Call: call}
}

// MockRelationModelServiceDeleteModelRelationCall wrap *gomock.Call
type MockRelationModelServiceDeleteModelRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceDeleteModelRelationCall) Return(arg0 int64, arg1 error) *MockRelationModelServiceDeleteModelRelationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceDeleteModelRelationCall) Do(f func(context.Context, int64) (int64, error)) *MockRelationModelServiceDeleteModelRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceDeleteModelRelationCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockRelationModelServiceDeleteModelRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindModelDiagramBySrcUids mocks base method.
func (m *MockRelationModelService) FindModelDiagramBySrcUids(ctx context.Context, srcUids []string) ([]domain.ModelDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindModelDiagramBySrcUids", ctx, srcUids)
	ret0, _ := ret[0].([]domain.ModelDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindModelDiagramBySrcUids indicates an expected call of FindModelDiagramBySrcUids.
func (mr *MockRelationModelServiceMockRecorder) FindModelDiagramBySrcUids(ctx, srcUids any) *MockRelationModelServiceFindModelDiagramBySrcUidsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindModelDiagramBySrcUids", reflect.TypeOf((*MockRelationModelService)(nil).FindModelDiagramBySrcUids), ctx, srcUids)
	return &MockRelationModelServiceFindModelDiagramBySrcUidsCall{Call: call}
}

// MockRelationModelServiceFindModelDiagramBySrcUidsCall wrap *gomock.Call
type MockRelationModelServiceFindModelDiagramBySrcUidsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceFindModelDiagramBySrcUidsCall) Return(arg0 []domain.ModelDiagram, arg1 error) *MockRelationModelServiceFindModelDiagramBySrcUidsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceFindModelDiagramBySrcUidsCall) Do(f func(context.Context, []string) ([]domain.ModelDiagram, error)) *MockRelationModelServiceFindModelDiagramBySrcUidsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceFindModelDiagramBySrcUidsCall) DoAndReturn(f func(context.Context, []string) ([]domain.ModelDiagram, error)) *MockRelationModelServiceFindModelDiagramBySrcUidsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByRelationNames mocks base method.
func (m *MockRelationModelService) GetByRelationNames(ctx context.Context, names []string) ([]domain.ModelRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRelationNames", ctx, names)
	ret0, _ := ret[0].([]domain.ModelRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRelationNames indicates an expected call of GetByRelationNames.
func (mr *MockRelationModelServiceMockRecorder) GetByRelationNames(ctx, names any) *MockRelationModelServiceGetByRelationNamesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRelationNames", reflect.TypeOf((*MockRelationModelService)(nil).GetByRelationNames), ctx, names)
	return &MockRelationModelServiceGetByRelationNamesCall{Call: call}
}

// MockRelationModelServiceGetByRelationNamesCall wrap *gomock.Call
type MockRelationModelServiceGetByRelationNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceGetByRelationNamesCall) Return(arg0 []domain.ModelRelation, arg1 error) *MockRelationModelServiceGetByRelationNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceGetByRelationNamesCall) Do(f func(context.Context, []string) ([]domain.ModelRelation, error)) *MockRelationModelServiceGetByRelationNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceGetByRelationNamesCall) DoAndReturn(f func(context.Context, []string) ([]domain.ModelRelation, error)) *MockRelationModelServiceGetByRelationNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListModelUidRelation mocks base method.
func (m *MockRelationModelService) ListModelUidRelation(ctx context.Context, offset, limit int64, modelUid string) ([]domain.ModelRelation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModelUidRelation", ctx, offset, limit, modelUid)
	ret0, _ := ret[0].([]domain.ModelRelation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModelUidRelation indicates an expected call of ListModelUidRelation.
func (mr *MockRelationModelServiceMockRecorder) ListModelUidRelation(ctx, offset, limit, modelUid any) *MockRelationModelServiceListModelUidRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModelUidRelation", reflect.TypeOf((*MockRelationModelService)(nil).ListModelUidRelation), ctx, offset, limit, modelUid)
	return &MockRelationModelServiceListModelUidRelationCall{Call: call}
}

// MockRelationModelServiceListModelUidRelationCall wrap *gomock.Call
type MockRelationModelServiceListModelUidRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceListModelUidRelationCall) Return(arg0 []domain.ModelRelation, arg1 int64, arg2 error) *MockRelationModelServiceListModelUidRelationCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceListModelUidRelationCall) Do(f func(context.Context, int64, int64, string) ([]domain.ModelRelation, int64, error)) *MockRelationModelServiceListModelUidRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceListModelUidRelationCall) DoAndReturn(f func(context.Context, int64, int64, string) ([]domain.ModelRelation, int64, error)) *MockRelationModelServiceListModelUidRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateModelRelation mocks base method.
func (m *MockRelationModelService) UpdateModelRelation(ctx context.Context, req domain.ModelRelation) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModelRelation", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModelRelation indicates an expected call of UpdateModelRelation.
func (mr *MockRelationModelServiceMockRecorder) UpdateModelRelation(ctx, req any) *MockRelationModelServiceUpdateModelRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModelRelation", reflect.TypeOf((*MockRelationModelService)(nil).UpdateModelRelation), ctx, req)
	return &MockRelationModelServiceUpdateModelRelationCall{Call: call}
}

// MockRelationModelServiceUpdateModelRelationCall wrap *gomock.Call
type MockRelationModelServiceUpdateModelRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationModelServiceUpdateModelRelationCall) Return(arg0 int64, arg1 error) *MockRelationModelServiceUpdateModelRelationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationModelServiceUpdateModelRelationCall) Do(f func(context.Context, domain.ModelRelation) (int64, error)) *MockRelationModelServiceUpdateModelRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationModelServiceUpdateModelRelationCall) DoAndReturn(f func(context.Context, domain.ModelRelation) (int64, error)) *MockRelationModelServiceUpdateModelRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
