// Code generated by MockGen. DO NOT EDIT.
// Source: ./relation_resource.go
//
// Generated by this command:
//
//	mockgen -source=./relation_resource.go -destination=../../mocks/relation_resource.mock.go -package=relationmocks -typed RelationResourceService
//

// Package relationmocks is a generated GoMock package.
package relationmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/relation/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRelationResourceService is a mock of RelationResourceService interface.
type MockRelationResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockRelationResourceServiceMockRecorder
}

// MockRelationResourceServiceMockRecorder is the mock recorder for MockRelationResourceService.
type MockRelationResourceServiceMockRecorder struct {
	mock *MockRelationResourceService
}

// NewMockRelationResourceService creates a new mock instance.
func NewMockRelationResourceService(ctrl *gomock.Controller) *MockRelationResourceService {
	mock := &MockRelationResourceService{ctrl: ctrl}
	mock.recorder = &MockRelationResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelationResourceService) EXPECT() *MockRelationResourceServiceMockRecorder {
	return m.recorder
}

// CreateResourceRelation mocks base method.
func (m *MockRelationResourceService) CreateResourceRelation(ctx context.Context, req domain.ResourceRelation) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResourceRelation", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceRelation indicates an expected call of CreateResourceRelation.
func (mr *MockRelationResourceServiceMockRecorder) CreateResourceRelation(ctx, req any) *MockRelationResourceServiceCreateResourceRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceRelation", reflect.TypeOf((*MockRelationResourceService)(nil).CreateResourceRelation), ctx, req)
	return &MockRelationResourceServiceCreateResourceRelationCall{Call: call}
}

// MockRelationResourceServiceCreateResourceRelationCall wrap *gomock.Call
type MockRelationResourceServiceCreateResourceRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceCreateResourceRelationCall) Return(arg0 int64, arg1 error) *MockRelationResourceServiceCreateResourceRelationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceCreateResourceRelationCall) Do(f func(context.Context, domain.ResourceRelation) (int64, error)) *MockRelationResourceServiceCreateResourceRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceCreateResourceRelationCall) DoAndReturn(f func(context.Context, domain.ResourceRelation) (int64, error)) *MockRelationResourceServiceCreateResourceRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDiagram mocks base method.
func (m *MockRelationResourceService) ListDiagram(ctx context.Context, modelUid string, id int64) (domain.ResourceDiagram, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiagram", ctx, modelUid, id)
	ret0, _ := ret[0].(domain.ResourceDiagram)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDiagram indicates an expected call of ListDiagram.
func (mr *MockRelationResourceServiceMockRecorder) ListDiagram(ctx, modelUid, id any) *MockRelationResourceServiceListDiagramCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiagram", reflect.TypeOf((*MockRelationResourceService)(nil).ListDiagram), ctx, modelUid, id)
	return &MockRelationResourceServiceListDiagramCall{Call: call}
}

// MockRelationResourceServiceListDiagramCall wrap *gomock.Call
type MockRelationResourceServiceListDiagramCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListDiagramCall) Return(arg0 domain.ResourceDiagram, arg1 int64, arg2 error) *MockRelationResourceServiceListDiagramCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListDiagramCall) Do(f func(context.Context, string, int64) (domain.ResourceDiagram, int64, error)) *MockRelationResourceServiceListDiagramCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListDiagramCall) DoAndReturn(f func(context.Context, string, int64) (domain.ResourceDiagram, int64, error)) *MockRelationResourceServiceListDiagramCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDstAggregated mocks base method.
func (m *MockRelationResourceService) ListDstAggregated(ctx context.Context, modelUid string, id int64) ([]domain.ResourceAggregatedAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDstAggregated", ctx, modelUid, id)
	ret0, _ := ret[0].([]domain.ResourceAggregatedAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDstAggregated indicates an expected call of ListDstAggregated.
func (mr *MockRelationResourceServiceMockRecorder) ListDstAggregated(ctx, modelUid, id any) *MockRelationResourceServiceListDstAggregatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDstAggregated", reflect.TypeOf((*MockRelationResourceService)(nil).ListDstAggregated), ctx, modelUid, id)
	return &MockRelationResourceServiceListDstAggregatedCall{Call: call}
}

// MockRelationResourceServiceListDstAggregatedCall wrap *gomock.Call
type MockRelationResourceServiceListDstAggregatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListDstAggregatedCall) Return(arg0 []domain.ResourceAggregatedAssets, arg1 error) *MockRelationResourceServiceListDstAggregatedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListDstAggregatedCall) Do(f func(context.Context, string, int64) ([]domain.ResourceAggregatedAssets, error)) *MockRelationResourceServiceListDstAggregatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListDstAggregatedCall) DoAndReturn(f func(context.Context, string, int64) ([]domain.ResourceAggregatedAssets, error)) *MockRelationResourceServiceListDstAggregatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDstRelated mocks base method.
func (m *MockRelationResourceService) ListDstRelated(ctx context.Context, modelUid, relationName string, id int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDstRelated", ctx, modelUid, relationName, id)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDstRelated indicates an expected call of ListDstRelated.
func (mr *MockRelationResourceServiceMockRecorder) ListDstRelated(ctx, modelUid, relationName, id any) *MockRelationResourceServiceListDstRelatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDstRelated", reflect.TypeOf((*MockRelationResourceService)(nil).ListDstRelated), ctx, modelUid, relationName, id)
	return &MockRelationResourceServiceListDstRelatedCall{Call: call}
}

// MockRelationResourceServiceListDstRelatedCall wrap *gomock.Call
type MockRelationResourceServiceListDstRelatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListDstRelatedCall) Return(arg0 []int64, arg1 error) *MockRelationResourceServiceListDstRelatedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListDstRelatedCall) Do(f func(context.Context, string, string, int64) ([]int64, error)) *MockRelationResourceServiceListDstRelatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListDstRelatedCall) DoAndReturn(f func(context.Context, string, string, int64) ([]int64, error)) *MockRelationResourceServiceListDstRelatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDstResources mocks base method.
func (m *MockRelationResourceService) ListDstResources(ctx context.Context, modelUid string, id int64) ([]domain.ResourceRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDstResources", ctx, modelUid, id)
	ret0, _ := ret[0].([]domain.ResourceRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDstResources indicates an expected call of ListDstResources.
func (mr *MockRelationResourceServiceMockRecorder) ListDstResources(ctx, modelUid, id any) *MockRelationResourceServiceListDstResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDstResources", reflect.TypeOf((*MockRelationResourceService)(nil).ListDstResources), ctx, modelUid, id)
	return &MockRelationResourceServiceListDstResourcesCall{Call: call}
}

// MockRelationResourceServiceListDstResourcesCall wrap *gomock.Call
type MockRelationResourceServiceListDstResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListDstResourcesCall) Return(arg0 []domain.ResourceRelation, arg1 error) *MockRelationResourceServiceListDstResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListDstResourcesCall) Do(f func(context.Context, string, int64) ([]domain.ResourceRelation, error)) *MockRelationResourceServiceListDstResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListDstResourcesCall) DoAndReturn(f func(context.Context, string, int64) ([]domain.ResourceRelation, error)) *MockRelationResourceServiceListDstResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResourceIds mocks base method.
func (m *MockRelationResourceService) ListResourceIds(ctx context.Context, modelUid, relationType string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceIds", ctx, modelUid, relationType)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourceIds indicates an expected call of ListResourceIds.
func (mr *MockRelationResourceServiceMockRecorder) ListResourceIds(ctx, modelUid, relationType any) *MockRelationResourceServiceListResourceIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceIds", reflect.TypeOf((*MockRelationResourceService)(nil).ListResourceIds), ctx, modelUid, relationType)
	return &MockRelationResourceServiceListResourceIdsCall{Call: call}
}

// MockRelationResourceServiceListResourceIdsCall wrap *gomock.Call
type MockRelationResourceServiceListResourceIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListResourceIdsCall) Return(arg0 []int64, arg1 error) *MockRelationResourceServiceListResourceIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListResourceIdsCall) Do(f func(context.Context, string, string) ([]int64, error)) *MockRelationResourceServiceListResourceIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListResourceIdsCall) DoAndReturn(f func(context.Context, string, string) ([]int64, error)) *MockRelationResourceServiceListResourceIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResourceRelation mocks base method.
func (m *MockRelationResourceService) ListResourceRelation(ctx context.Context, offset, limit int64) ([]domain.ResourceRelation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceRelation", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.ResourceRelation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListResourceRelation indicates an expected call of ListResourceRelation.
func (mr *MockRelationResourceServiceMockRecorder) ListResourceRelation(ctx, offset, limit any) *MockRelationResourceServiceListResourceRelationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceRelation", reflect.TypeOf((*MockRelationResourceService)(nil).ListResourceRelation), ctx, offset, limit)
	return &MockRelationResourceServiceListResourceRelationCall{Call: call}
}

// MockRelationResourceServiceListResourceRelationCall wrap *gomock.Call
type MockRelationResourceServiceListResourceRelationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListResourceRelationCall) Return(arg0 []domain.ResourceRelation, arg1 int64, arg2 error) *MockRelationResourceServiceListResourceRelationCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListResourceRelationCall) Do(f func(context.Context, int64, int64) ([]domain.ResourceRelation, int64, error)) *MockRelationResourceServiceListResourceRelationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListResourceRelationCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.ResourceRelation, int64, error)) *MockRelationResourceServiceListResourceRelationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSrcAggregated mocks base method.
func (m *MockRelationResourceService) ListSrcAggregated(ctx context.Context, modelUid string, id int64) ([]domain.ResourceAggregatedAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSrcAggregated", ctx, modelUid, id)
	ret0, _ := ret[0].([]domain.ResourceAggregatedAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSrcAggregated indicates an expected call of ListSrcAggregated.
func (mr *MockRelationResourceServiceMockRecorder) ListSrcAggregated(ctx, modelUid, id any) *MockRelationResourceServiceListSrcAggregatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSrcAggregated", reflect.TypeOf((*MockRelationResourceService)(nil).ListSrcAggregated), ctx, modelUid, id)
	return &MockRelationResourceServiceListSrcAggregatedCall{Call: call}
}

// MockRelationResourceServiceListSrcAggregatedCall wrap *gomock.Call
type MockRelationResourceServiceListSrcAggregatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListSrcAggregatedCall) Return(arg0 []domain.ResourceAggregatedAssets, arg1 error) *MockRelationResourceServiceListSrcAggregatedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListSrcAggregatedCall) Do(f func(context.Context, string, int64) ([]domain.ResourceAggregatedAssets, error)) *MockRelationResourceServiceListSrcAggregatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListSrcAggregatedCall) DoAndReturn(f func(context.Context, string, int64) ([]domain.ResourceAggregatedAssets, error)) *MockRelationResourceServiceListSrcAggregatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSrcRelated mocks base method.
func (m *MockRelationResourceService) ListSrcRelated(ctx context.Context, modelUid, relationName string, id int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSrcRelated", ctx, modelUid, relationName, id)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSrcRelated indicates an expected call of ListSrcRelated.
func (mr *MockRelationResourceServiceMockRecorder) ListSrcRelated(ctx, modelUid, relationName, id any) *MockRelationResourceServiceListSrcRelatedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSrcRelated", reflect.TypeOf((*MockRelationResourceService)(nil).ListSrcRelated), ctx, modelUid, relationName, id)
	return &MockRelationResourceServiceListSrcRelatedCall{Call: call}
}

// MockRelationResourceServiceListSrcRelatedCall wrap *gomock.Call
type MockRelationResourceServiceListSrcRelatedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListSrcRelatedCall) Return(arg0 []int64, arg1 error) *MockRelationResourceServiceListSrcRelatedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListSrcRelatedCall) Do(f func(context.Context, string, string, int64) ([]int64, error)) *MockRelationResourceServiceListSrcRelatedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListSrcRelatedCall) DoAndReturn(f func(context.Context, string, string, int64) ([]int64, error)) *MockRelationResourceServiceListSrcRelatedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSrcResources mocks base method.
func (m *MockRelationResourceService) ListSrcResources(ctx context.Context, modelUid string, id int64) ([]domain.ResourceRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSrcResources", ctx, modelUid, id)
	ret0, _ := ret[0].([]domain.ResourceRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSrcResources indicates an expected call of ListSrcResources.
func (mr *MockRelationResourceServiceMockRecorder) ListSrcResources(ctx, modelUid, id any) *MockRelationResourceServiceListSrcResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSrcResources", reflect.TypeOf((*MockRelationResourceService)(nil).ListSrcResources), ctx, modelUid, id)
	return &MockRelationResourceServiceListSrcResourcesCall{Call: call}
}

// MockRelationResourceServiceListSrcResourcesCall wrap *gomock.Call
type MockRelationResourceServiceListSrcResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelationResourceServiceListSrcResourcesCall) Return(arg0 []domain.ResourceRelation, arg1 error) *MockRelationResourceServiceListSrcResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelationResourceServiceListSrcResourcesCall) Do(f func(context.Context, string, int64) ([]domain.ResourceRelation, error)) *MockRelationResourceServiceListSrcResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelationResourceServiceListSrcResourcesCall) DoAndReturn(f func(context.Context, string, int64) ([]domain.ResourceRelation, error)) *MockRelationResourceServiceListSrcResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
