// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resource

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/Duke1616/ecmdb/internal/resource/internal/repository"
	"github.com/Duke1616/ecmdb/internal/resource/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/resource/internal/service"
	"github.com/Duke1616/ecmdb/internal/resource/internal/web"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, attributeModule *attribute.Module, relationModule *relation.Module, aesKey string) (*Module, error) {
	resourceDAO := InitResourceDAO(db)
	resourceRepository := repository.NewResourceRepository(resourceDAO)
	service := NewService(resourceRepository)
	serviceService := attributeModule.Svc
	encryptedSvc := NewEncryptedService(service, serviceService, aesKey)
	relationResourceService := relationModule.RRSvc
	handler := web.NewHandler(encryptedSvc, serviceService, relationResourceService)
	module := &Module{
		Svc:          service,
		EncryptedSvc: encryptedSvc,
		Hdl:          handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, repository.NewResourceRepository)

var daoOnce = sync.Once{}

func InitCollectionOnce(db *mongox.Mongo) {
	daoOnce.Do(func() {
		err := dao.InitIndexes(db)
		if err != nil {
			panic(err)
		}
	})
}

func InitResourceDAO(db *mongox.Mongo) dao.ResourceDAO {
	InitCollectionOnce(db)
	return dao.NewResourceDAO(db)
}

func NewService(repo repository.ResourceRepository) Service {
	return service.NewService(repo)
}

func NewEncryptedService(baseSvc service.Service, attrSvc attribute.Service,
	aesKey string) EncryptedSvc {
	return service.NewEncryptedResourceService(baseSvc, attrSvc, aesKey)
}
