// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resource

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/resource/internal/repository"
	"github.com/Duke1616/ecmdb/internal/resource/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/resource/internal/service"
	"github.com/Duke1616/ecmdb/internal/resource/internal/web"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *mongo.Client, attributeModule *attribute.Module) (*Module, error) {
	resourceDAO := InitResourceDAO(db)
	resourceRepository := repository.NewResourceRepository(resourceDAO)
	service := NewService(resourceRepository)
	serviceService := attributeModule.Svc
	handler := web.NewHandler(service, serviceService)
	module := &Module{
		Svc: service,
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, repository.NewResourceRepository)

var daoOnce = sync.Once{}

func InitCollectionOnce(db *mongo.Client) {
	daoOnce.Do(func() {
		err := dao.InitIndexes(db)
		if err != nil {
			panic(err)
		}
	})
}

func InitResourceDAO(db *mongo.Client) dao.ResourceDAO {
	InitCollectionOnce(db)
	return dao.NewResourceDAO(db)
}

func NewService(repo repository.ResourceRepository) Service {
	return service.NewService(repo)
}
