// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tools

import (
	"github.com/Duke1616/ecmdb/internal/tools/web"
)

// Injectors from wire.go:

func InitModule() (*web.Handler, error) {
	handler := web.NewHandler()
	return handler, nil
}
