// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Duke1616/ecmdb/internal/repository (interfaces: ResourceRepository)
//
// Generated by this command:
//
//	mockgen -package=resourcemocks -destination=./mocks/repository.mock.go -typed github.com/Duke1616/ecmdb/internal/repository ResourceRepository
//

// Package resourcemocks is a generated GoMock package.
package resourcemocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceRepository is a mock of ResourceRepository interface.
type MockResourceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockResourceRepositoryMockRecorder
	isgomock struct{}
}

// MockResourceRepositoryMockRecorder is the mock recorder for MockResourceRepository.
type MockResourceRepositoryMockRecorder struct {
	mock *MockResourceRepository
}

// NewMockResourceRepository creates a new mock instance.
func NewMockResourceRepository(ctrl *gomock.Controller) *MockResourceRepository {
	mock := &MockResourceRepository{ctrl: ctrl}
	mock.recorder = &MockResourceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceRepository) EXPECT() *MockResourceRepositoryMockRecorder {
	return m.recorder
}

// BatchCreateOrUpdate mocks base method.
func (m *MockResourceRepository) BatchCreateOrUpdate(ctx context.Context, resources []domain.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateOrUpdate", ctx, resources)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateOrUpdate indicates an expected call of BatchCreateOrUpdate.
func (mr *MockResourceRepositoryMockRecorder) BatchCreateOrUpdate(ctx, resources any) *MockResourceRepositoryBatchCreateOrUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateOrUpdate", reflect.TypeOf((*MockResourceRepository)(nil).BatchCreateOrUpdate), ctx, resources)
	return &MockResourceRepositoryBatchCreateOrUpdateCall{Call: call}
}

// MockResourceRepositoryBatchCreateOrUpdateCall wrap *gomock.Call
type MockResourceRepositoryBatchCreateOrUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryBatchCreateOrUpdateCall) Return(arg0 error) *MockResourceRepositoryBatchCreateOrUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryBatchCreateOrUpdateCall) Do(f func(context.Context, []domain.Resource) error) *MockResourceRepositoryBatchCreateOrUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryBatchCreateOrUpdateCall) DoAndReturn(f func(context.Context, []domain.Resource) error) *MockResourceRepositoryBatchCreateOrUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BatchUpdateResources mocks base method.
func (m *MockResourceRepository) BatchUpdateResources(ctx context.Context, resources []domain.Resource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateResources", ctx, resources)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateResources indicates an expected call of BatchUpdateResources.
func (mr *MockResourceRepositoryMockRecorder) BatchUpdateResources(ctx, resources any) *MockResourceRepositoryBatchUpdateResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateResources", reflect.TypeOf((*MockResourceRepository)(nil).BatchUpdateResources), ctx, resources)
	return &MockResourceRepositoryBatchUpdateResourcesCall{Call: call}
}

// MockResourceRepositoryBatchUpdateResourcesCall wrap *gomock.Call
type MockResourceRepositoryBatchUpdateResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryBatchUpdateResourcesCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryBatchUpdateResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryBatchUpdateResourcesCall) Do(f func(context.Context, []domain.Resource) (int64, error)) *MockResourceRepositoryBatchUpdateResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryBatchUpdateResourcesCall) DoAndReturn(f func(context.Context, []domain.Resource) (int64, error)) *MockResourceRepositoryBatchUpdateResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountByModelUids mocks base method.
func (m *MockResourceRepository) CountByModelUids(ctx context.Context, modelUids []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByModelUids", ctx, modelUids)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByModelUids indicates an expected call of CountByModelUids.
func (mr *MockResourceRepositoryMockRecorder) CountByModelUids(ctx, modelUids any) *MockResourceRepositoryCountByModelUidsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByModelUids", reflect.TypeOf((*MockResourceRepository)(nil).CountByModelUids), ctx, modelUids)
	return &MockResourceRepositoryCountByModelUidsCall{Call: call}
}

// MockResourceRepositoryCountByModelUidsCall wrap *gomock.Call
type MockResourceRepositoryCountByModelUidsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryCountByModelUidsCall) Return(arg0 map[string]int, arg1 error) *MockResourceRepositoryCountByModelUidsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryCountByModelUidsCall) Do(f func(context.Context, []string) (map[string]int, error)) *MockResourceRepositoryCountByModelUidsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryCountByModelUidsCall) DoAndReturn(f func(context.Context, []string) (map[string]int, error)) *MockResourceRepositoryCountByModelUidsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateResource mocks base method.
func (m *MockResourceRepository) CreateResource(ctx context.Context, req domain.Resource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockResourceRepositoryMockRecorder) CreateResource(ctx, req any) *MockResourceRepositoryCreateResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockResourceRepository)(nil).CreateResource), ctx, req)
	return &MockResourceRepositoryCreateResourceCall{Call: call}
}

// MockResourceRepositoryCreateResourceCall wrap *gomock.Call
type MockResourceRepositoryCreateResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryCreateResourceCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryCreateResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryCreateResourceCall) Do(f func(context.Context, domain.Resource) (int64, error)) *MockResourceRepositoryCreateResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryCreateResourceCall) DoAndReturn(f func(context.Context, domain.Resource) (int64, error)) *MockResourceRepositoryCreateResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteResource mocks base method.
func (m *MockResourceRepository) DeleteResource(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockResourceRepositoryMockRecorder) DeleteResource(ctx, id any) *MockResourceRepositoryDeleteResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockResourceRepository)(nil).DeleteResource), ctx, id)
	return &MockResourceRepositoryDeleteResourceCall{Call: call}
}

// MockResourceRepositoryDeleteResourceCall wrap *gomock.Call
type MockResourceRepositoryDeleteResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryDeleteResourceCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryDeleteResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryDeleteResourceCall) Do(f func(context.Context, int64) (int64, error)) *MockResourceRepositoryDeleteResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryDeleteResourceCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockResourceRepositoryDeleteResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindResourceById mocks base method.
func (m *MockResourceRepository) FindResourceById(ctx context.Context, fields []string, id int64) (domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindResourceById", ctx, fields, id)
	ret0, _ := ret[0].(domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindResourceById indicates an expected call of FindResourceById.
func (mr *MockResourceRepositoryMockRecorder) FindResourceById(ctx, fields, id any) *MockResourceRepositoryFindResourceByIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindResourceById", reflect.TypeOf((*MockResourceRepository)(nil).FindResourceById), ctx, fields, id)
	return &MockResourceRepositoryFindResourceByIdCall{Call: call}
}

// MockResourceRepositoryFindResourceByIdCall wrap *gomock.Call
type MockResourceRepositoryFindResourceByIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryFindResourceByIdCall) Return(arg0 domain.Resource, arg1 error) *MockResourceRepositoryFindResourceByIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryFindResourceByIdCall) Do(f func(context.Context, []string, int64) (domain.Resource, error)) *MockResourceRepositoryFindResourceByIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryFindResourceByIdCall) DoAndReturn(f func(context.Context, []string, int64) (domain.Resource, error)) *MockResourceRepositoryFindResourceByIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindSecureData mocks base method.
func (m *MockResourceRepository) FindSecureData(ctx context.Context, id int64, fieldUid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSecureData", ctx, id, fieldUid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSecureData indicates an expected call of FindSecureData.
func (mr *MockResourceRepositoryMockRecorder) FindSecureData(ctx, id, fieldUid any) *MockResourceRepositoryFindSecureDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSecureData", reflect.TypeOf((*MockResourceRepository)(nil).FindSecureData), ctx, id, fieldUid)
	return &MockResourceRepositoryFindSecureDataCall{Call: call}
}

// MockResourceRepositoryFindSecureDataCall wrap *gomock.Call
type MockResourceRepositoryFindSecureDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryFindSecureDataCall) Return(arg0 string, arg1 error) *MockResourceRepositoryFindSecureDataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryFindSecureDataCall) Do(f func(context.Context, int64, string) (string, error)) *MockResourceRepositoryFindSecureDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryFindSecureDataCall) DoAndReturn(f func(context.Context, int64, string) (string, error)) *MockResourceRepositoryFindSecureDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListBeforeUtime mocks base method.
func (m *MockResourceRepository) ListBeforeUtime(ctx context.Context, utime int64, fields []string, modelUid string, offset, limit int64) ([]domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBeforeUtime", ctx, utime, fields, modelUid, offset, limit)
	ret0, _ := ret[0].([]domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBeforeUtime indicates an expected call of ListBeforeUtime.
func (mr *MockResourceRepositoryMockRecorder) ListBeforeUtime(ctx, utime, fields, modelUid, offset, limit any) *MockResourceRepositoryListBeforeUtimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBeforeUtime", reflect.TypeOf((*MockResourceRepository)(nil).ListBeforeUtime), ctx, utime, fields, modelUid, offset, limit)
	return &MockResourceRepositoryListBeforeUtimeCall{Call: call}
}

// MockResourceRepositoryListBeforeUtimeCall wrap *gomock.Call
type MockResourceRepositoryListBeforeUtimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryListBeforeUtimeCall) Return(arg0 []domain.Resource, arg1 error) *MockResourceRepositoryListBeforeUtimeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryListBeforeUtimeCall) Do(f func(context.Context, int64, []string, string, int64, int64) ([]domain.Resource, error)) *MockResourceRepositoryListBeforeUtimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryListBeforeUtimeCall) DoAndReturn(f func(context.Context, int64, []string, string, int64, int64) ([]domain.Resource, error)) *MockResourceRepositoryListBeforeUtimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListExcludeAndFilterResourceByIds mocks base method.
func (m *MockResourceRepository) ListExcludeAndFilterResourceByIds(ctx context.Context, fields []string, modelUid string, offset, limit int64, ids []int64, filter domain.Condition) ([]domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExcludeAndFilterResourceByIds", ctx, fields, modelUid, offset, limit, ids, filter)
	ret0, _ := ret[0].([]domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExcludeAndFilterResourceByIds indicates an expected call of ListExcludeAndFilterResourceByIds.
func (mr *MockResourceRepositoryMockRecorder) ListExcludeAndFilterResourceByIds(ctx, fields, modelUid, offset, limit, ids, filter any) *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExcludeAndFilterResourceByIds", reflect.TypeOf((*MockResourceRepository)(nil).ListExcludeAndFilterResourceByIds), ctx, fields, modelUid, offset, limit, ids, filter)
	return &MockResourceRepositoryListExcludeAndFilterResourceByIdsCall{Call: call}
}

// MockResourceRepositoryListExcludeAndFilterResourceByIdsCall wrap *gomock.Call
type MockResourceRepositoryListExcludeAndFilterResourceByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall) Return(arg0 []domain.Resource, arg1 error) *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall) Do(f func(context.Context, []string, string, int64, int64, []int64, domain.Condition) ([]domain.Resource, error)) *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall) DoAndReturn(f func(context.Context, []string, string, int64, int64, []int64, domain.Condition) ([]domain.Resource, error)) *MockResourceRepositoryListExcludeAndFilterResourceByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResource mocks base method.
func (m *MockResourceRepository) ListResource(ctx context.Context, fields []string, modelUid string, offset, limit int64) ([]domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResource", ctx, fields, modelUid, offset, limit)
	ret0, _ := ret[0].([]domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResource indicates an expected call of ListResource.
func (mr *MockResourceRepositoryMockRecorder) ListResource(ctx, fields, modelUid, offset, limit any) *MockResourceRepositoryListResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResource", reflect.TypeOf((*MockResourceRepository)(nil).ListResource), ctx, fields, modelUid, offset, limit)
	return &MockResourceRepositoryListResourceCall{Call: call}
}

// MockResourceRepositoryListResourceCall wrap *gomock.Call
type MockResourceRepositoryListResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryListResourceCall) Return(arg0 []domain.Resource, arg1 error) *MockResourceRepositoryListResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryListResourceCall) Do(f func(context.Context, []string, string, int64, int64) ([]domain.Resource, error)) *MockResourceRepositoryListResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryListResourceCall) DoAndReturn(f func(context.Context, []string, string, int64, int64) ([]domain.Resource, error)) *MockResourceRepositoryListResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResourcesByIds mocks base method.
func (m *MockResourceRepository) ListResourcesByIds(ctx context.Context, fields []string, ids []int64) ([]domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourcesByIds", ctx, fields, ids)
	ret0, _ := ret[0].([]domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourcesByIds indicates an expected call of ListResourcesByIds.
func (mr *MockResourceRepositoryMockRecorder) ListResourcesByIds(ctx, fields, ids any) *MockResourceRepositoryListResourcesByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourcesByIds", reflect.TypeOf((*MockResourceRepository)(nil).ListResourcesByIds), ctx, fields, ids)
	return &MockResourceRepositoryListResourcesByIdsCall{Call: call}
}

// MockResourceRepositoryListResourcesByIdsCall wrap *gomock.Call
type MockResourceRepositoryListResourcesByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryListResourcesByIdsCall) Return(arg0 []domain.Resource, arg1 error) *MockResourceRepositoryListResourcesByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryListResourcesByIdsCall) Do(f func(context.Context, []string, []int64) ([]domain.Resource, error)) *MockResourceRepositoryListResourcesByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryListResourcesByIdsCall) DoAndReturn(f func(context.Context, []string, []int64) ([]domain.Resource, error)) *MockResourceRepositoryListResourcesByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResourcesWithFilters mocks base method.
func (m *MockResourceRepository) ListResourcesWithFilters(ctx context.Context, fields []string, modelUid string, ids []int64, offset, limit int64, filterGroups []domain.FilterGroup) ([]domain.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourcesWithFilters", ctx, fields, modelUid, ids, offset, limit, filterGroups)
	ret0, _ := ret[0].([]domain.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourcesWithFilters indicates an expected call of ListResourcesWithFilters.
func (mr *MockResourceRepositoryMockRecorder) ListResourcesWithFilters(ctx, fields, modelUid, ids, offset, limit, filterGroups any) *MockResourceRepositoryListResourcesWithFiltersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourcesWithFilters", reflect.TypeOf((*MockResourceRepository)(nil).ListResourcesWithFilters), ctx, fields, modelUid, ids, offset, limit, filterGroups)
	return &MockResourceRepositoryListResourcesWithFiltersCall{Call: call}
}

// MockResourceRepositoryListResourcesWithFiltersCall wrap *gomock.Call
type MockResourceRepositoryListResourcesWithFiltersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryListResourcesWithFiltersCall) Return(arg0 []domain.Resource, arg1 error) *MockResourceRepositoryListResourcesWithFiltersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryListResourcesWithFiltersCall) Do(f func(context.Context, []string, string, []int64, int64, int64, []domain.FilterGroup) ([]domain.Resource, error)) *MockResourceRepositoryListResourcesWithFiltersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryListResourcesWithFiltersCall) DoAndReturn(f func(context.Context, []string, string, []int64, int64, int64, []domain.FilterGroup) ([]domain.Resource, error)) *MockResourceRepositoryListResourcesWithFiltersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Search mocks base method.
func (m *MockResourceRepository) Search(ctx context.Context, text string) ([]domain.SearchResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, text)
	ret0, _ := ret[0].([]domain.SearchResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockResourceRepositoryMockRecorder) Search(ctx, text any) *MockResourceRepositorySearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockResourceRepository)(nil).Search), ctx, text)
	return &MockResourceRepositorySearchCall{Call: call}
}

// MockResourceRepositorySearchCall wrap *gomock.Call
type MockResourceRepositorySearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositorySearchCall) Return(arg0 []domain.SearchResource, arg1 error) *MockResourceRepositorySearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositorySearchCall) Do(f func(context.Context, string) ([]domain.SearchResource, error)) *MockResourceRepositorySearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositorySearchCall) DoAndReturn(f func(context.Context, string) ([]domain.SearchResource, error)) *MockResourceRepositorySearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetCustomField mocks base method.
func (m *MockResourceRepository) SetCustomField(ctx context.Context, id int64, field string, data any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCustomField", ctx, id, field, data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCustomField indicates an expected call of SetCustomField.
func (mr *MockResourceRepositoryMockRecorder) SetCustomField(ctx, id, field, data any) *MockResourceRepositorySetCustomFieldCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCustomField", reflect.TypeOf((*MockResourceRepository)(nil).SetCustomField), ctx, id, field, data)
	return &MockResourceRepositorySetCustomFieldCall{Call: call}
}

// MockResourceRepositorySetCustomFieldCall wrap *gomock.Call
type MockResourceRepositorySetCustomFieldCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositorySetCustomFieldCall) Return(arg0 int64, arg1 error) *MockResourceRepositorySetCustomFieldCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositorySetCustomFieldCall) Do(f func(context.Context, int64, string, any) (int64, error)) *MockResourceRepositorySetCustomFieldCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositorySetCustomFieldCall) DoAndReturn(f func(context.Context, int64, string, any) (int64, error)) *MockResourceRepositorySetCustomFieldCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TotalByModelUid mocks base method.
func (m *MockResourceRepository) TotalByModelUid(ctx context.Context, modelUid string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalByModelUid", ctx, modelUid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalByModelUid indicates an expected call of TotalByModelUid.
func (mr *MockResourceRepositoryMockRecorder) TotalByModelUid(ctx, modelUid any) *MockResourceRepositoryTotalByModelUidCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalByModelUid", reflect.TypeOf((*MockResourceRepository)(nil).TotalByModelUid), ctx, modelUid)
	return &MockResourceRepositoryTotalByModelUidCall{Call: call}
}

// MockResourceRepositoryTotalByModelUidCall wrap *gomock.Call
type MockResourceRepositoryTotalByModelUidCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryTotalByModelUidCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryTotalByModelUidCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryTotalByModelUidCall) Do(f func(context.Context, string) (int64, error)) *MockResourceRepositoryTotalByModelUidCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryTotalByModelUidCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockResourceRepositoryTotalByModelUidCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TotalExcludeAndFilterResourceByIds mocks base method.
func (m *MockResourceRepository) TotalExcludeAndFilterResourceByIds(ctx context.Context, modelUid string, ids []int64, filter domain.Condition) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalExcludeAndFilterResourceByIds", ctx, modelUid, ids, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalExcludeAndFilterResourceByIds indicates an expected call of TotalExcludeAndFilterResourceByIds.
func (mr *MockResourceRepositoryMockRecorder) TotalExcludeAndFilterResourceByIds(ctx, modelUid, ids, filter any) *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalExcludeAndFilterResourceByIds", reflect.TypeOf((*MockResourceRepository)(nil).TotalExcludeAndFilterResourceByIds), ctx, modelUid, ids, filter)
	return &MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall{Call: call}
}

// MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall wrap *gomock.Call
type MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall) Do(f func(context.Context, string, []int64, domain.Condition) (int64, error)) *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall) DoAndReturn(f func(context.Context, string, []int64, domain.Condition) (int64, error)) *MockResourceRepositoryTotalExcludeAndFilterResourceByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TotalResourcesWithFilters mocks base method.
func (m *MockResourceRepository) TotalResourcesWithFilters(ctx context.Context, modelUid string, ids []int64, filterGroups []domain.FilterGroup) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalResourcesWithFilters", ctx, modelUid, ids, filterGroups)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalResourcesWithFilters indicates an expected call of TotalResourcesWithFilters.
func (mr *MockResourceRepositoryMockRecorder) TotalResourcesWithFilters(ctx, modelUid, ids, filterGroups any) *MockResourceRepositoryTotalResourcesWithFiltersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalResourcesWithFilters", reflect.TypeOf((*MockResourceRepository)(nil).TotalResourcesWithFilters), ctx, modelUid, ids, filterGroups)
	return &MockResourceRepositoryTotalResourcesWithFiltersCall{Call: call}
}

// MockResourceRepositoryTotalResourcesWithFiltersCall wrap *gomock.Call
type MockResourceRepositoryTotalResourcesWithFiltersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryTotalResourcesWithFiltersCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryTotalResourcesWithFiltersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryTotalResourcesWithFiltersCall) Do(f func(context.Context, string, []int64, []domain.FilterGroup) (int64, error)) *MockResourceRepositoryTotalResourcesWithFiltersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryTotalResourcesWithFiltersCall) DoAndReturn(f func(context.Context, string, []int64, []domain.FilterGroup) (int64, error)) *MockResourceRepositoryTotalResourcesWithFiltersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnsetCustomField mocks base method.
func (m *MockResourceRepository) UnsetCustomField(ctx context.Context, modelUid, fieldUid string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetCustomField", ctx, modelUid, fieldUid)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsetCustomField indicates an expected call of UnsetCustomField.
func (mr *MockResourceRepositoryMockRecorder) UnsetCustomField(ctx, modelUid, fieldUid any) *MockResourceRepositoryUnsetCustomFieldCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetCustomField", reflect.TypeOf((*MockResourceRepository)(nil).UnsetCustomField), ctx, modelUid, fieldUid)
	return &MockResourceRepositoryUnsetCustomFieldCall{Call: call}
}

// MockResourceRepositoryUnsetCustomFieldCall wrap *gomock.Call
type MockResourceRepositoryUnsetCustomFieldCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryUnsetCustomFieldCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryUnsetCustomFieldCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryUnsetCustomFieldCall) Do(f func(context.Context, string, string) (int64, error)) *MockResourceRepositoryUnsetCustomFieldCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryUnsetCustomFieldCall) DoAndReturn(f func(context.Context, string, string) (int64, error)) *MockResourceRepositoryUnsetCustomFieldCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateResource mocks base method.
func (m *MockResourceRepository) UpdateResource(ctx context.Context, resource domain.Resource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResource", ctx, resource)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResource indicates an expected call of UpdateResource.
func (mr *MockResourceRepositoryMockRecorder) UpdateResource(ctx, resource any) *MockResourceRepositoryUpdateResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResource", reflect.TypeOf((*MockResourceRepository)(nil).UpdateResource), ctx, resource)
	return &MockResourceRepositoryUpdateResourceCall{Call: call}
}

// MockResourceRepositoryUpdateResourceCall wrap *gomock.Call
type MockResourceRepositoryUpdateResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceRepositoryUpdateResourceCall) Return(arg0 int64, arg1 error) *MockResourceRepositoryUpdateResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceRepositoryUpdateResourceCall) Do(f func(context.Context, domain.Resource) (int64, error)) *MockResourceRepositoryUpdateResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceRepositoryUpdateResourceCall) DoAndReturn(f func(context.Context, domain.Resource) (int64, error)) *MockResourceRepositoryUpdateResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
