// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=enginemocks -destination=../../mocks/engine.mock.go -typed Service
//

// Package enginemocks is a generated GoMock package.
package enginemocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Bunny3th/easy-workflow/workflow/model"
	domain "github.com/Duke1616/ecmdb/internal/engine/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateSkippedTask mocks base method.
func (m *MockService) CreateSkippedTask(ctx context.Context, processInstId int, nodeId, prevNodeId, comment string, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSkippedTask", ctx, processInstId, nodeId, prevNodeId, comment, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSkippedTask indicates an expected call of CreateSkippedTask.
func (mr *MockServiceMockRecorder) CreateSkippedTask(ctx, processInstId, nodeId, prevNodeId, comment, status any) *MockServiceCreateSkippedTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSkippedTask", reflect.TypeOf((*MockService)(nil).CreateSkippedTask), ctx, processInstId, nodeId, prevNodeId, comment, status)
	return &MockServiceCreateSkippedTaskCall{Call: call}
}

// MockServiceCreateSkippedTaskCall wrap *gomock.Call
type MockServiceCreateSkippedTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateSkippedTaskCall) Return(arg0 error) *MockServiceCreateSkippedTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateSkippedTaskCall) Do(f func(context.Context, int, string, string, string, uint8) error) *MockServiceCreateSkippedTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateSkippedTaskCall) DoAndReturn(f func(context.Context, int, string, string, string, uint8) error) *MockServiceCreateSkippedTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProxyNodeByNodeId mocks base method.
func (m *MockService) DeleteProxyNodeByNodeId(ctx context.Context, processInstId int, nodeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProxyNodeByNodeId", ctx, processInstId, nodeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProxyNodeByNodeId indicates an expected call of DeleteProxyNodeByNodeId.
func (mr *MockServiceMockRecorder) DeleteProxyNodeByNodeId(ctx, processInstId, nodeId any) *MockServiceDeleteProxyNodeByNodeIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProxyNodeByNodeId", reflect.TypeOf((*MockService)(nil).DeleteProxyNodeByNodeId), ctx, processInstId, nodeId)
	return &MockServiceDeleteProxyNodeByNodeIdCall{Call: call}
}

// MockServiceDeleteProxyNodeByNodeIdCall wrap *gomock.Call
type MockServiceDeleteProxyNodeByNodeIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteProxyNodeByNodeIdCall) Return(arg0 error) *MockServiceDeleteProxyNodeByNodeIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteProxyNodeByNodeIdCall) Do(f func(context.Context, int, string) error) *MockServiceDeleteProxyNodeByNodeIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteProxyNodeByNodeIdCall) DoAndReturn(f func(context.Context, int, string) error) *MockServiceDeleteProxyNodeByNodeIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ForceUpdateIsFinishedByNodeId mocks base method.
func (m *MockService) ForceUpdateIsFinishedByNodeId(ctx context.Context, processInstId int, nodeId string, status int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceUpdateIsFinishedByNodeId", ctx, processInstId, nodeId, status, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceUpdateIsFinishedByNodeId indicates an expected call of ForceUpdateIsFinishedByNodeId.
func (mr *MockServiceMockRecorder) ForceUpdateIsFinishedByNodeId(ctx, processInstId, nodeId, status, comment any) *MockServiceForceUpdateIsFinishedByNodeIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUpdateIsFinishedByNodeId", reflect.TypeOf((*MockService)(nil).ForceUpdateIsFinishedByNodeId), ctx, processInstId, nodeId, status, comment)
	return &MockServiceForceUpdateIsFinishedByNodeIdCall{Call: call}
}

// MockServiceForceUpdateIsFinishedByNodeIdCall wrap *gomock.Call
type MockServiceForceUpdateIsFinishedByNodeIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceForceUpdateIsFinishedByNodeIdCall) Return(arg0 error) *MockServiceForceUpdateIsFinishedByNodeIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceForceUpdateIsFinishedByNodeIdCall) Do(f func(context.Context, int, string, int, string) error) *MockServiceForceUpdateIsFinishedByNodeIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceForceUpdateIsFinishedByNodeIdCall) DoAndReturn(f func(context.Context, int, string, int, string) error) *MockServiceForceUpdateIsFinishedByNodeIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ForceUpdateIsFinishedByPreNodeId mocks base method.
func (m *MockService) ForceUpdateIsFinishedByPreNodeId(ctx context.Context, processInstId int, nodeId string, status int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceUpdateIsFinishedByPreNodeId", ctx, processInstId, nodeId, status, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceUpdateIsFinishedByPreNodeId indicates an expected call of ForceUpdateIsFinishedByPreNodeId.
func (mr *MockServiceMockRecorder) ForceUpdateIsFinishedByPreNodeId(ctx, processInstId, nodeId, status, comment any) *MockServiceForceUpdateIsFinishedByPreNodeIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUpdateIsFinishedByPreNodeId", reflect.TypeOf((*MockService)(nil).ForceUpdateIsFinishedByPreNodeId), ctx, processInstId, nodeId, status, comment)
	return &MockServiceForceUpdateIsFinishedByPreNodeIdCall{Call: call}
}

// MockServiceForceUpdateIsFinishedByPreNodeIdCall wrap *gomock.Call
type MockServiceForceUpdateIsFinishedByPreNodeIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceForceUpdateIsFinishedByPreNodeIdCall) Return(arg0 error) *MockServiceForceUpdateIsFinishedByPreNodeIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceForceUpdateIsFinishedByPreNodeIdCall) Do(f func(context.Context, int, string, int, string) error) *MockServiceForceUpdateIsFinishedByPreNodeIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceForceUpdateIsFinishedByPreNodeIdCall) DoAndReturn(f func(context.Context, int, string, int, string) error) *MockServiceForceUpdateIsFinishedByPreNodeIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAutomationTask mocks base method.
func (m *MockService) GetAutomationTask(ctx context.Context, currentNodeId string, processInstId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationTask", ctx, currentNodeId, processInstId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationTask indicates an expected call of GetAutomationTask.
func (mr *MockServiceMockRecorder) GetAutomationTask(ctx, currentNodeId, processInstId any) *MockServiceGetAutomationTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationTask", reflect.TypeOf((*MockService)(nil).GetAutomationTask), ctx, currentNodeId, processInstId)
	return &MockServiceGetAutomationTaskCall{Call: call}
}

// MockServiceGetAutomationTaskCall wrap *gomock.Call
type MockServiceGetAutomationTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetAutomationTaskCall) Return(arg0 model.Task, arg1 error) *MockServiceGetAutomationTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetAutomationTaskCall) Do(f func(context.Context, string, int) (model.Task, error)) *MockServiceGetAutomationTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetAutomationTaskCall) DoAndReturn(f func(context.Context, string, int) (model.Task, error)) *MockServiceGetAutomationTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetInstanceByID mocks base method.
func (m *MockService) GetInstanceByID(ctx context.Context, processInstId int) (domain.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceByID", ctx, processInstId)
	ret0, _ := ret[0].(domain.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceByID indicates an expected call of GetInstanceByID.
func (mr *MockServiceMockRecorder) GetInstanceByID(ctx, processInstId any) *MockServiceGetInstanceByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceByID", reflect.TypeOf((*MockService)(nil).GetInstanceByID), ctx, processInstId)
	return &MockServiceGetInstanceByIDCall{Call: call}
}

// MockServiceGetInstanceByIDCall wrap *gomock.Call
type MockServiceGetInstanceByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetInstanceByIDCall) Return(arg0 domain.Instance, arg1 error) *MockServiceGetInstanceByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetInstanceByIDCall) Do(f func(context.Context, int) (domain.Instance, error)) *MockServiceGetInstanceByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetInstanceByIDCall) DoAndReturn(f func(context.Context, int) (domain.Instance, error)) *MockServiceGetInstanceByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLatestProcessVersion mocks base method.
func (m *MockService) GetLatestProcessVersion(ctx context.Context, processID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestProcessVersion", ctx, processID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestProcessVersion indicates an expected call of GetLatestProcessVersion.
func (mr *MockServiceMockRecorder) GetLatestProcessVersion(ctx, processID any) *MockServiceGetLatestProcessVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestProcessVersion", reflect.TypeOf((*MockService)(nil).GetLatestProcessVersion), ctx, processID)
	return &MockServiceGetLatestProcessVersionCall{Call: call}
}

// MockServiceGetLatestProcessVersionCall wrap *gomock.Call
type MockServiceGetLatestProcessVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetLatestProcessVersionCall) Return(arg0 int, arg1 error) *MockServiceGetLatestProcessVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetLatestProcessVersionCall) Do(f func(context.Context, int) (int, error)) *MockServiceGetLatestProcessVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetLatestProcessVersionCall) DoAndReturn(f func(context.Context, int) (int, error)) *MockServiceGetLatestProcessVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOrderIdByVariable mocks base method.
func (m *MockService) GetOrderIdByVariable(ctx context.Context, processInstId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderIdByVariable", ctx, processInstId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderIdByVariable indicates an expected call of GetOrderIdByVariable.
func (mr *MockServiceMockRecorder) GetOrderIdByVariable(ctx, processInstId any) *MockServiceGetOrderIdByVariableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderIdByVariable", reflect.TypeOf((*MockService)(nil).GetOrderIdByVariable), ctx, processInstId)
	return &MockServiceGetOrderIdByVariableCall{Call: call}
}

// MockServiceGetOrderIdByVariableCall wrap *gomock.Call
type MockServiceGetOrderIdByVariableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetOrderIdByVariableCall) Return(arg0 string, arg1 error) *MockServiceGetOrderIdByVariableCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetOrderIdByVariableCall) Do(f func(context.Context, int) (string, error)) *MockServiceGetOrderIdByVariableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetOrderIdByVariableCall) DoAndReturn(f func(context.Context, int) (string, error)) *MockServiceGetOrderIdByVariableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProcessDefineByVersion mocks base method.
func (m *MockService) GetProcessDefineByVersion(ctx context.Context, processID, version int) (model.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessDefineByVersion", ctx, processID, version)
	ret0, _ := ret[0].(model.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessDefineByVersion indicates an expected call of GetProcessDefineByVersion.
func (mr *MockServiceMockRecorder) GetProcessDefineByVersion(ctx, processID, version any) *MockServiceGetProcessDefineByVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessDefineByVersion", reflect.TypeOf((*MockService)(nil).GetProcessDefineByVersion), ctx, processID, version)
	return &MockServiceGetProcessDefineByVersionCall{Call: call}
}

// MockServiceGetProcessDefineByVersionCall wrap *gomock.Call
type MockServiceGetProcessDefineByVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetProcessDefineByVersionCall) Return(arg0 model.Process, arg1 error) *MockServiceGetProcessDefineByVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetProcessDefineByVersionCall) Do(f func(context.Context, int, int) (model.Process, error)) *MockServiceGetProcessDefineByVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetProcessDefineByVersionCall) DoAndReturn(f func(context.Context, int, int) (model.Process, error)) *MockServiceGetProcessDefineByVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProxyNodeByProcessInstId mocks base method.
func (m *MockService) GetProxyNodeByProcessInstId(ctx context.Context, processInstId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyNodeByProcessInstId", ctx, processInstId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyNodeByProcessInstId indicates an expected call of GetProxyNodeByProcessInstId.
func (mr *MockServiceMockRecorder) GetProxyNodeByProcessInstId(ctx, processInstId any) *MockServiceGetProxyNodeByProcessInstIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyNodeByProcessInstId", reflect.TypeOf((*MockService)(nil).GetProxyNodeByProcessInstId), ctx, processInstId)
	return &MockServiceGetProxyNodeByProcessInstIdCall{Call: call}
}

// MockServiceGetProxyNodeByProcessInstIdCall wrap *gomock.Call
type MockServiceGetProxyNodeByProcessInstIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetProxyNodeByProcessInstIdCall) Return(arg0 string, arg1 error) *MockServiceGetProxyNodeByProcessInstIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetProxyNodeByProcessInstIdCall) Do(f func(context.Context, int) (string, error)) *MockServiceGetProxyNodeByProcessInstIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetProxyNodeByProcessInstIdCall) DoAndReturn(f func(context.Context, int) (string, error)) *MockServiceGetProxyNodeByProcessInstIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProxyPrevNodeID mocks base method.
func (m *MockService) GetProxyPrevNodeID(ctx context.Context, processInstId int, prevNodeID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyPrevNodeID", ctx, processInstId, prevNodeID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyPrevNodeID indicates an expected call of GetProxyPrevNodeID.
func (mr *MockServiceMockRecorder) GetProxyPrevNodeID(ctx, processInstId, prevNodeID any) *MockServiceGetProxyPrevNodeIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyPrevNodeID", reflect.TypeOf((*MockService)(nil).GetProxyPrevNodeID), ctx, processInstId, prevNodeID)
	return &MockServiceGetProxyPrevNodeIDCall{Call: call}
}

// MockServiceGetProxyPrevNodeIDCall wrap *gomock.Call
type MockServiceGetProxyPrevNodeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetProxyPrevNodeIDCall) Return(arg0 string, arg1 error) *MockServiceGetProxyPrevNodeIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetProxyPrevNodeIDCall) Do(f func(context.Context, int, string) (string, error)) *MockServiceGetProxyPrevNodeIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetProxyPrevNodeIDCall) DoAndReturn(f func(context.Context, int, string) (string, error)) *MockServiceGetProxyPrevNodeIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProxyTaskByProcessInstId mocks base method.
func (m *MockService) GetProxyTaskByProcessInstId(ctx context.Context, processInstId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyTaskByProcessInstId", ctx, processInstId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyTaskByProcessInstId indicates an expected call of GetProxyTaskByProcessInstId.
func (mr *MockServiceMockRecorder) GetProxyTaskByProcessInstId(ctx, processInstId any) *MockServiceGetProxyTaskByProcessInstIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyTaskByProcessInstId", reflect.TypeOf((*MockService)(nil).GetProxyTaskByProcessInstId), ctx, processInstId)
	return &MockServiceGetProxyTaskByProcessInstIdCall{Call: call}
}

// MockServiceGetProxyTaskByProcessInstIdCall wrap *gomock.Call
type MockServiceGetProxyTaskByProcessInstIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetProxyTaskByProcessInstIdCall) Return(arg0 model.Task, arg1 error) *MockServiceGetProxyTaskByProcessInstIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetProxyTaskByProcessInstIdCall) Do(f func(context.Context, int) (model.Task, error)) *MockServiceGetProxyTaskByProcessInstIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetProxyTaskByProcessInstIdCall) DoAndReturn(f func(context.Context, int) (model.Task, error)) *MockServiceGetProxyTaskByProcessInstIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTasksByCurrentNodeId mocks base method.
func (m *MockService) GetTasksByCurrentNodeId(ctx context.Context, processInstId int, currentNodeId string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByCurrentNodeId", ctx, processInstId, currentNodeId)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByCurrentNodeId indicates an expected call of GetTasksByCurrentNodeId.
func (mr *MockServiceMockRecorder) GetTasksByCurrentNodeId(ctx, processInstId, currentNodeId any) *MockServiceGetTasksByCurrentNodeIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByCurrentNodeId", reflect.TypeOf((*MockService)(nil).GetTasksByCurrentNodeId), ctx, processInstId, currentNodeId)
	return &MockServiceGetTasksByCurrentNodeIdCall{Call: call}
}

// MockServiceGetTasksByCurrentNodeIdCall wrap *gomock.Call
type MockServiceGetTasksByCurrentNodeIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetTasksByCurrentNodeIdCall) Return(arg0 []model.Task, arg1 error) *MockServiceGetTasksByCurrentNodeIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetTasksByCurrentNodeIdCall) Do(f func(context.Context, int, string) ([]model.Task, error)) *MockServiceGetTasksByCurrentNodeIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetTasksByCurrentNodeIdCall) DoAndReturn(f func(context.Context, int, string) ([]model.Task, error)) *MockServiceGetTasksByCurrentNodeIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTasksByInstUsers mocks base method.
func (m *MockService) GetTasksByInstUsers(ctx context.Context, processInstId int, userIds []string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByInstUsers", ctx, processInstId, userIds)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByInstUsers indicates an expected call of GetTasksByInstUsers.
func (mr *MockServiceMockRecorder) GetTasksByInstUsers(ctx, processInstId, userIds any) *MockServiceGetTasksByInstUsersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByInstUsers", reflect.TypeOf((*MockService)(nil).GetTasksByInstUsers), ctx, processInstId, userIds)
	return &MockServiceGetTasksByInstUsersCall{Call: call}
}

// MockServiceGetTasksByInstUsersCall wrap *gomock.Call
type MockServiceGetTasksByInstUsersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetTasksByInstUsersCall) Return(arg0 []model.Task, arg1 error) *MockServiceGetTasksByInstUsersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetTasksByInstUsersCall) Do(f func(context.Context, int, []string) ([]model.Task, error)) *MockServiceGetTasksByInstUsersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetTasksByInstUsersCall) DoAndReturn(f func(context.Context, int, []string) ([]model.Task, error)) *MockServiceGetTasksByInstUsersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTraversedEdges mocks base method.
func (m *MockService) GetTraversedEdges(ctx context.Context, records []model.Task, processInstId, processId int, status uint8) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraversedEdges", ctx, records, processInstId, processId, status)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraversedEdges indicates an expected call of GetTraversedEdges.
func (mr *MockServiceMockRecorder) GetTraversedEdges(ctx, records, processInstId, processId, status any) *MockServiceGetTraversedEdgesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraversedEdges", reflect.TypeOf((*MockService)(nil).GetTraversedEdges), ctx, records, processInstId, processId, status)
	return &MockServiceGetTraversedEdgesCall{Call: call}
}

// MockServiceGetTraversedEdgesCall wrap *gomock.Call
type MockServiceGetTraversedEdgesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetTraversedEdgesCall) Return(arg0 map[string][]string, arg1 error) *MockServiceGetTraversedEdgesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetTraversedEdgesCall) Do(f func(context.Context, []model.Task, int, int, uint8) (map[string][]string, error)) *MockServiceGetTraversedEdgesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetTraversedEdgesCall) DoAndReturn(f func(context.Context, []model.Task, int, int, uint8) (map[string][]string, error)) *MockServiceGetTraversedEdgesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsReject mocks base method.
func (m *MockService) IsReject(ctx context.Context, taskId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReject", ctx, taskId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReject indicates an expected call of IsReject.
func (mr *MockServiceMockRecorder) IsReject(ctx, taskId any) *MockServiceIsRejectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReject", reflect.TypeOf((*MockService)(nil).IsReject), ctx, taskId)
	return &MockServiceIsRejectCall{Call: call}
}

// MockServiceIsRejectCall wrap *gomock.Call
type MockServiceIsRejectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceIsRejectCall) Return(arg0 bool, arg1 error) *MockServiceIsRejectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceIsRejectCall) Do(f func(context.Context, int) (bool, error)) *MockServiceIsRejectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceIsRejectCall) DoAndReturn(f func(context.Context, int) (bool, error)) *MockServiceIsRejectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByStartUser mocks base method.
func (m *MockService) ListByStartUser(ctx context.Context, userId, processName string, offset, limit int) ([]domain.Instance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStartUser", ctx, userId, processName, offset, limit)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByStartUser indicates an expected call of ListByStartUser.
func (mr *MockServiceMockRecorder) ListByStartUser(ctx, userId, processName, offset, limit any) *MockServiceListByStartUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStartUser", reflect.TypeOf((*MockService)(nil).ListByStartUser), ctx, userId, processName, offset, limit)
	return &MockServiceListByStartUserCall{Call: call}
}

// MockServiceListByStartUserCall wrap *gomock.Call
type MockServiceListByStartUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByStartUserCall) Return(arg0 []domain.Instance, arg1 int64, arg2 error) *MockServiceListByStartUserCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByStartUserCall) Do(f func(context.Context, string, string, int, int) ([]domain.Instance, int64, error)) *MockServiceListByStartUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByStartUserCall) DoAndReturn(f func(context.Context, string, string, int, int) ([]domain.Instance, int64, error)) *MockServiceListByStartUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListPendingStepsOfMyTask mocks base method.
func (m *MockService) ListPendingStepsOfMyTask(ctx context.Context, processInstIds []int, starter string) ([]domain.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingStepsOfMyTask", ctx, processInstIds, starter)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingStepsOfMyTask indicates an expected call of ListPendingStepsOfMyTask.
func (mr *MockServiceMockRecorder) ListPendingStepsOfMyTask(ctx, processInstIds, starter any) *MockServiceListPendingStepsOfMyTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingStepsOfMyTask", reflect.TypeOf((*MockService)(nil).ListPendingStepsOfMyTask), ctx, processInstIds, starter)
	return &MockServiceListPendingStepsOfMyTaskCall{Call: call}
}

// MockServiceListPendingStepsOfMyTaskCall wrap *gomock.Call
type MockServiceListPendingStepsOfMyTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListPendingStepsOfMyTaskCall) Return(arg0 []domain.Instance, arg1 error) *MockServiceListPendingStepsOfMyTaskCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListPendingStepsOfMyTaskCall) Do(f func(context.Context, []int, string) ([]domain.Instance, error)) *MockServiceListPendingStepsOfMyTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListPendingStepsOfMyTaskCall) DoAndReturn(f func(context.Context, []int, string) ([]domain.Instance, error)) *MockServiceListPendingStepsOfMyTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTodoTasks mocks base method.
func (m *MockService) ListTodoTasks(ctx context.Context, userId, processName string, sortByAse bool, offset, limit int) ([]domain.Instance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodoTasks", ctx, userId, processName, sortByAse, offset, limit)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTodoTasks indicates an expected call of ListTodoTasks.
func (mr *MockServiceMockRecorder) ListTodoTasks(ctx, userId, processName, sortByAse, offset, limit any) *MockServiceListTodoTasksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodoTasks", reflect.TypeOf((*MockService)(nil).ListTodoTasks), ctx, userId, processName, sortByAse, offset, limit)
	return &MockServiceListTodoTasksCall{Call: call}
}

// MockServiceListTodoTasksCall wrap *gomock.Call
type MockServiceListTodoTasksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListTodoTasksCall) Return(arg0 []domain.Instance, arg1 int64, arg2 error) *MockServiceListTodoTasksCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListTodoTasksCall) Do(f func(context.Context, string, string, bool, int, int) ([]domain.Instance, int64, error)) *MockServiceListTodoTasksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListTodoTasksCall) DoAndReturn(f func(context.Context, string, string, bool, int, int) ([]domain.Instance, int64, error)) *MockServiceListTodoTasksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Pass mocks base method.
func (m *MockService) Pass(ctx context.Context, taskId int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pass", ctx, taskId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pass indicates an expected call of Pass.
func (mr *MockServiceMockRecorder) Pass(ctx, taskId, comment any) *MockServicePassCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pass", reflect.TypeOf((*MockService)(nil).Pass), ctx, taskId, comment)
	return &MockServicePassCall{Call: call}
}

// MockServicePassCall wrap *gomock.Call
type MockServicePassCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServicePassCall) Return(arg0 error) *MockServicePassCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServicePassCall) Do(f func(context.Context, int, string) error) *MockServicePassCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServicePassCall) DoAndReturn(f func(context.Context, int, string) error) *MockServicePassCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProcessSave mocks base method.
func (m *MockService) ProcessSave(ctx context.Context, process *model.Process) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSave", ctx, process)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessSave indicates an expected call of ProcessSave.
func (mr *MockServiceMockRecorder) ProcessSave(ctx, process any) *MockServiceProcessSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSave", reflect.TypeOf((*MockService)(nil).ProcessSave), ctx, process)
	return &MockServiceProcessSaveCall{Call: call}
}

// MockServiceProcessSaveCall wrap *gomock.Call
type MockServiceProcessSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceProcessSaveCall) Return(arg0 int, arg1 error) *MockServiceProcessSaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceProcessSaveCall) Do(f func(context.Context, *model.Process) (int, error)) *MockServiceProcessSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceProcessSaveCall) DoAndReturn(f func(context.Context, *model.Process) (int, error)) *MockServiceProcessSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TaskInfo mocks base method.
func (m *MockService) TaskInfo(ctx context.Context, taskId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskInfo", ctx, taskId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskInfo indicates an expected call of TaskInfo.
func (mr *MockServiceMockRecorder) TaskInfo(ctx, taskId any) *MockServiceTaskInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskInfo", reflect.TypeOf((*MockService)(nil).TaskInfo), ctx, taskId)
	return &MockServiceTaskInfoCall{Call: call}
}

// MockServiceTaskInfoCall wrap *gomock.Call
type MockServiceTaskInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTaskInfoCall) Return(arg0 model.Task, arg1 error) *MockServiceTaskInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTaskInfoCall) Do(f func(context.Context, int) (model.Task, error)) *MockServiceTaskInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTaskInfoCall) DoAndReturn(f func(context.Context, int) (model.Task, error)) *MockServiceTaskInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TaskRecord mocks base method.
func (m *MockService) TaskRecord(ctx context.Context, processInstId, offset, limit int) ([]model.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskRecord", ctx, processInstId, offset, limit)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TaskRecord indicates an expected call of TaskRecord.
func (mr *MockServiceMockRecorder) TaskRecord(ctx, processInstId, offset, limit any) *MockServiceTaskRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskRecord", reflect.TypeOf((*MockService)(nil).TaskRecord), ctx, processInstId, offset, limit)
	return &MockServiceTaskRecordCall{Call: call}
}

// MockServiceTaskRecordCall wrap *gomock.Call
type MockServiceTaskRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTaskRecordCall) Return(arg0 []model.Task, arg1 int64, arg2 error) *MockServiceTaskRecordCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTaskRecordCall) Do(f func(context.Context, int, int, int) ([]model.Task, int64, error)) *MockServiceTaskRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTaskRecordCall) DoAndReturn(f func(context.Context, int, int, int) ([]model.Task, int64, error)) *MockServiceTaskRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Transfer mocks base method.
func (m *MockService) Transfer(ctx context.Context, taskId int, userIds []string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, taskId, userIds)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockServiceMockRecorder) Transfer(ctx, taskId, userIds any) *MockServiceTransferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockService)(nil).Transfer), ctx, taskId, userIds)
	return &MockServiceTransferCall{Call: call}
}

// MockServiceTransferCall wrap *gomock.Call
type MockServiceTransferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceTransferCall) Return(arg0 []model.Task, arg1 error) *MockServiceTransferCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceTransferCall) Do(f func(context.Context, int, []string) ([]model.Task, error)) *MockServiceTransferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceTransferCall) DoAndReturn(f func(context.Context, int, []string) ([]model.Task, error)) *MockServiceTransferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateIsFinishedByPreNodeId mocks base method.
func (m *MockService) UpdateIsFinishedByPreNodeId(ctx context.Context, processInstId int, nodeId string, status int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsFinishedByPreNodeId", ctx, processInstId, nodeId, status, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsFinishedByPreNodeId indicates an expected call of UpdateIsFinishedByPreNodeId.
func (mr *MockServiceMockRecorder) UpdateIsFinishedByPreNodeId(ctx, processInstId, nodeId, status, comment any) *MockServiceUpdateIsFinishedByPreNodeIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsFinishedByPreNodeId", reflect.TypeOf((*MockService)(nil).UpdateIsFinishedByPreNodeId), ctx, processInstId, nodeId, status, comment)
	return &MockServiceUpdateIsFinishedByPreNodeIdCall{Call: call}
}

// MockServiceUpdateIsFinishedByPreNodeIdCall wrap *gomock.Call
type MockServiceUpdateIsFinishedByPreNodeIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateIsFinishedByPreNodeIdCall) Return(arg0 error) *MockServiceUpdateIsFinishedByPreNodeIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateIsFinishedByPreNodeIdCall) Do(f func(context.Context, int, string, int, string) error) *MockServiceUpdateIsFinishedByPreNodeIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateIsFinishedByPreNodeIdCall) DoAndReturn(f func(context.Context, int, string, int, string) error) *MockServiceUpdateIsFinishedByPreNodeIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTaskPrevNodeID mocks base method.
func (m *MockService) UpdateTaskPrevNodeID(ctx context.Context, taskId int, prevNodeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskPrevNodeID", ctx, taskId, prevNodeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskPrevNodeID indicates an expected call of UpdateTaskPrevNodeID.
func (mr *MockServiceMockRecorder) UpdateTaskPrevNodeID(ctx, taskId, prevNodeId any) *MockServiceUpdateTaskPrevNodeIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskPrevNodeID", reflect.TypeOf((*MockService)(nil).UpdateTaskPrevNodeID), ctx, taskId, prevNodeId)
	return &MockServiceUpdateTaskPrevNodeIDCall{Call: call}
}

// MockServiceUpdateTaskPrevNodeIDCall wrap *gomock.Call
type MockServiceUpdateTaskPrevNodeIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateTaskPrevNodeIDCall) Return(arg0 error) *MockServiceUpdateTaskPrevNodeIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateTaskPrevNodeIDCall) Do(f func(context.Context, int, string) error) *MockServiceUpdateTaskPrevNodeIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateTaskPrevNodeIDCall) DoAndReturn(f func(context.Context, int, string) error) *MockServiceUpdateTaskPrevNodeIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Upstream mocks base method.
func (m *MockService) Upstream(ctx context.Context, taskId int) ([]model.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upstream", ctx, taskId)
	ret0, _ := ret[0].([]model.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upstream indicates an expected call of Upstream.
func (mr *MockServiceMockRecorder) Upstream(ctx, taskId any) *MockServiceUpstreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upstream", reflect.TypeOf((*MockService)(nil).Upstream), ctx, taskId)
	return &MockServiceUpstreamCall{Call: call}
}

// MockServiceUpstreamCall wrap *gomock.Call
type MockServiceUpstreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpstreamCall) Return(arg0 []model.Node, arg1 error) *MockServiceUpstreamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpstreamCall) Do(f func(context.Context, int) ([]model.Node, error)) *MockServiceUpstreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpstreamCall) DoAndReturn(f func(context.Context, int) ([]model.Node, error)) *MockServiceUpstreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
