// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package task

import (
	"context"
	"github.com/Bunny3th/easy-workflow/workflow/engine"
	"github.com/Duke1616/ecmdb/internal/task/event"
	"github.com/Duke1616/ecmdb/internal/task/register"
	"github.com/Duke1616/ecmdb/internal/task/web"
	"github.com/Duke1616/ecmdb/internal/workflow"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"gorm.io/gorm"
	"log"
	"sync"
)

// Injectors from wire.go:

func InitModule(db *gorm.DB, q mq.MQ, workflowModule *workflow.Module) (*Module, error) {
	handler := InitEasyFlowOnce(db)
	service := workflowModule.Svc
	taskEventConsumer := InitConsumer(q, service)
	module := &Module{
		Hdl: handler,
		c:   taskEventConsumer,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler)

var flowOnce = sync.Once{}

func InitEasyFlowOnce(db *gorm.DB) *web.Handler {
	flowOnce.Do(func() {
		engine.DB = db
		if err := engine.DatabaseInitialize(); err != nil {
			log.Fatalln("easy workflow 初始化数据表失败，错误:", err)
		}
		engine.IgnoreEventError = false
		engine.RegisterEvents(&register.EasyFlowEvent{})
		log.Println("========================== easy workflow 启动成功 ========================== ")
	})

	return web.NewHandler()
}

func InitConsumer(q mq.MQ, workflowSvc workflow.Service) *event.TaskEventConsumer {
	consumer, err := event.NewTaskEventConsumer(q, workflowSvc)
	if err != nil {
		return nil
	}

	consumer.Start(context.Background())
	return consumer
}
