// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/event/service/strategy/base.go
//
// Generated by this command:
//
//	mockgen -source=./internal/event/service/strategy/base.go -package=strategymocks -destination=./internal/event/service/mocks/strategy.mock.go -typed Service
//

// Package strategymocks is a generated GoMock package.
package strategymocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/Bunny3th/easy-workflow/workflow/model"
	strategy "github.com/Duke1616/ecmdb/internal/event/service/strategy"
	order "github.com/Duke1616/ecmdb/internal/order"
	notification "github.com/Duke1616/ecmdb/internal/pkg/notification"
	user "github.com/Duke1616/ecmdb/internal/user"
	workflow "github.com/Duke1616/ecmdb/internal/workflow"
	easyflow "github.com/Duke1616/ecmdb/internal/workflow/pkg/easyflow"
	resolve "github.com/Duke1616/ecmdb/pkg/resolve"
	elog "github.com/gotomicro/ego/core/elog"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// EnrichTargets mocks base method.
func (m *MockService) EnrichTargets(info strategy.Info, assignees []easyflow.Assignee) []resolve.Target {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrichTargets", info, assignees)
	ret0, _ := ret[0].([]resolve.Target)
	return ret0
}

// EnrichTargets indicates an expected call of EnrichTargets.
func (mr *MockServiceMockRecorder) EnrichTargets(info, assignees any) *MockServiceEnrichTargetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichTargets", reflect.TypeOf((*MockService)(nil).EnrichTargets), info, assignees)
	return &MockServiceEnrichTargetsCall{Call: call}
}

// MockServiceEnrichTargetsCall wrap *gomock.Call
type MockServiceEnrichTargetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEnrichTargetsCall) Return(arg0 []resolve.Target) *MockServiceEnrichTargetsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEnrichTargetsCall) Do(f func(strategy.Info, []easyflow.Assignee) []resolve.Target) *MockServiceEnrichTargetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEnrichTargetsCall) DoAndReturn(f func(strategy.Info, []easyflow.Assignee) []resolve.Target) *MockServiceEnrichTargetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchRequiredData mocks base method.
func (m *MockService) FetchRequiredData(ctx context.Context, info strategy.Info, nodes []easyflow.Node) (*strategy.NotificationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRequiredData", ctx, info, nodes)
	ret0, _ := ret[0].(*strategy.NotificationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRequiredData indicates an expected call of FetchRequiredData.
func (mr *MockServiceMockRecorder) FetchRequiredData(ctx, info, nodes any) *MockServiceFetchRequiredDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRequiredData", reflect.TypeOf((*MockService)(nil).FetchRequiredData), ctx, info, nodes)
	return &MockServiceFetchRequiredDataCall{Call: call}
}

// MockServiceFetchRequiredDataCall wrap *gomock.Call
type MockServiceFetchRequiredDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFetchRequiredDataCall) Return(arg0 *strategy.NotificationData, arg1 error) *MockServiceFetchRequiredDataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFetchRequiredDataCall) Do(f func(context.Context, strategy.Info, []easyflow.Node) (*strategy.NotificationData, error)) *MockServiceFetchRequiredDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFetchRequiredDataCall) DoAndReturn(f func(context.Context, strategy.Info, []easyflow.Node) (*strategy.NotificationData, error)) *MockServiceFetchRequiredDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FetchTasksWithRetry mocks base method.
func (m *MockService) FetchTasksWithRetry(ctx context.Context, info strategy.Info) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTasksWithRetry", ctx, info)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTasksWithRetry indicates an expected call of FetchTasksWithRetry.
func (mr *MockServiceMockRecorder) FetchTasksWithRetry(ctx, info any) *MockServiceFetchTasksWithRetryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTasksWithRetry", reflect.TypeOf((*MockService)(nil).FetchTasksWithRetry), ctx, info)
	return &MockServiceFetchTasksWithRetryCall{Call: call}
}

// MockServiceFetchTasksWithRetryCall wrap *gomock.Call
type MockServiceFetchTasksWithRetryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFetchTasksWithRetryCall) Return(arg0 []model.Task, arg1 error) *MockServiceFetchTasksWithRetryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFetchTasksWithRetryCall) Do(f func(context.Context, strategy.Info) ([]model.Task, error)) *MockServiceFetchTasksWithRetryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFetchTasksWithRetryCall) DoAndReturn(f func(context.Context, strategy.Info) ([]model.Task, error)) *MockServiceFetchTasksWithRetryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTaskForms mocks base method.
func (m *MockService) FindTaskForms(ctx context.Context, orderId int64) ([]order.FormValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskForms", ctx, orderId)
	ret0, _ := ret[0].([]order.FormValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskForms indicates an expected call of FindTaskForms.
func (mr *MockServiceMockRecorder) FindTaskForms(ctx, orderId any) *MockServiceFindTaskFormsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskForms", reflect.TypeOf((*MockService)(nil).FindTaskForms), ctx, orderId)
	return &MockServiceFindTaskFormsCall{Call: call}
}

// MockServiceFindTaskFormsCall wrap *gomock.Call
type MockServiceFindTaskFormsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindTaskFormsCall) Return(arg0 []order.FormValue, arg1 error) *MockServiceFindTaskFormsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindTaskFormsCall) Do(f func(context.Context, int64) ([]order.FormValue, error)) *MockServiceFindTaskFormsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindTaskFormsCall) DoAndReturn(f func(context.Context, int64) ([]order.FormValue, error)) *MockServiceFindTaskFormsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNodeProperty mocks base method.
func (m *MockService) GetNodeProperty(info strategy.Info, nodeID string) ([]easyflow.Node, any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeProperty", info, nodeID)
	ret0, _ := ret[0].([]easyflow.Node)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNodeProperty indicates an expected call of GetNodeProperty.
func (mr *MockServiceMockRecorder) GetNodeProperty(info, nodeID any) *MockServiceGetNodePropertyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeProperty", reflect.TypeOf((*MockService)(nil).GetNodeProperty), info, nodeID)
	return &MockServiceGetNodePropertyCall{Call: call}
}

// MockServiceGetNodePropertyCall wrap *gomock.Call
type MockServiceGetNodePropertyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetNodePropertyCall) Return(arg0 []easyflow.Node, arg1 any, arg2 error) *MockServiceGetNodePropertyCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetNodePropertyCall) Do(f func(strategy.Info, string) ([]easyflow.Node, any, error)) *MockServiceGetNodePropertyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetNodePropertyCall) DoAndReturn(f func(strategy.Info, string) ([]easyflow.Node, any, error)) *MockServiceGetNodePropertyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsGlobalNotify mocks base method.
func (m *MockService) IsGlobalNotify(wf workflow.Workflow) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGlobalNotify", wf)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsGlobalNotify indicates an expected call of IsGlobalNotify.
func (mr *MockServiceMockRecorder) IsGlobalNotify(wf any) *MockServiceIsGlobalNotifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGlobalNotify", reflect.TypeOf((*MockService)(nil).IsGlobalNotify), wf)
	return &MockServiceIsGlobalNotifyCall{Call: call}
}

// MockServiceIsGlobalNotifyCall wrap *gomock.Call
type MockServiceIsGlobalNotifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceIsGlobalNotifyCall) Return(arg0 bool) *MockServiceIsGlobalNotifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceIsGlobalNotifyCall) Do(f func(workflow.Workflow) bool) *MockServiceIsGlobalNotifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceIsGlobalNotifyCall) DoAndReturn(f func(workflow.Workflow) bool) *MockServiceIsGlobalNotifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logger mocks base method.
func (m *MockService) Logger() *elog.Component {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*elog.Component)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockServiceMockRecorder) Logger() *MockServiceLoggerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockService)(nil).Logger))
	return &MockServiceLoggerCall{Call: call}
}

// MockServiceLoggerCall wrap *gomock.Call
type MockServiceLoggerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceLoggerCall) Return(arg0 *elog.Component) *MockServiceLoggerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceLoggerCall) Do(f func() *elog.Component) *MockServiceLoggerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceLoggerCall) DoAndReturn(f func() *elog.Component) *MockServiceLoggerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PassTask mocks base method.
func (m *MockService) PassTask(ctx context.Context, taskId int, remark string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PassTask", ctx, taskId, remark)
	ret0, _ := ret[0].(error)
	return ret0
}

// PassTask indicates an expected call of PassTask.
func (mr *MockServiceMockRecorder) PassTask(ctx, taskId, remark any) *MockServicePassTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PassTask", reflect.TypeOf((*MockService)(nil).PassTask), ctx, taskId, remark)
	return &MockServicePassTaskCall{Call: call}
}

// MockServicePassTaskCall wrap *gomock.Call
type MockServicePassTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServicePassTaskCall) Return(arg0 error) *MockServicePassTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServicePassTaskCall) Do(f func(context.Context, int, string) error) *MockServicePassTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServicePassTaskCall) DoAndReturn(f func(context.Context, int, string) error) *MockServicePassTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrepareCommonFields mocks base method.
func (m *MockService) PrepareCommonFields(info strategy.Info, data *strategy.NotificationData) []notification.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareCommonFields", info, data)
	ret0, _ := ret[0].([]notification.Field)
	return ret0
}

// PrepareCommonFields indicates an expected call of PrepareCommonFields.
func (mr *MockServiceMockRecorder) PrepareCommonFields(info, data any) *MockServicePrepareCommonFieldsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareCommonFields", reflect.TypeOf((*MockService)(nil).PrepareCommonFields), info, data)
	return &MockServicePrepareCommonFieldsCall{Call: call}
}

// MockServicePrepareCommonFieldsCall wrap *gomock.Call
type MockServicePrepareCommonFieldsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServicePrepareCommonFieldsCall) Return(arg0 []notification.Field) *MockServicePrepareCommonFieldsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServicePrepareCommonFieldsCall) Do(f func(strategy.Info, *strategy.NotificationData) []notification.Field) *MockServicePrepareCommonFieldsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServicePrepareCommonFieldsCall) DoAndReturn(f func(strategy.Info, *strategy.NotificationData) []notification.Field) *MockServicePrepareCommonFieldsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveAssignees mocks base method.
func (m *MockService) ResolveAssignees(ctx context.Context, info *strategy.Info, assignees []easyflow.Assignee) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAssignees", ctx, info, assignees)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAssignees indicates an expected call of ResolveAssignees.
func (mr *MockServiceMockRecorder) ResolveAssignees(ctx, info, assignees any) *MockServiceResolveAssigneesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAssignees", reflect.TypeOf((*MockService)(nil).ResolveAssignees), ctx, info, assignees)
	return &MockServiceResolveAssigneesCall{Call: call}
}

// MockServiceResolveAssigneesCall wrap *gomock.Call
type MockServiceResolveAssigneesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceResolveAssigneesCall) Return(arg0 []user.User, arg1 error) *MockServiceResolveAssigneesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceResolveAssigneesCall) Do(f func(context.Context, *strategy.Info, []easyflow.Assignee) ([]user.User, error)) *MockServiceResolveAssigneesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceResolveAssigneesCall) DoAndReturn(f func(context.Context, *strategy.Info, []easyflow.Assignee) ([]user.User, error)) *MockServiceResolveAssigneesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SafeGo mocks base method.
func (m *MockService) SafeGo(ctx context.Context, timeout time.Duration, fn func(context.Context)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SafeGo", ctx, timeout, fn)
}

// SafeGo indicates an expected call of SafeGo.
func (mr *MockServiceMockRecorder) SafeGo(ctx, timeout, fn any) *MockServiceSafeGoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SafeGo", reflect.TypeOf((*MockService)(nil).SafeGo), ctx, timeout, fn)
	return &MockServiceSafeGoCall{Call: call}
}

// MockServiceSafeGoCall wrap *gomock.Call
type MockServiceSafeGoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSafeGoCall) Return() *MockServiceSafeGoCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSafeGoCall) Do(f func(context.Context, time.Duration, func(context.Context))) *MockServiceSafeGoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSafeGoCall) DoAndReturn(f func(context.Context, time.Duration, func(context.Context))) *MockServiceSafeGoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
