// Code generated by MockGen. DO NOT EDIT.
// Source: ./importer.go
//
// Generated by this command:
//
//	mockgen -source=./importer.go -destination=./mocks/importer.mock.go -package=pluginmocks -typed ISchemaImporter
//

// Package pluginmocks is a generated GoMock package.
package pluginmocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Duke1616/ecmdb/pkg/plugin/types"
	gomock "go.uber.org/mock/gomock"
)

// MockISchemaImporter is a mock of ISchemaImporter interface.
type MockISchemaImporter struct {
	ctrl     *gomock.Controller
	recorder *MockISchemaImporterMockRecorder
	isgomock struct{}
}

// MockISchemaImporterMockRecorder is the mock recorder for MockISchemaImporter.
type MockISchemaImporterMockRecorder struct {
	mock *MockISchemaImporter
}

// NewMockISchemaImporter creates a new mock instance.
func NewMockISchemaImporter(ctrl *gomock.Controller) *MockISchemaImporter {
	mock := &MockISchemaImporter{ctrl: ctrl}
	mock.recorder = &MockISchemaImporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISchemaImporter) EXPECT() *MockISchemaImporterMockRecorder {
	return m.recorder
}

// ImportSchema mocks base method.
func (m *MockISchemaImporter) ImportSchema(ctx context.Context, schema types.Schema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportSchema", ctx, schema)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportSchema indicates an expected call of ImportSchema.
func (mr *MockISchemaImporterMockRecorder) ImportSchema(ctx, schema any) *MockISchemaImporterImportSchemaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportSchema", reflect.TypeOf((*MockISchemaImporter)(nil).ImportSchema), ctx, schema)
	return &MockISchemaImporterImportSchemaCall{Call: call}
}

// MockISchemaImporterImportSchemaCall wrap *gomock.Call
type MockISchemaImporterImportSchemaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISchemaImporterImportSchemaCall) Return(arg0 error) *MockISchemaImporterImportSchemaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISchemaImporterImportSchemaCall) Do(f func(context.Context, types.Schema) error) *MockISchemaImporterImportSchemaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISchemaImporterImportSchemaCall) DoAndReturn(f func(context.Context, types.Schema) error) *MockISchemaImporterImportSchemaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
