// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=./mocks/service.mock.go -package=pluginmocks -typed Service
//

// Package pluginmocks is a generated GoMock package.
package pluginmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/domain"
	plugin "github.com/Duke1616/ecmdb/pkg/plugin"
	types "github.com/Duke1616/ecmdb/pkg/plugin/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DeleteBinding mocks base method.
func (m *MockService) DeleteBinding(ctx context.Context, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinding", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinding indicates an expected call of DeleteBinding.
func (mr *MockServiceMockRecorder) DeleteBinding(ctx, uid any) *MockServiceDeleteBindingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinding", reflect.TypeOf((*MockService)(nil).DeleteBinding), ctx, uid)
	return &MockServiceDeleteBindingCall{Call: call}
}

// MockServiceDeleteBindingCall wrap *gomock.Call
type MockServiceDeleteBindingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteBindingCall) Return(arg0 error) *MockServiceDeleteBindingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteBindingCall) Do(f func(context.Context, string) error) *MockServiceDeleteBindingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteBindingCall) DoAndReturn(f func(context.Context, string) error) *MockServiceDeleteBindingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActionRuntime mocks base method.
func (m *MockService) GetActionRuntime(ctx context.Context, pluginID, action string) (domain.Plugin, types.ActionSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionRuntime", ctx, pluginID, action)
	ret0, _ := ret[0].(domain.Plugin)
	ret1, _ := ret[1].(types.ActionSpec)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActionRuntime indicates an expected call of GetActionRuntime.
func (mr *MockServiceMockRecorder) GetActionRuntime(ctx, pluginID, action any) *MockServiceGetActionRuntimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionRuntime", reflect.TypeOf((*MockService)(nil).GetActionRuntime), ctx, pluginID, action)
	return &MockServiceGetActionRuntimeCall{Call: call}
}

// MockServiceGetActionRuntimeCall wrap *gomock.Call
type MockServiceGetActionRuntimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetActionRuntimeCall) Return(arg0 domain.Plugin, arg1 types.ActionSpec, arg2 error) *MockServiceGetActionRuntimeCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetActionRuntimeCall) Do(f func(context.Context, string, string) (domain.Plugin, types.ActionSpec, error)) *MockServiceGetActionRuntimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetActionRuntimeCall) DoAndReturn(f func(context.Context, string, string) (domain.Plugin, types.ActionSpec, error)) *MockServiceGetActionRuntimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDefaultDefinition mocks base method.
func (m *MockService) GetDefaultDefinition(ctx context.Context, pluginID string) (plugin.Definition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultDefinition", ctx, pluginID)
	ret0, _ := ret[0].(plugin.Definition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultDefinition indicates an expected call of GetDefaultDefinition.
func (mr *MockServiceMockRecorder) GetDefaultDefinition(ctx, pluginID any) *MockServiceGetDefaultDefinitionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultDefinition", reflect.TypeOf((*MockService)(nil).GetDefaultDefinition), ctx, pluginID)
	return &MockServiceGetDefaultDefinitionCall{Call: call}
}

// MockServiceGetDefaultDefinitionCall wrap *gomock.Call
type MockServiceGetDefaultDefinitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetDefaultDefinitionCall) Return(arg0 plugin.Definition, arg1 error) *MockServiceGetDefaultDefinitionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetDefaultDefinitionCall) Do(f func(context.Context, string) (plugin.Definition, error)) *MockServiceGetDefaultDefinitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetDefaultDefinitionCall) DoAndReturn(f func(context.Context, string) (plugin.Definition, error)) *MockServiceGetDefaultDefinitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPluginDetail mocks base method.
func (m *MockService) GetPluginDetail(ctx context.Context, uid string) (domain.PluginDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPluginDetail", ctx, uid)
	ret0, _ := ret[0].(domain.PluginDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPluginDetail indicates an expected call of GetPluginDetail.
func (mr *MockServiceMockRecorder) GetPluginDetail(ctx, uid any) *MockServiceGetPluginDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPluginDetail", reflect.TypeOf((*MockService)(nil).GetPluginDetail), ctx, uid)
	return &MockServiceGetPluginDetailCall{Call: call}
}

// MockServiceGetPluginDetailCall wrap *gomock.Call
type MockServiceGetPluginDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetPluginDetailCall) Return(arg0 domain.PluginDetail, arg1 error) *MockServiceGetPluginDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetPluginDetailCall) Do(f func(context.Context, string) (domain.PluginDetail, error)) *MockServiceGetPluginDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetPluginDetailCall) DoAndReturn(f func(context.Context, string) (domain.PluginDetail, error)) *MockServiceGetPluginDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImportDefinition mocks base method.
func (m *MockService) ImportDefinition(ctx context.Context, def plugin.Definition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportDefinition", ctx, def)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportDefinition indicates an expected call of ImportDefinition.
func (mr *MockServiceMockRecorder) ImportDefinition(ctx, def any) *MockServiceImportDefinitionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportDefinition", reflect.TypeOf((*MockService)(nil).ImportDefinition), ctx, def)
	return &MockServiceImportDefinitionCall{Call: call}
}

// MockServiceImportDefinitionCall wrap *gomock.Call
type MockServiceImportDefinitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceImportDefinitionCall) Return(arg0 error) *MockServiceImportDefinitionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceImportDefinitionCall) Do(f func(context.Context, plugin.Definition) error) *MockServiceImportDefinitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceImportDefinitionCall) DoAndReturn(f func(context.Context, plugin.Definition) error) *MockServiceImportDefinitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListEnums mocks base method.
func (m *MockService) ListEnums(ctx context.Context) (domain.PluginManagementEnums, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnums", ctx)
	ret0, _ := ret[0].(domain.PluginManagementEnums)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnums indicates an expected call of ListEnums.
func (mr *MockServiceMockRecorder) ListEnums(ctx any) *MockServiceListEnumsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnums", reflect.TypeOf((*MockService)(nil).ListEnums), ctx)
	return &MockServiceListEnumsCall{Call: call}
}

// MockServiceListEnumsCall wrap *gomock.Call
type MockServiceListEnumsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListEnumsCall) Return(arg0 domain.PluginManagementEnums, arg1 error) *MockServiceListEnumsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListEnumsCall) Do(f func(context.Context) (domain.PluginManagementEnums, error)) *MockServiceListEnumsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListEnumsCall) DoAndReturn(f func(context.Context) (domain.PluginManagementEnums, error)) *MockServiceListEnumsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListPlugins mocks base method.
func (m *MockService) ListPlugins(ctx context.Context) ([]domain.PluginListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlugins", ctx)
	ret0, _ := ret[0].([]domain.PluginListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlugins indicates an expected call of ListPlugins.
func (mr *MockServiceMockRecorder) ListPlugins(ctx any) *MockServiceListPluginsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlugins", reflect.TypeOf((*MockService)(nil).ListPlugins), ctx)
	return &MockServiceListPluginsCall{Call: call}
}

// MockServiceListPluginsCall wrap *gomock.Call
type MockServiceListPluginsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListPluginsCall) Return(arg0 []domain.PluginListItem, arg1 error) *MockServiceListPluginsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListPluginsCall) Do(f func(context.Context) ([]domain.PluginListItem, error)) *MockServiceListPluginsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListPluginsCall) DoAndReturn(f func(context.Context) ([]domain.PluginListItem, error)) *MockServiceListPluginsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResourceActionsBatch mocks base method.
func (m *MockService) ListResourceActionsBatch(ctx context.Context, resourceIDs []int64) ([]types.ResourceActions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceActionsBatch", ctx, resourceIDs)
	ret0, _ := ret[0].([]types.ResourceActions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourceActionsBatch indicates an expected call of ListResourceActionsBatch.
func (mr *MockServiceMockRecorder) ListResourceActionsBatch(ctx, resourceIDs any) *MockServiceListResourceActionsBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceActionsBatch", reflect.TypeOf((*MockService)(nil).ListResourceActionsBatch), ctx, resourceIDs)
	return &MockServiceListResourceActionsBatchCall{Call: call}
}

// MockServiceListResourceActionsBatchCall wrap *gomock.Call
type MockServiceListResourceActionsBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListResourceActionsBatchCall) Return(arg0 []types.ResourceActions, arg1 error) *MockServiceListResourceActionsBatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListResourceActionsBatchCall) Do(f func(context.Context, []int64) ([]types.ResourceActions, error)) *MockServiceListResourceActionsBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListResourceActionsBatchCall) DoAndReturn(f func(context.Context, []int64) ([]types.ResourceActions, error)) *MockServiceListResourceActionsBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveAction mocks base method.
func (m *MockService) ResolveAction(ctx context.Context, req types.ResolveRequest) (types.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAction", ctx, req)
	ret0, _ := ret[0].(types.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAction indicates an expected call of ResolveAction.
func (mr *MockServiceMockRecorder) ResolveAction(ctx, req any) *MockServiceResolveActionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAction", reflect.TypeOf((*MockService)(nil).ResolveAction), ctx, req)
	return &MockServiceResolveActionCall{Call: call}
}

// MockServiceResolveActionCall wrap *gomock.Call
type MockServiceResolveActionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceResolveActionCall) Return(arg0 types.ResolveResult, arg1 error) *MockServiceResolveActionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceResolveActionCall) Do(f func(context.Context, types.ResolveRequest) (types.ResolveResult, error)) *MockServiceResolveActionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceResolveActionCall) DoAndReturn(f func(context.Context, types.ResolveRequest) (types.ResolveResult, error)) *MockServiceResolveActionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveActionContext mocks base method.
func (m *MockService) ResolveActionContext(ctx context.Context, req types.ResolveRequest) (types.ActionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveActionContext", ctx, req)
	ret0, _ := ret[0].(types.ActionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveActionContext indicates an expected call of ResolveActionContext.
func (mr *MockServiceMockRecorder) ResolveActionContext(ctx, req any) *MockServiceResolveActionContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveActionContext", reflect.TypeOf((*MockService)(nil).ResolveActionContext), ctx, req)
	return &MockServiceResolveActionContextCall{Call: call}
}

// MockServiceResolveActionContextCall wrap *gomock.Call
type MockServiceResolveActionContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceResolveActionContextCall) Return(arg0 types.ActionContext, arg1 error) *MockServiceResolveActionContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceResolveActionContextCall) Do(f func(context.Context, types.ResolveRequest) (types.ActionContext, error)) *MockServiceResolveActionContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceResolveActionContextCall) DoAndReturn(f func(context.Context, types.ResolveRequest) (types.ActionContext, error)) *MockServiceResolveActionContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveBindings mocks base method.
func (m *MockService) SaveBindings(ctx context.Context, req domain.SavePluginBindings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBindings", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBindings indicates an expected call of SaveBindings.
func (mr *MockServiceMockRecorder) SaveBindings(ctx, req any) *MockServiceSaveBindingsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBindings", reflect.TypeOf((*MockService)(nil).SaveBindings), ctx, req)
	return &MockServiceSaveBindingsCall{Call: call}
}

// MockServiceSaveBindingsCall wrap *gomock.Call
type MockServiceSaveBindingsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceSaveBindingsCall) Return(arg0 error) *MockServiceSaveBindingsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceSaveBindingsCall) Do(f func(context.Context, domain.SavePluginBindings) error) *MockServiceSaveBindingsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceSaveBindingsCall) DoAndReturn(f func(context.Context, domain.SavePluginBindings) error) *MockServiceSaveBindingsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ToggleBindingStatus mocks base method.
func (m *MockService) ToggleBindingStatus(ctx context.Context, uid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleBindingStatus", ctx, uid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleBindingStatus indicates an expected call of ToggleBindingStatus.
func (mr *MockServiceMockRecorder) ToggleBindingStatus(ctx, uid any) *MockServiceToggleBindingStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleBindingStatus", reflect.TypeOf((*MockService)(nil).ToggleBindingStatus), ctx, uid)
	return &MockServiceToggleBindingStatusCall{Call: call}
}

// MockServiceToggleBindingStatusCall wrap *gomock.Call
type MockServiceToggleBindingStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceToggleBindingStatusCall) Return(arg0 bool, arg1 error) *MockServiceToggleBindingStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceToggleBindingStatusCall) Do(f func(context.Context, string) (bool, error)) *MockServiceToggleBindingStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceToggleBindingStatusCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockServiceToggleBindingStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
