// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/Duke1616/ecmdb/internal/policy"
	"github.com/Duke1616/ecmdb/internal/user/internal/repository"
	"github.com/Duke1616/ecmdb/internal/user/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/user/internal/service"
	"github.com/Duke1616/ecmdb/internal/user/internal/web"
	"github.com/Duke1616/ecmdb/internal/user/ldapx"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo, ldapConfig ldapx.Config, policyModule *policy.Module) (*Module, error) {
	userDAO := dao.NewUserDao(db)
	userRepository := repository.NewResourceRepository(userDAO)
	serviceService := service.NewService(userRepository)
	ldapService := service.NewLdapService(ldapConfig)
	service2 := policyModule.Svc
	handler := web.NewHandler(serviceService, ldapService, service2)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewLdapService, service.NewService, repository.NewResourceRepository, dao.NewUserDao, web.NewHandler)
