// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/Duke1616/ecmdb/internal/user/internal/service"
	"github.com/Duke1616/ecmdb/internal/user/internal/web"
	"github.com/Duke1616/ecmdb/internal/user/ldapx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(ldapConfig ldapx.Config) (*Module, error) {
	ldapService := service.NewLdapService(ldapConfig)
	handler := web.NewHandler(ldapService)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(service.NewLdapService, web.NewHandler)
