// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -package=ordermocks -destination=../../mocks/order.mock.go -typed Service
//

// Package ordermocks is a generated GoMock package.
package ordermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/ecmdb/internal/order/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateBizOrder mocks base method.
func (m *MockService) CreateBizOrder(ctx context.Context, order domain.Order) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBizOrder", ctx, order)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBizOrder indicates an expected call of CreateBizOrder.
func (mr *MockServiceMockRecorder) CreateBizOrder(ctx, order any) *MockServiceCreateBizOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBizOrder", reflect.TypeOf((*MockService)(nil).CreateBizOrder), ctx, order)
	return &MockServiceCreateBizOrderCall{Call: call}
}

// MockServiceCreateBizOrderCall wrap *gomock.Call
type MockServiceCreateBizOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateBizOrderCall) Return(arg0 domain.Order, arg1 error) *MockServiceCreateBizOrderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateBizOrderCall) Do(f func(context.Context, domain.Order) (domain.Order, error)) *MockServiceCreateBizOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateBizOrderCall) DoAndReturn(f func(context.Context, domain.Order) (domain.Order, error)) *MockServiceCreateBizOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateOrder mocks base method.
func (m *MockService) CreateOrder(ctx context.Context, req domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockServiceMockRecorder) CreateOrder(ctx, req any) *MockServiceCreateOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockService)(nil).CreateOrder), ctx, req)
	return &MockServiceCreateOrderCall{Call: call}
}

// MockServiceCreateOrderCall wrap *gomock.Call
type MockServiceCreateOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateOrderCall) Return(arg0 error) *MockServiceCreateOrderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateOrderCall) Do(f func(context.Context, domain.Order) error) *MockServiceCreateOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateOrderCall) DoAndReturn(f func(context.Context, domain.Order) error) *MockServiceCreateOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTaskForm mocks base method.
func (m *MockService) CreateTaskForm(ctx context.Context, taskId int, orderId int64, fields []domain.FormValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskForm", ctx, taskId, orderId, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskForm indicates an expected call of CreateTaskForm.
func (mr *MockServiceMockRecorder) CreateTaskForm(ctx, taskId, orderId, fields any) *MockServiceCreateTaskFormCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskForm", reflect.TypeOf((*MockService)(nil).CreateTaskForm), ctx, taskId, orderId, fields)
	return &MockServiceCreateTaskFormCall{Call: call}
}

// MockServiceCreateTaskFormCall wrap *gomock.Call
type MockServiceCreateTaskFormCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateTaskFormCall) Return(arg0 error) *MockServiceCreateTaskFormCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateTaskFormCall) Do(f func(context.Context, int, int64, []domain.FormValue) error) *MockServiceCreateTaskFormCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateTaskFormCall) DoAndReturn(f func(context.Context, int, int64, []domain.FormValue) error) *MockServiceCreateTaskFormCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Detail mocks base method.
func (m *MockService) Detail(ctx context.Context, id int64) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockServiceMockRecorder) Detail(ctx, id any) *MockServiceDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockService)(nil).Detail), ctx, id)
	return &MockServiceDetailCall{Call: call}
}

// MockServiceDetailCall wrap *gomock.Call
type MockServiceDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDetailCall) Return(arg0 domain.Order, arg1 error) *MockServiceDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDetailCall) Do(f func(context.Context, int64) (domain.Order, error)) *MockServiceDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDetailCall) DoAndReturn(f func(context.Context, int64) (domain.Order, error)) *MockServiceDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetailByProcessInstId mocks base method.
func (m *MockService) DetailByProcessInstId(ctx context.Context, instanceId int) (domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailByProcessInstId", ctx, instanceId)
	ret0, _ := ret[0].(domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailByProcessInstId indicates an expected call of DetailByProcessInstId.
func (mr *MockServiceMockRecorder) DetailByProcessInstId(ctx, instanceId any) *MockServiceDetailByProcessInstIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailByProcessInstId", reflect.TypeOf((*MockService)(nil).DetailByProcessInstId), ctx, instanceId)
	return &MockServiceDetailByProcessInstIdCall{Call: call}
}

// MockServiceDetailByProcessInstIdCall wrap *gomock.Call
type MockServiceDetailByProcessInstIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDetailByProcessInstIdCall) Return(arg0 domain.Order, arg1 error) *MockServiceDetailByProcessInstIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDetailByProcessInstIdCall) Do(f func(context.Context, int) (domain.Order, error)) *MockServiceDetailByProcessInstIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDetailByProcessInstIdCall) DoAndReturn(f func(context.Context, int) (domain.Order, error)) *MockServiceDetailByProcessInstIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTaskFormsBatch mocks base method.
func (m *MockService) FindTaskFormsBatch(ctx context.Context, taskIds []int) (map[int][]domain.FormValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskFormsBatch", ctx, taskIds)
	ret0, _ := ret[0].(map[int][]domain.FormValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskFormsBatch indicates an expected call of FindTaskFormsBatch.
func (mr *MockServiceMockRecorder) FindTaskFormsBatch(ctx, taskIds any) *MockServiceFindTaskFormsBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskFormsBatch", reflect.TypeOf((*MockService)(nil).FindTaskFormsBatch), ctx, taskIds)
	return &MockServiceFindTaskFormsBatchCall{Call: call}
}

// MockServiceFindTaskFormsBatchCall wrap *gomock.Call
type MockServiceFindTaskFormsBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindTaskFormsBatchCall) Return(arg0 map[int][]domain.FormValue, arg1 error) *MockServiceFindTaskFormsBatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindTaskFormsBatchCall) Do(f func(context.Context, []int) (map[int][]domain.FormValue, error)) *MockServiceFindTaskFormsBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindTaskFormsBatchCall) DoAndReturn(f func(context.Context, []int) (map[int][]domain.FormValue, error)) *MockServiceFindTaskFormsBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindTaskFormsByOrderID mocks base method.
func (m *MockService) FindTaskFormsByOrderID(ctx context.Context, orderID int64) ([]domain.FormValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskFormsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]domain.FormValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskFormsByOrderID indicates an expected call of FindTaskFormsByOrderID.
func (mr *MockServiceMockRecorder) FindTaskFormsByOrderID(ctx, orderID any) *MockServiceFindTaskFormsByOrderIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskFormsByOrderID", reflect.TypeOf((*MockService)(nil).FindTaskFormsByOrderID), ctx, orderID)
	return &MockServiceFindTaskFormsByOrderIDCall{Call: call}
}

// MockServiceFindTaskFormsByOrderIDCall wrap *gomock.Call
type MockServiceFindTaskFormsByOrderIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindTaskFormsByOrderIDCall) Return(arg0 []domain.FormValue, arg1 error) *MockServiceFindTaskFormsByOrderIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindTaskFormsByOrderIDCall) Do(f func(context.Context, int64) ([]domain.FormValue, error)) *MockServiceFindTaskFormsByOrderIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindTaskFormsByOrderIDCall) DoAndReturn(f func(context.Context, int64) ([]domain.FormValue, error)) *MockServiceFindTaskFormsByOrderIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListHistoryOrder mocks base method.
func (m *MockService) ListHistoryOrder(ctx context.Context, userId string, offset, limit int64) ([]domain.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHistoryOrder", ctx, userId, offset, limit)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListHistoryOrder indicates an expected call of ListHistoryOrder.
func (mr *MockServiceMockRecorder) ListHistoryOrder(ctx, userId, offset, limit any) *MockServiceListHistoryOrderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHistoryOrder", reflect.TypeOf((*MockService)(nil).ListHistoryOrder), ctx, userId, offset, limit)
	return &MockServiceListHistoryOrderCall{Call: call}
}

// MockServiceListHistoryOrderCall wrap *gomock.Call
type MockServiceListHistoryOrderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListHistoryOrderCall) Return(arg0 []domain.Order, arg1 int64, arg2 error) *MockServiceListHistoryOrderCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListHistoryOrderCall) Do(f func(context.Context, string, int64, int64) ([]domain.Order, int64, error)) *MockServiceListHistoryOrderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListHistoryOrderCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.Order, int64, error)) *MockServiceListHistoryOrderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListOrderByProcessInstanceIds mocks base method.
func (m *MockService) ListOrderByProcessInstanceIds(ctx context.Context, instanceIds []int) ([]domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderByProcessInstanceIds", ctx, instanceIds)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrderByProcessInstanceIds indicates an expected call of ListOrderByProcessInstanceIds.
func (mr *MockServiceMockRecorder) ListOrderByProcessInstanceIds(ctx, instanceIds any) *MockServiceListOrderByProcessInstanceIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderByProcessInstanceIds", reflect.TypeOf((*MockService)(nil).ListOrderByProcessInstanceIds), ctx, instanceIds)
	return &MockServiceListOrderByProcessInstanceIdsCall{Call: call}
}

// MockServiceListOrderByProcessInstanceIdsCall wrap *gomock.Call
type MockServiceListOrderByProcessInstanceIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListOrderByProcessInstanceIdsCall) Return(arg0 []domain.Order, arg1 error) *MockServiceListOrderByProcessInstanceIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListOrderByProcessInstanceIdsCall) Do(f func(context.Context, []int) ([]domain.Order, error)) *MockServiceListOrderByProcessInstanceIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListOrderByProcessInstanceIdsCall) DoAndReturn(f func(context.Context, []int) ([]domain.Order, error)) *MockServiceListOrderByProcessInstanceIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListOrdersByUser mocks base method.
func (m *MockService) ListOrdersByUser(ctx context.Context, userId string, offset, limit int64) ([]domain.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByUser", ctx, userId, offset, limit)
	ret0, _ := ret[0].([]domain.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrdersByUser indicates an expected call of ListOrdersByUser.
func (mr *MockServiceMockRecorder) ListOrdersByUser(ctx, userId, offset, limit any) *MockServiceListOrdersByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByUser", reflect.TypeOf((*MockService)(nil).ListOrdersByUser), ctx, userId, offset, limit)
	return &MockServiceListOrdersByUserCall{Call: call}
}

// MockServiceListOrdersByUserCall wrap *gomock.Call
type MockServiceListOrdersByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListOrdersByUserCall) Return(arg0 []domain.Order, arg1 int64, arg2 error) *MockServiceListOrdersByUserCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListOrdersByUserCall) Do(f func(context.Context, string, int64, int64) ([]domain.Order, int64, error)) *MockServiceListOrdersByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListOrdersByUserCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.Order, int64, error)) *MockServiceListOrdersByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MergeOrderData mocks base method.
func (m *MockService) MergeOrderData(ctx context.Context, orderId int64, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeOrderData", ctx, orderId, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeOrderData indicates an expected call of MergeOrderData.
func (mr *MockServiceMockRecorder) MergeOrderData(ctx, orderId, data any) *MockServiceMergeOrderDataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeOrderData", reflect.TypeOf((*MockService)(nil).MergeOrderData), ctx, orderId, data)
	return &MockServiceMergeOrderDataCall{Call: call}
}

// MockServiceMergeOrderDataCall wrap *gomock.Call
type MockServiceMergeOrderDataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceMergeOrderDataCall) Return(arg0 error) *MockServiceMergeOrderDataCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceMergeOrderDataCall) Do(f func(context.Context, int64, map[string]any) error) *MockServiceMergeOrderDataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceMergeOrderDataCall) DoAndReturn(f func(context.Context, int64, map[string]any) error) *MockServiceMergeOrderDataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterProcessInstanceId mocks base method.
func (m *MockService) RegisterProcessInstanceId(ctx context.Context, id int64, instanceId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterProcessInstanceId", ctx, id, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterProcessInstanceId indicates an expected call of RegisterProcessInstanceId.
func (mr *MockServiceMockRecorder) RegisterProcessInstanceId(ctx, id, instanceId any) *MockServiceRegisterProcessInstanceIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProcessInstanceId", reflect.TypeOf((*MockService)(nil).RegisterProcessInstanceId), ctx, id, instanceId)
	return &MockServiceRegisterProcessInstanceIdCall{Call: call}
}

// MockServiceRegisterProcessInstanceIdCall wrap *gomock.Call
type MockServiceRegisterProcessInstanceIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceRegisterProcessInstanceIdCall) Return(arg0 error) *MockServiceRegisterProcessInstanceIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceRegisterProcessInstanceIdCall) Do(f func(context.Context, int64, int) error) *MockServiceRegisterProcessInstanceIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceRegisterProcessInstanceIdCall) DoAndReturn(f func(context.Context, int64, int) error) *MockServiceRegisterProcessInstanceIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStatusByInstanceId mocks base method.
func (m *MockService) UpdateStatusByInstanceId(ctx context.Context, instanceId int, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByInstanceId", ctx, instanceId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByInstanceId indicates an expected call of UpdateStatusByInstanceId.
func (mr *MockServiceMockRecorder) UpdateStatusByInstanceId(ctx, instanceId, status any) *MockServiceUpdateStatusByInstanceIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByInstanceId", reflect.TypeOf((*MockService)(nil).UpdateStatusByInstanceId), ctx, instanceId, status)
	return &MockServiceUpdateStatusByInstanceIdCall{Call: call}
}

// MockServiceUpdateStatusByInstanceIdCall wrap *gomock.Call
type MockServiceUpdateStatusByInstanceIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateStatusByInstanceIdCall) Return(arg0 error) *MockServiceUpdateStatusByInstanceIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateStatusByInstanceIdCall) Do(f func(context.Context, int, uint8) error) *MockServiceUpdateStatusByInstanceIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateStatusByInstanceIdCall) DoAndReturn(f func(context.Context, int, uint8) error) *MockServiceUpdateStatusByInstanceIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
