// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/Duke1616/ecmdb/internal/resource/internal/web"
)

// Injectors from wire.go:

func InitHandler(am *attribute.Module) (*web.Handler, error) {
	mongo := InitMongoDB()
	module, err := resource.InitModule(mongo, am)
	if err != nil {
		return nil, err
	}
	handler := module.Hdl
	return handler, nil
}
