// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package terminal

import (
	"github.com/Duke1616/ecmdb/internal/attribute"
	"github.com/Duke1616/ecmdb/internal/relation"
	"github.com/Duke1616/ecmdb/internal/resource"
	"github.com/Duke1616/ecmdb/internal/terminal/internal/web"
)

// Injectors from wire.go:

func InitModule(relationModule *relation.Module, resourceModule *resource.Module, attributeModule *attribute.Module) (*web.Handler, error) {
	v := relationModule.RRSvc
	v2 := resourceModule.EncryptedSvc
	v3 := attributeModule.Svc
	handler := web.NewHandler(v, v2, v3)
	return handler, nil
}
