// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package endpoint

import (
	"github.com/Duke1616/ecmdb/internal/endpoint/internal/repository"
	"github.com/Duke1616/ecmdb/internal/endpoint/internal/repository/dao"
	"github.com/Duke1616/ecmdb/internal/endpoint/internal/service"
	"github.com/Duke1616/ecmdb/internal/endpoint/internal/web"
	"github.com/Duke1616/ecmdb/pkg/mongox"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *mongox.Mongo) (*Module, error) {
	endpointDAO := dao.NewEndpointDAO(db)
	endpointRepository := repository.NewEndpointRepository(endpointDAO)
	serviceService := service.NewService(endpointRepository)
	handler := web.NewHandler(serviceService)
	module := &Module{
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService, repository.NewEndpointRepository, dao.NewEndpointDAO)
