// Code generated by eiam permgen. DO NOT EDIT.

package model

import "github.com/Duke1616/eiam/pkg/web/capability"

var (
	// Attribute 模型管理/属性管理 (cmdb:attribute)
	Attribute = capability.Model{
		Service: "cmdb",
		Name:    "attribute",
		Group:   "模型管理/属性管理",
		Scope:   capability.ScopeTenant,
	}
	// Dataio 资产仓库/导入导出 (cmdb:dataio)
	Dataio = capability.Model{
		Service: "cmdb",
		Name:    "dataio",
		Group:   "资产仓库/导入导出",
		Scope:   capability.ScopeTenant,
	}
	// Model 模型管理 (cmdb:model)
	Model = capability.Model{
		Service: "cmdb",
		Name:    "model",
		Group:   "模型管理",
		Scope:   capability.ScopeTenant,
	}
	// Plugin 插件中心/插件管理 (cmdb:plugin)
	Plugin = capability.Model{
		Service: "cmdb",
		Name:    "plugin",
		Group:   "插件中心/插件管理",
		Scope:   capability.ScopeTenant,
	}
	// Relation 关联类型 (cmdb:relation)
	Relation = capability.Model{
		Service: "cmdb",
		Name:    "relation",
		Group:   "关联类型",
		Scope:   capability.ScopeTenant,
	}
	// Resource 资产仓库 (cmdb:resource)
	Resource = capability.Model{
		Service: "cmdb",
		Name:    "resource",
		Group:   "资产仓库",
		Scope:   capability.ScopeTenant,
	}
	// Tools 资产仓库/文件管理 (cmdb:tools)
	Tools = capability.Model{
		Service: "cmdb",
		Name:    "tools",
		Group:   "资产仓库/文件管理",
		Scope:   capability.ScopeTenant,
	}
)
