// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package template

import (
	"context"
	"github.com/Duke1616/ecmdb/internal/template/internal/event"
	"github.com/Duke1616/ecmdb/internal/template/internal/service"
	"github.com/Duke1616/ecmdb/internal/template/internal/web"
	"github.com/ecodeclub/mq-api"
	"github.com/google/wire"
	"github.com/xen0n/go-workwx"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, workAPP *workwx.WorkwxApp) (*Module, error) {
	serviceService := service.NewService()
	wechatApprovalCallbackConsumer := initConsumer(serviceService, q, workAPP)
	handler := web.NewHandler(serviceService)
	module := &Module{
		Svc: serviceService,
		c:   wechatApprovalCallbackConsumer,
		Hdl: handler,
	}
	return module, nil
}

// wire.go:

var ProviderSet = wire.NewSet(web.NewHandler, service.NewService)

func initConsumer(svc service.Service, q mq.MQ, workAPP *workwx.WorkwxApp) *event.WechatApprovalCallbackConsumer {
	consumer, err := event.NewWechatApprovalCallbackConsumer(svc, q, workAPP)
	if err != nil {
		panic(err)
	}

	consumer.Start(context.Background())
	return consumer
}
